# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/plasma-vault/kded/ui/passwordchooserwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PasswordChooserWidget(object):
    def setupUi(self, PasswordChooserWidget):
        PasswordChooserWidget.setObjectName("PasswordChooserWidget")
        PasswordChooserWidget.resize(653, 160)
        self.verticalLayout = QtWidgets.QVBoxLayout(PasswordChooserWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(PasswordChooserWidget)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.editPassword = KNewPasswordWidget(PasswordChooserWidget)
        self.editPassword.setObjectName("editPassword")
        self.verticalLayout.addWidget(self.editPassword)

        self.retranslateUi(PasswordChooserWidget)
        QtCore.QMetaObject.connectSlotsByName(PasswordChooserWidget)

    def retranslateUi(self, PasswordChooserWidget):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("PasswordChooserWidget", "Mind that there is no way to recover a forgotten password. If you forget the password, your data is as good as gone."))
from knewpasswordwidget import KNewPasswordWidget
