# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/plasma-vault/kded/ui/vaultconfigurationdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VaultConfigurationDialog(object):
    def setupUi(self, VaultConfigurationDialog):
        VaultConfigurationDialog.setObjectName("VaultConfigurationDialog")
        VaultConfigurationDialog.resize(646, 529)
        icon = QtGui.QIcon.fromTheme("plasmavault")
        VaultConfigurationDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(VaultConfigurationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameUnlockVault = QtWidgets.QFrame(VaultConfigurationDialog)
        self.frameUnlockVault.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameUnlockVault.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUnlockVault.setObjectName("frameUnlockVault")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameUnlockVault)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frameUnlockVault)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonCloseVault = QtWidgets.QPushButton(self.frameUnlockVault)
        self.buttonCloseVault.setObjectName("buttonCloseVault")
        self.horizontalLayout.addWidget(self.buttonCloseVault)
        self.verticalLayout.addWidget(self.frameUnlockVault)
        self.container = QtWidgets.QWidget(VaultConfigurationDialog)
        self.container.setObjectName("container")
        self.verticalLayout.addWidget(self.container)
        self.message = KMessageWidget(VaultConfigurationDialog)
        self.message.setCloseButtonVisible(False)
        self.message.setObjectName("message")
        self.verticalLayout.addWidget(self.message)
        self.buttons = QtWidgets.QDialogButtonBox(VaultConfigurationDialog)
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons.setObjectName("buttons")
        self.verticalLayout.addWidget(self.buttons)

        self.retranslateUi(VaultConfigurationDialog)
        self.buttons.accepted.connect(VaultConfigurationDialog.accept) # type: ignore
        self.buttons.rejected.connect(VaultConfigurationDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(VaultConfigurationDialog)

    def retranslateUi(self, VaultConfigurationDialog):
        _translate = QtCore.QCoreApplication.translate
        VaultConfigurationDialog.setWindowTitle(_translate("VaultConfigurationDialog", "Dialog"))
        self.label.setText(_translate("VaultConfigurationDialog", "The vault configuration can only be changed while it is closed."))
        self.buttonCloseVault.setText(_translate("VaultConfigurationDialog", "Close the vault"))
from kmessagewidget import KMessageWidget
