#!/bin/bash

set -e

gsettings set org.lingmo.power-manager sleep-computer-ac -1 || true
gsettings set org.lingmo.power-manager sleep-computer-battery -1 || true

gsettings set org.lingmo.screensaver idle-lock -1 || true
gsettings set org.lingmo.screensaver idle-delay -1 || true
gsettings set org.lingmo.screensaver idle-activation-enabled false || true

gsettings set org.lingmo.power-manager sleep-display-ac -1 || true
gsettings set org.lingmo.power-manager sleep-display-battery -1 || true



