#!/bin/sh

mv /usr/bin/lingmo-greeter-wayland /usr/bin/lingmo-greeter
mv /var/lightdm-lingmo-greeter-wayland /etc/lingmo/greeters.d/lightdm-lingmo-greeter
mv /usr/share/xgreeters/lightdm-lingmo-greeter-wayland.desktop /usr/share/xgreeters/lightdm-lingmo-greeter.desktop
mv /usr/share/dsg/configs/org.lingmo.ocean.lightdm-lingmo-greeter/lightdm-lingmo-greeter-default-wayland.json /usr/share/dsg/configs/org.lingmo.ocean.lightdm-lingmo-greeter/org.lingmo.ocean.lightdm-lingmo-greeter.json
mv /usr/bin/kwin_wayland_helper-wayland /usr/bin/kwin_wayland_helper
