################################################################################
#
# mjpg-streamer
#
################################################################################

MJPG_STREAMER_VERSION = 5a6e0a2db163e6ae9461552b59079870d0959340
MJPG_STREAMER_SITE = $(call github,jacksonliam,mjpg-streamer,$(MJPG_STREAMER_VERSION))
MJPG_STREAMER_SUBDIR = mjpg-streamer-experimental
MJPG_STREAMER_LICENSE = GPL-2.0+
MJPG_STREAMER_LICENSE_FILES = $(MJPG_STREAMER_SUBDIR)/LICENSE
MJPG_STREAMER_DEPENDENCIES = jpeg

ifeq ($(LINGMO_PACKAGE_LIBGPHOTO2),y)
MJPG_STREAMER_CONF_OPTS += -DPLUGIN_INPUT_PTP2=ON
MJPG_STREAMER_DEPENDENCIES += host-pkgconf libgphoto2
else
MJPG_STREAMER_CONF_OPTS += -DPLUGIN_INPUT_PTP2=OFF
endif

ifeq ($(LINGMO_PACKAGE_LIBV4L),y)
MJPG_STREAMER_DEPENDENCIES += libv4l
endif

ifeq ($(LINGMO_PACKAGE_OPENCV3_LIB_HIGHGUI)$(LINGMO_PACKAGE_OPENCV3_LIB_IMGPROC)$(LINGMO_PACKAGE_OPENCV3_LIB_VIDEOIO),yyy)
MJPG_STREAMER_CONF_OPTS += \
	-DPLUGIN_INPUT_OPENCV=ON \
	-DPLUGIN_CVFILTER_CPP=OFF \
	-DPLUGIN_CVFILTER_PY=OFF
MJPG_STREAMER_DEPENDENCIES += host-pkgconf opencv3
else
MJPG_STREAMER_CONF_OPTS += -DPLUGIN_INPUT_OPENCV=OFF
endif

ifeq ($(LINGMO_PACKAGE_PROTOBUF_C)$(LINGMO_PACKAGE_ZEROMQ),yy)
MJPG_STREAMER_CONF_OPTS += -DPLUGIN_OUTPUT_ZMQSERVER=ON
MJPG_STREAMER_DEPENDENCIES += host-pkgconf protobuf-c zeromq
else
MJPG_STREAMER_CONF_OPTS += -DPLUGIN_OUTPUT_ZMQSERVER=OFF
endif

ifeq ($(LINGMO_PACKAGE_SDL),y)
MJPG_STREAMER_CONF_OPTS += -DPLUGIN_OUTPUT_VIEWER=ON
MJPG_STREAMER_DEPENDENCIES += host-pkgconf sdl
else
MJPG_STREAMER_CONF_OPTS += -DPLUGIN_OUTPUT_VIEWER=OFF
endif

$(eval $(cmake-package))
