#!/bin/bash

set -e

if [[ "${is_minimal}" = "true" ]]; then
    return 0
elif [[ "${is_ghost}" = "true" ]]; then
    return 0
fi

if [[ -d /cdrom/QC ]]; then
    /usr/bin/rsync -a /cdrom/QC/ /usr/share/oem-test/
fi
