.\" Man Page for lingmo-virtual-keyboard
.TH lingmo-virtual-keyboard 1 "26 July 2023"
.SH "NAME"
lingmo-virtual-keyboard \- The virtual keyboard based on fcitx5.
.SH "SYNOPSIS"
.B lingmo-virtual-keyboard
.SH "DESCRIPTION"
The virtual keyboard based on fcitx5.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at:
https://gitee.com/lingmo/lingmo-virtual-keyboard/issues
.SH "AUTHORS"
.SS This Manual Page has been written for the InputMethod team by:
hanteng <hanteng@kylinos.cn> (2023)