#!/bin/sh

set -e
echo "version,codename,series,created,release,eol" > /usr/share/distro-info/lingmo.csv
echo "3.0.0,Helium,helium,2025-04-05" >> /usr/share/distro-info/lingmo.csv


case "${1}" in
	configure)
	    update-alternatives --install /etc/lingmo-version \
		    deepin-version /usr/lib/lingmo/lingmo-version 50

	    if [ -x /usr/sbin/update-initramfs ]
	    then
		    update-initramfs -u
	    fi

        if [ -x /usr/sbin/update-grub ]
        then
            /usr/sbin/update-grub || echo "update-grub failed! Ignore..." >&2
        fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		;;
esac

#DEBHELPER#

exit 0
