#! /bin/sh
set -e

#DEBHELPER#

case "$1" in
    remove|deconfigure|failed-upgrade)
	update-alternatives --remove lingmo-default-background \
	    /usr/share/backgrounds/lingmo/desktop.jpg

	update-alternatives --remove lingmo-version \
	    /usr/lib/lingmo/desktop-version
	;;
esac

