development-files/lingmosdk-kabase.pc /usr/share/pkgconfig/
usr/include/lingmosdk/applications/kabase/application_access.hpp
usr/include/lingmosdk/applications/kabase/buried_point.hpp
usr/include/lingmosdk/applications/kabase/currency.hpp
usr/include/lingmosdk/applications/kabase/dbus.hpp
usr/include/lingmosdk/applications/kabase/gsettings.hpp
usr/include/lingmosdk/applications/kabase/log.hpp
usr/include/lingmosdk/applications/kabase/lingmo_image_codec/lingmoimagecodec.hpp
usr/include/lingmosdk/applications/kabase/lingmo_image_codec/lingmoimagecodec_global.hpp
usr/include/lingmosdk/applications/kabase/lingmo_image_codec/loadmovie.hpp
usr/include/lingmosdk/applications/kabase/lingmo_image_codec/savemovie.hpp
usr/include/lingmosdk/applications/kabase/lingmo_system/session_management.hpp
usr/include/lingmosdk/applications/kabase/lingmo_system/system_information.hpp
usr/include/lingmosdk/applications/kabase/lingmo_system/theme_management.hpp
usr/include/lingmosdk/applications/kabase/lingmo_system/user_manual.hpp
usr/include/lingmosdk/applications/kabase/lingmo_system/window_management.hpp
usr/include/lingmosdk/applications/kabase/single_application/single_application.hpp

usr/lib/*/liblingmosdk-kabase.so
