#!/bin/bash

#[ ! -d /usr/share/xsessions ] && mkdir -p /usr/share/xsessions 
#[ -f /usr/share/wayland-sessions/lingmo.desktop ] && mv -f /usr/share/wayland-sessions/lingmo.desktop /usr/share/xsessions/lingmo.desktop
[ -f /etc/udcp-client.conf ] && rm -f /etc/udcp-client.conf

chown root Xlingmo
chgrp root Xlingmo
chmod +s /usr/bin/Xlingmo

