// SPDX-FileCopyrightText: 2022 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: LGPL-3.0-or-later

#define DTK_NAMESPACE Dtk
#define DNETWORKMANAGER_NAMESPACE NetworkManager
#define DTK_DNETWORKMANAGER_NAMESPACE DTK_NAMESPACE::DNETWORKMANAGER_NAMESPACE

#define DNETWORKMANAGER_USE_NAMESPACE using namespace DTK_DNETWORKMANAGER_NAMESPACE;

#define DNETWORKMANAGER_BEGIN_NAMESPACE namespace DTK_NAMESPACE { namespace DNETWORKMANAGER_NAMESPACE {

#define DNETWORKMANAGER_END_NAMESPACE }}
