#!/bin/bash
#
# mkdir data_base
 
function read_dir(){
for file in `ls base`
	do
		if [ -d $1"/"$file ]
		then
		read_dir $1"/"$file
		else
		# echo $1"/"$file
		cd base/$file
		makepkg --skipchecksums --nodeps --nobuild --skippgpcheck
		cd ../../
		fi
	done
}
 
read_dir $1
