.TH "libkyocr" 3 "Wed Sep 20 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libkyocr - OCR 文字识别功能
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkdk::kdkOCR\fP"
.br
.RI "OCR文字识别功能类 主要用来获取文字框和获取文字内容 "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< std::vector< std::vector< int > > > \fBkdk::kdkOCR::getRect\fP (const std::string &imagePath)"
.br
.RI "获取文字框 "
.ti -1c
.RI "std::vector< std::string > \fBkdk::kdkOCR::getCls\fP (const std::string &imagePath, int nums)"
.br
.RI "获取文字内容 "
.ti -1c
.in -1c
.SH "Detailed Description"
.PP 
此库的主要功能是提供OCR文字识别接口和类

.SH "Function Documentation"
.PP 
.SS "std::vector<std::string> kdk::kdkOCR::getCls (const std::string & imagePath, int nums)"

.PP
获取文字内容 
.PP
\fBParameters\fP
.RS 4
\fIString\fP 图片文件路径 
.br
\fInums\fP 同时处理的文字栈个数 
.RE
.PP
\fBReturns\fP
.RS 4
Vector<string> 图片中的文字字符串 
.RE
.PP

.PP
Referenced by getCls()\&.
.SS "std::vector<std::vector<std::vector<int> > > kdk::kdkOCR::getRect (const std::string & imagePath)"

.PP
获取文字框 
.PP
\fBParameters\fP
.RS 4
\fIString\fP 图片文件路径 
.RE
.PP
\fBReturns\fP
.RS 4
Vector<vector<vector<vector<int> 文字框点的坐标矩阵、以及文字框的个数 
.RE
.PP

.PP
Referenced by getRect()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libkyocr.hpp from the source code\&.
