#!/bin/sh

set -e

if [ "x$1" = xremove ]; then
	update-alternatives \
		--remove default.plymouth /usr/share/plymouth/themes/lingmo-plymouth/lingmo-plymouth.plymouth

        update-alternatives \
		--remove text.plymouth /usr/share/plymouth/themes/lingmo-text/lingmo-text.plymouth
fi

#DEBHELPER#
