usr/bin/appwidgetprovider-clock-demo
usr/bin/appwidgetprovider-clock-service
usr/bin/appwidgetprovider-search-demo
usr/bin/appwidgetuser-demo
usr/share/appwidget/qml/democlock.qml
usr/share/appwidget/qml/demosearch.qml
usr/share/appwidget/config/*.conf
usr/share/appwidgetdemo/clock/*.png
usr/share/dbus-1/services/org.lingmo.appwidget.provider.democlock.service
usr/share/dbus-1/services/org.lingmo.appwidget.provider.demosearch.service
usr/share/appwidgetdemo/search/*.png
usr/share/appwidgetdemo/search/*.svg

