.TH "kdk::KTranslucentFloor" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KTranslucentFloor \- 提供一个半透明底板，可作为基础窗体进行布局  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ktranslucentfloor\&.h>\fP
.PP
Inherits QFrame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKTranslucentFloor\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBsetBorderRadius\fP (int radius)"
.br
.RI "设置圆角半径 "
.ti -1c
.RI "int \fBborderRadius\fP ()"
.br
.RI "返回圆角半径 "
.ti -1c
.RI "void \fBsetShadow\fP (bool flag)"
.br
.RI "设置是否显示阴影 "
.ti -1c
.RI "bool \fBshadow\fP ()"
.br
.RI "返回是否显示阴影 "
.ti -1c
.RI "void \fBsetEnableBlur\fP (bool flag)"
.br
.RI "设置是否启用毛玻璃效果 "
.ti -1c
.RI "bool \fBenableBlur\fP ()"
.br
.RI "获取是否已启用毛玻璃效果 "
.ti -1c
.RI "void \fBsetOpacity\fP (qreal \fBopacity\fP)"
.br
.RI "设置透明度 "
.ti -1c
.RI "qreal \fBopacity\fP ()"
.br
.RI "获取透明度 "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
提供一个半透明底板，可作为基础窗体进行布局 


.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int kdk::KTranslucentFloor::borderRadius ()"

.PP
返回圆角半径 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "bool kdk::KTranslucentFloor::enableBlur ()"

.PP
获取是否已启用毛玻璃效果 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "qreal kdk::KTranslucentFloor::opacity ()"

.PP
获取透明度 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "void kdk::KTranslucentFloor::setBorderRadius (int radius)"

.PP
设置圆角半径 
.PP
\fBParameters\fP
.RS 4
\fIradius\fP 
.RE
.PP

.SS "void kdk::KTranslucentFloor::setEnableBlur (bool flag)"

.PP
设置是否启用毛玻璃效果 
.PP
\fBParameters\fP
.RS 4
\fIflag\fP 
.RE
.PP

.SS "void kdk::KTranslucentFloor::setOpacity (qreal opacity)"

.PP
设置透明度 
.PP
\fBParameters\fP
.RS 4
\fIopacity\fP 
.RE
.PP

.SS "void kdk::KTranslucentFloor::setShadow (bool flag)"

.PP
设置是否显示阴影 
.PP
\fBParameters\fP
.RS 4
\fIflag\fP 
.RE
.PP

.SS "bool kdk::KTranslucentFloor::shadow ()"

.PP
返回是否显示阴影 
.PP
\fBReturns\fP
.RS 4

.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
