.TH "kdk::KColorComboBox" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KColorComboBox \- 颜色选择框  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kcolorcombobox\&.h>\fP
.PP
Inherits QComboBox\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBComboType\fP { \fBCircle\fP, \fBRoundedRect\fP }"
.br
.RI "指定显示样式，圆形或者圆角矩形 "
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBactivated\fP (const QColor &color)"
.br
.ti -1c
.RI "void \fBcurrentColorChanged\fP (const QColor &color)"
.br
.ti -1c
.RI "void \fBhighlighted\fP (const QColor &color)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKColorComboBox\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBsetColorList\fP (const QList< QColor > &list)"
.br
.RI "以列表形式添加颜色选项 "
.ti -1c
.RI "QList< QColor > \fBcolorList\fP ()"
.br
.RI "获取颜色列表 "
.ti -1c
.RI "void \fBaddColor\fP (const QColor &color)"
.br
.RI "添加颜色选项 "
.ti -1c
.RI "void \fBsetComboType\fP (const \fBComboType\fP &type)"
.br
.RI "设置显示样式 "
.ti -1c
.RI "\fBComboType\fP \fBcomboType\fP ()"
.br
.RI "获取显示样式 "
.ti -1c
.RI "void \fBsetPopupItemSize\fP (const QSize &size)"
.br
.RI "设置item尺寸 "
.ti -1c
.RI "QSize \fBpopupItemSzie\fP ()"
.br
.RI "返回item尺寸 "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *event) override"
.br
.ti -1c
.RI "void \fBresizeEvent\fP (QResizeEvent *event) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
颜色选择框 


.PP
\fBSince\fP
.RS 4
2\&.0 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void kdk::KColorComboBox::addColor (const QColor & color)"

.PP
添加颜色选项 
.PP
\fBParameters\fP
.RS 4
\fIcolor\fP 
.RE
.PP

.SS "QList<QColor> kdk::KColorComboBox::colorList ()"

.PP
获取颜色列表 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "\fBComboType\fP kdk::KColorComboBox::comboType ()"

.PP
获取显示样式 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "QSize kdk::KColorComboBox::popupItemSzie ()"

.PP
返回item尺寸 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "void kdk::KColorComboBox::setColorList (const QList< QColor > & list)"

.PP
以列表形式添加颜色选项 
.PP
\fBParameters\fP
.RS 4
\fIlist\fP 
.RE
.PP

.SS "void kdk::KColorComboBox::setComboType (const \fBComboType\fP & type)"

.PP
设置显示样式 
.PP
\fBParameters\fP
.RS 4
\fItype\fP 
.RE
.PP

.SS "void kdk::KColorComboBox::setPopupItemSize (const QSize & size)"

.PP
设置item尺寸 
.PP
\fBParameters\fP
.RS 4
\fIsize\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
