.TH "kdk::KItemWidget" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KItemWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKItemWidget\fP (const QIcon &Myicon, QString MmainText, QString MsecText, QWidget *parent)"
.br
.ti -1c
.RI "void \fBSetInverse\fP ()"
.br
.ti -1c
.RI "void \fBCancelInverse\fP ()"
.br
.ti -1c
.RI "void \fBSetIconSize\fP (QSize size)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *event)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
