.TH "kdk::KWindowButtonBar" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KWindowButtonBar \- 窗口三联按钮和菜单按钮的集合  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kwindowbuttonbar\&.h>\fP
.PP
Inherits QFrame\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBdoubleClick\fP ()"
.br
.RI "双击会发出双击信号，父widget可以绑定相应槽函数 "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKWindowButtonBar\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "QPushButton * \fBminimumButton\fP ()"
.br
.RI "获取最小化按钮 "
.ti -1c
.RI "QPushButton * \fBmaximumButton\fP ()"
.br
.RI "获取最大化按钮 "
.ti -1c
.RI "QPushButton * \fBcloseButton\fP ()"
.br
.RI "获取关闭按钮 "
.ti -1c
.RI "\fBKMenuButton\fP * \fBmenuButton\fP ()"
.br
.RI "获取菜单按钮 "
.ti -1c
.RI "\fBMaximumButtonState\fP \fBmaximumButtonState\fP ()"
.br
.RI "获取最大化按钮的状态(最大化/恢复) "
.ti -1c
.RI "void \fBsetMaximumButtonState\fP (\fBMaximumButtonState\fP state)"
.br
.RI "设置最大化按钮图标状态（最大化/恢复） "
.ti -1c
.RI "void \fBsetFollowMode\fP (bool flag)"
.br
.RI "设置是否遵循模式 "
.ti -1c
.RI "bool \fBfollowMode\fP ()"
.br
.RI "返回是否遵循模式 "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBmouseDoubleClickEvent\fP (QMouseEvent *event)"
.br
.ti -1c
.RI "bool \fBeventFilter\fP (QObject *watched, QEvent *event)"
.br
.ti -1c
.RI "QSize \fBsizeHint\fP () const override"
.br
.in -1c
.SH "Detailed Description"
.PP 
窗口三联按钮和菜单按钮的集合 

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
