.TH "kdk::KDialog" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KDialog \- 继承自 QDialog，支持响应式主题背景切换和图标主题切换、 标题颜色响应窗口激活状态  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kdialog\&.h>\fP
.PP
Inherits QDialog, and ThemeController\&.
.PP
Inherited by \fBkdk::KAboutDialog\fP, \fBkdk::KInputDialog\fP, \fBkdk::KMessageBox\fP, \fBkdk::KProgressDialog\fP, and \fBkdk::KUninstallDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKDialog\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBsetWindowIcon\fP (const QIcon &icon)"
.br
.RI "设置对话框图标 "
.ti -1c
.RI "void \fBsetWindowIcon\fP (const QString &iconName)"
.br
.RI "设置对话框图标 "
.ti -1c
.RI "void \fBsetWindowTitle\fP (const QString &)"
.br
.RI "设置对话框标题名称 "
.ti -1c
.RI "QPushButton * \fBmaximumButton\fP ()"
.br
.RI "获取最大化按钮 "
.ti -1c
.RI "QPushButton * \fBminimumButton\fP ()"
.br
.RI "获取最小化按钮 "
.ti -1c
.RI "QPushButton * \fBcloseButton\fP ()"
.br
.RI "获取关闭按钮 "
.ti -1c
.RI "\fBKMenuButton\fP * \fBmenuButton\fP ()"
.br
.RI "获取下拉菜单按钮 "
.ti -1c
.RI "QWidget * \fBmainWidget\fP ()"
.br
.RI "获取主内容区Widget "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBeventFilter\fP (QObject *target, QEvent *event) override"
.br
.ti -1c
.RI "void \fBchangeTheme\fP ()"
.br
.ti -1c
.RI "void \fBchangeIconStyle\fP ()"
.br
.ti -1c
.RI "QBoxLayout * \fBmainLayout\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
继承自 QDialog，支持响应式主题背景切换和图标主题切换、 标题颜色响应窗口激活状态 

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
