.TH "kdk::KTabBar" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KTabBar \- 支持三种样式  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ktabbar\&.h>\fP
.PP
Inherits QTabBar\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKTabBar\fP (\fBKTabBarStyle\fP \fBbarStyle\fP=SegmentLight, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBsetTabBarStyle\fP (\fBKTabBarStyle\fP \fBbarStyle\fP)"
.br
.RI "设置TabBar样式 "
.ti -1c
.RI "\fBKTabBarStyle\fP \fBbarStyle\fP ()"
.br
.RI "返回TabBar样式 "
.ti -1c
.RI "void \fBsetBorderRadius\fP (int radius)"
.br
.RI "设置圆角半径，只对SegmentDark，SegmentLight样式生效 "
.ti -1c
.RI "int \fBborderRadius\fP ()"
.br
.RI "获取圆角半径 "
.ti -1c
.RI "void \fBsetBackgroundColor\fP (const QColor &color)"
.br
.RI "设置背景色 "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "QSize \fBsizeHint\fP () const"
.br
.ti -1c
.RI "QSize \fBminimumTabSizeHint\fP (int index) const"
.br
.ti -1c
.RI "QSize \fBtabSizeHint\fP (int index) const"
.br
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
支持三种样式 

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
