.TH "kdk::KNavigationBar" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KNavigationBar \- 导航栏控件  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <knavigationbar\&.h>\fP
.PP
Inherits QScrollArea\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKNavigationBar\fP (QWidget *parent)"
.br
.ti -1c
.RI "void \fBaddItem\fP (QStandardItem *item)"
.br
.RI "增加常规Item "
.ti -1c
.RI "void \fBaddSubItem\fP (QStandardItem *subItem)"
.br
.RI "增加次级Item "
.ti -1c
.RI "void \fBaddGroupItems\fP (QList< QStandardItem * >items, const QString &tag)"
.br
.RI "成组增加Item,在导航栏中会显示tag "
.ti -1c
.RI "void \fBaddTag\fP (const QString &tag)"
.br
.RI "添加tag "
.ti -1c
.RI "QStandardItemModel * \fBmodel\fP ()"
.br
.RI "获取model "
.ti -1c
.RI "QListView * \fBlistview\fP ()"
.br
.RI "获取view "
.in -1c
.SH "Detailed Description"
.PP 
导航栏控件 
.PP
\fBExamples\fP
.in +1c
\fBtestnavigationbar/widget\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
