.TH "kdk::KProgressDialog" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KProgressDialog \- 进度对话框，会实时显示当前进度  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kprogressdialog\&.h>\fP
.PP
Inherits \fBkdk::KDialog\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBcancel\fP ()"
.br
.RI "取消进度条 "
.ti -1c
.RI "void \fBreset\fP ()"
.br
.RI "重置进度条 "
.ti -1c
.RI "void \fBsetMaximum\fP (int \fBmaximum\fP)"
.br
.RI "设置最大值 "
.ti -1c
.RI "void \fBsetMinimum\fP (int \fBminimum\fP)"
.br
.RI "设置最小值 "
.ti -1c
.RI "void \fBsetRange\fP (int \fBminimum\fP, int \fBmaximum\fP)"
.br
.RI "设置范围 "
.ti -1c
.RI "void \fBsetValue\fP (int progress)"
.br
.RI "设置当前值 "
.ti -1c
.RI "void \fBsetLabelText\fP (const QString &text)"
.br
.RI "设置提示内容 "
.ti -1c
.RI "void \fBsetCancelButtonText\fP (const QString &text)"
.br
.RI "设置取消按钮内容 "
.ti -1c
.RI "void \fBsetSubContent\fP (const QString &text)"
.br
.RI "设置次级内容 "
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBcanceled\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKProgressDialog\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fBKProgressDialog\fP (const QString &\fBlabelText\fP, const QString &cancelButtonText='cancel', int \fBminimum\fP=0, int \fBmaximum\fP=100, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBsetLabel\fP (QLabel *label)"
.br
.RI "设置提示文字 "
.ti -1c
.RI "void \fBsetCancelButton\fP (QPushButton *button)"
.br
.RI "设置取消按钮 "
.ti -1c
.RI "void \fBsetBar\fP (QProgressBar *bar)"
.br
.RI "设置进度条 "
.ti -1c
.RI "void \fBsetSuffix\fP (const QString &suffix)"
.br
.RI "设置detail的后缀 "
.ti -1c
.RI "void \fBsetShowDetail\fP (bool flag)"
.br
.RI "设置是否显示详细信息 "
.ti -1c
.RI "int \fBminimum\fP () const"
.br
.RI "返回最小值 "
.ti -1c
.RI "int \fBmaximum\fP () const"
.br
.RI "返回最大值 "
.ti -1c
.RI "int \fBvalue\fP () const"
.br
.RI "返回当前值 "
.ti -1c
.RI "QString \fBlabelText\fP () const"
.br
.RI "返回提示内容 "
.ti -1c
.RI "void \fBsetAutoReset\fP (bool \fBreset\fP)"
.br
.RI "设置自动重置 "
.ti -1c
.RI "bool \fBautoReset\fP () const"
.br
.RI "返回是否自动重置 "
.ti -1c
.RI "void \fBsetAutoClose\fP (bool close)"
.br
.RI "设置是否自动关闭对话框 "
.ti -1c
.RI "bool \fBautoClose\fP () const"
.br
.RI "返回是否自动关闭对话框 "
.ti -1c
.RI "QProgressBar * \fBprogressBar\fP ()"
.br
.RI "获取进度条 "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBchangeTheme\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
进度对话框，会实时显示当前进度 
.PP
\fBExamples\fP
.in +1c
\fBtestprogressdialog/widget\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
