.TH "kdk::KDragWidget" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KDragWidget \- 拖动文件或文件夹，可识别并获取文件或文件夹路径  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kdragwidget\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBgetPath\fP (QString)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKDragWidget\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fBKPushButton\fP * \fBiconButton\fP ()"
.br
.RI "iconButton "
.ti -1c
.RI "QLabel * \fBtextLabel\fP ()"
.br
.RI "textLabel "
.ti -1c
.RI "QFileDialog * \fBfileDialog\fP ()"
.br
.RI "fileDialog "
.ti -1c
.RI "void \fBsetNameFilter\fP (const QString &filter)"
.br
.RI "将文件对话框中使用的过滤器设置为给定的过滤器。 "
.ti -1c
.RI "void \fBsetNameFilters\fP (const QStringList &filters)"
.br
.RI "设置文件对话框中使用的过滤器。 "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBmouseMoveEvent\fP (QMouseEvent *event)"
.br
.ti -1c
.RI "void \fBmousePressEvent\fP (QMouseEvent *event)"
.br
.ti -1c
.RI "void \fBmouseReleaseEvent\fP (QMouseEvent *event)"
.br
.ti -1c
.RI "void \fBkeyPressEvent\fP (QKeyEvent *event)"
.br
.ti -1c
.RI "void \fBkeyReleaseEvent\fP (QKeyEvent *event)"
.br
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *event)"
.br
.ti -1c
.RI "bool \fBeventFilter\fP (QObject *watched, QEvent *event)"
.br
.ti -1c
.RI "void \fBdragEnterEvent\fP (QDragEnterEvent *event)"
.br
.ti -1c
.RI "void \fBdragLeaveEvent\fP (QDragLeaveEvent *event)"
.br
.ti -1c
.RI "void \fBdragMoveEvent\fP (QDragMoveEvent *event)"
.br
.ti -1c
.RI "void \fBdropEvent\fP (QDropEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
拖动文件或文件夹，可识别并获取文件或文件夹路径 


.PP
\fBSince\fP
.RS 4
2\&.3 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "QFileDialog* kdk::KDragWidget::fileDialog ()"

.PP
fileDialog 
.PP
\fBReturns\fP
.RS 4
返回QFiledialog 
.RE
.PP

.SS "\fBKPushButton\fP* kdk::KDragWidget::iconButton ()"

.PP
iconButton 
.PP
\fBReturns\fP
.RS 4
返回iconbutton 
.RE
.PP

.SS "void kdk::KDragWidget::setNameFilter (const QString & filter)"

.PP
将文件对话框中使用的过滤器设置为给定的过滤器。 
.PP
\fBParameters\fP
.RS 4
\fIfilter\fP 
.RE
.PP

.SS "void kdk::KDragWidget::setNameFilters (const QStringList & filters)"

.PP
设置文件对话框中使用的过滤器。 
.PP
\fBParameters\fP
.RS 4
\fIfilters\fP 
.RE
.PP

.SS "QLabel* kdk::KDragWidget::textLabel ()"

.PP
textLabel 
.PP
\fBReturns\fP
.RS 4
返回textlabel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
