.TH "kdk::KPressButton" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KPressButton \- 按压按钮，可根据情况设置loading状态  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kpressbutton\&.h>\fP
.PP
Inherits QPushButton\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBButtonType\fP { \fBNormalType\fP, \fBCircleType\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKPressButton\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetBorderRadius\fP (int radius)"
.br
.RI "设置圆角 "
.ti -1c
.RI "void \fBsetBorderRadius\fP (int bottomLeft, int topLeft, int topRight, int bottomRight)"
.br
.RI "设置圆角 "
.ti -1c
.RI "void \fBsetCheckable\fP (bool)"
.br
.RI "设置是否可选中 "
.ti -1c
.RI "bool \fBisCheckable\fP () const"
.br
.RI "返回是否可选中 "
.ti -1c
.RI "void \fBsetChecked\fP (bool)"
.br
.RI "设置是否选中 "
.ti -1c
.RI "bool \fBisChecked\fP () const"
.br
.RI "返回是否选中 "
.ti -1c
.RI "void \fBsetButtonType\fP (ButtonType type)"
.br
.RI "设置button类型 "
.ti -1c
.RI "KPressButton::ButtonType \fBbuttonType\fP ()"
.br
.RI "返回button类型 "
.ti -1c
.RI "void \fBsetLoaingStatus\fP (bool flag)"
.br
.RI "设置是否启用loading状态 "
.ti -1c
.RI "bool \fBisLoading\fP ()"
.br
.RI "返回是否启用loading状态 "
.ti -1c
.RI "void \fBsetTranslucent\fP (bool flag)"
.br
.RI "设置是否启用透明度 "
.ti -1c
.RI "bool \fBisTranslucent\fP ()"
.br
.RI "返回是否启用透明度 "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *event) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
按压按钮，可根据情况设置loading状态 


.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "KPressButton::ButtonType kdk::KPressButton::buttonType ()"

.PP
返回button类型 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "bool kdk::KPressButton::isCheckable () const"

.PP
返回是否可选中 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "bool kdk::KPressButton::isChecked () const"

.PP
返回是否选中 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "bool kdk::KPressButton::isLoading ()"

.PP
返回是否启用loading状态 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "bool kdk::KPressButton::isTranslucent ()"

.PP
返回是否启用透明度 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "void kdk::KPressButton::setBorderRadius (int bottomLeft, int topLeft, int topRight, int bottomRight)"

.PP
设置圆角 
.PP
\fBParameters\fP
.RS 4
\fIbuttomLeft\fP 
.br
\fItopLeft\fP 
.br
\fItopRight\fP 
.br
\fIbottomRight\fP 
.RE
.PP

.SS "void kdk::KPressButton::setBorderRadius (int radius)"

.PP
设置圆角 
.PP
\fBParameters\fP
.RS 4
\fIradius\fP 
.RE
.PP

.SS "void kdk::KPressButton::setButtonType (ButtonType type)"

.PP
设置button类型 
.PP
\fBParameters\fP
.RS 4
\fItype\fP 
.RE
.PP

.SS "void kdk::KPressButton::setCheckable (bool)"

.PP
设置是否可选中 
.PP
\fBParameters\fP
.RS 4
\fIflag\fP 
.RE
.PP

.SS "void kdk::KPressButton::setChecked (bool)"

.PP
设置是否选中 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "void kdk::KPressButton::setLoaingStatus (bool flag)"

.PP
设置是否启用loading状态 
.PP
\fBParameters\fP
.RS 4
\fIflag\fP 
.RE
.PP

.SS "void kdk::KPressButton::setTranslucent (bool flag)"

.PP
设置是否启用透明度 
.PP
\fBParameters\fP
.RS 4
\fIflag\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
