.TH "kdk::KUninstallDialog" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KUninstallDialog \- 卸载对话框，当用户卸载时可能会弹出此提示对话框  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kuninstalldialog\&.h>\fP
.PP
Inherits \fBkdk::KDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKUninstallDialog\fP (QString appName, QString appVersion, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "QLabel * \fBdebAppNameLabel\fP ()"
.br
.RI "debAppNameLabel "
.ti -1c
.RI "QLabel * \fBdebNameLabel\fP ()"
.br
.RI "包名Label "
.ti -1c
.RI "QLabel * \fBdebIconLabel\fP ()"
.br
.RI "包IconLabel "
.ti -1c
.RI "QLabel * \fBdebVersionLabel\fP ()"
.br
.RI "包版本Label "
.ti -1c
.RI "QPushButton * \fBuninstallButtton\fP ()"
.br
.RI "卸载按钮 "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBchangeTheme\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
卸载对话框，当用户卸载时可能会弹出此提示对话框 

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
