.TH "kdk::Parmscontroller" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::Parmscontroller \- The \fBParmscontroller\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parmscontroller\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBParm\fP { \fBPM_TabBarHeight\fP, \fBPM_PushButtonHeight\fP, \fBPM_ToolButtonHeight\fP, \fBPM_SearchLineEditHeight\fP, \fBPM_PasswordEditHeight\fP, \fBPM_NavigationBatHeight\fP, \fBPM_TagHeight\fP, \fBPM_SearchLineEditItemHeight\fP, \fBPM_SliderHandleRadius\fP, \fBPM_SliderNodeRadius\fP, \fBPM_BadgeHeight\fP, \fBPM_IconbarHeight\fP, \fBPM_IconBarIconSize\fP, \fBPM_WindowButtonBarSize\fP, \fBPM_NavigationBatInterval\fP, \fBPM_Widget_SideWidget_Width\fP, \fBPM_InputDialog_Height\fP, \fBPM_InputDialog_Width\fP, \fBPM_InputDialog_Label_Spacing\fP, \fBPM_InputDialog_Widget_Spacing\fP, \fBPM_InputDialog_Button_Spacing\fP, \fBPM_InputDialog_Bottom_Spacing\fP, \fBPM_InputDialog_Right_Spacing\fP }"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBmodeChanged\fP (bool)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBParmscontroller\fP * \fBself\fP ()"
.br
.ti -1c
.RI "static bool \fBisTabletMode\fP ()"
.br
.ti -1c
.RI "static int \fBparm\fP (Parm p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBParmscontroller\fP class\&. 


.PP
\fBSince\fP
.RS 4
2\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
