.TH "kdk::KBadge" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KBadge \- 消息提醒气泡  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kbadge\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKBadge\fP (QWidget *parent)"
.br
.ti -1c
.RI "int \fBvalue\fP ()"
.br
.RI "返回值 "
.ti -1c
.RI "void \fBsetValue\fP (int \fBvalue\fP)"
.br
.RI "设置值，最大显示数值为999，大于999显示'\&.\&.\&.' "
.ti -1c
.RI "void \fBsetValueVisiable\fP (bool flag)"
.br
.RI "设置值是否可见 "
.ti -1c
.RI "bool \fBisValueVisiable\fP () const"
.br
.RI "获取值是否可见 "
.ti -1c
.RI "QColor \fBcolor\fP ()"
.br
.RI "获取背景色 "
.ti -1c
.RI "void \fBsetColor\fP (const QColor &\fBcolor\fP)"
.br
.RI "设置背景色 "
.ti -1c
.RI "int \fBfontSize\fP ()"
.br
.RI "获取字体大小 "
.ti -1c
.RI "void \fBsetFontSize\fP (int size)"
.br
.RI "设置字体大小 "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *event)"
.br
.ti -1c
.RI "void \fBresizeEvent\fP (QResizeEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
消息提醒气泡 
.PP
\fBExamples\fP
.in +1c
\fBtestbadge/widget\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
