.TH "kdk::KBorderButton" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KBorderButton \- 带边框的按钮  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kborderbutton\&.h>\fP
.PP
Inherits QPushButton\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKBorderButton\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fBKBorderButton\fP (const QString &text, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fBKBorderButton\fP (const QIcon &icon, const QString &text, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fBKBorderButton\fP (const QIcon &icon, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBsetIcon\fP (const QIcon &icon)"
.br
.RI "设置按钮图标 "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBeventFilter\fP (QObject *watched, QEvent *event)"
.br
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *event)"
.br
.ti -1c
.RI "QSize \fBsizeHint\fP () const override"
.br
.in -1c
.SH "Detailed Description"
.PP 
带边框的按钮 
.PP
\fBExamples\fP
.in +1c
\fBtestPushbutton/widget\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
