.TH "kdk::KSlider" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KSlider \- 支持三种样式的滑动条 非步数关系：步数为1，可以在任意位置点击和拖拽 步数关系：步数为固定值，可根据步数值点击和拖拽 节点关系：步数为节点间隔，可根据节点间隔点击和拖拽  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kslider\&.h>\fP
.PP
Inherits QSlider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKSlider\fP (QWidget *parent)"
.br
.ti -1c
.RI "\fBKSlider\fP (Qt::Orientation orientation, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBsetTickInterval\fP (int interval)"
.br
.RI "设置节点间隔 "
.ti -1c
.RI "void \fBsetSliderType\fP (KSliderType type)"
.br
.RI "设置滑动条类型 "
.ti -1c
.RI "KSliderType \fBsliderType\fP ()"
.br
.RI "获取滑动条类型 "
.ti -1c
.RI "int \fBtickInterval\fP () const"
.br
.RI "获取节点间隔 "
.ti -1c
.RI "void \fBsetValue\fP (int)"
.br
.RI "设置值 "
.ti -1c
.RI "void \fBsetNodeVisible\fP (bool flag)"
.br
.RI "设置是否显示节点 "
.ti -1c
.RI "bool \fBnodeVisible\fP ()"
.br
.RI "获取是否显示节点 "
.ti -1c
.RI "void \fBsetToolTip\fP (const QString &)"
.br
.RI "设置tooltip "
.ti -1c
.RI "QString \fBtoolTip\fP () const"
.br
.RI "获取toolTip "
.ti -1c
.RI "void \fBsetTranslucent\fP (bool flag)"
.br
.RI "设置是否启用半透明效果 "
.ti -1c
.RI "bool \fBisTranslucent\fP ()"
.br
.RI "获取是否启用半透明效果 "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *event)"
.br
.ti -1c
.RI "void \fBresizeEvent\fP (QResizeEvent *event)"
.br
.ti -1c
.RI "void \fBmousePressEvent\fP (QMouseEvent *event)"
.br
.ti -1c
.RI "void \fBmouseReleaseEvent\fP (QMouseEvent *event)"
.br
.ti -1c
.RI "void \fBmouseMoveEvent\fP (QMouseEvent *event)"
.br
.ti -1c
.RI "void \fBwheelEvent\fP (QWheelEvent *event)"
.br
.ti -1c
.RI "bool \fBeventFilter\fP (QObject *watched, QEvent *event)"
.br
.ti -1c
.RI "QSize \fBsizeHint\fP () const override"
.br
.in -1c
.SH "Detailed Description"
.PP 
支持三种样式的滑动条 非步数关系：步数为1，可以在任意位置点击和拖拽 步数关系：步数为固定值，可根据步数值点击和拖拽 节点关系：步数为节点间隔，可根据节点间隔点击和拖拽 
.PP
\fBExamples\fP
.in +1c
\fBtestslider/widget\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
