.TH "kdk::KSwitchButton" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KSwitchButton \- 指示打开/关闭两种状态  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kswitchbutton\&.h>\fP
.PP
Inherits QPushButton\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBstateChanged\fP (bool)"
.br
.RI "当选中状态发生变化时，发出此信号 "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKSwitchButton\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetCheckable\fP (bool)"
.br
.RI "设置是否可选中 "
.ti -1c
.RI "bool \fBisCheckable\fP () const"
.br
.RI "返回是否可选中 "
.ti -1c
.RI "bool \fBisChecked\fP () const"
.br
.RI "返回是否选中 "
.ti -1c
.RI "void \fBsetChecked\fP (bool)"
.br
.RI "设置是否选中 "
.ti -1c
.RI "void \fBsetTranslucent\fP (bool flag)"
.br
.RI "设置是否启用半透明效果 "
.ti -1c
.RI "bool \fBisTranslucent\fP ()"
.br
.RI "获取是否启用半透明效果 "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *event) override"
.br
.ti -1c
.RI "void \fBresizeEvent\fP (QResizeEvent *event) override"
.br
.ti -1c
.RI "QSize \fBsizeHint\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
指示打开/关闭两种状态 

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
