.TH "kdk::KWidgetUtils" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KWidgetUtils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBhighDpiScaling\fP ()"
.br
.RI "适配高分屏，需要在定义QApplication对象前，调用该函数 \fBKWidgetUtils::highDpiScaling()\fP; QApplication a(argc, argv); "
.ti -1c
.RI "static bool \fBcheckCompositorRunning\fP (void)"
.br
.RI "判断合成器是否开启 "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static bool kdk::KWidgetUtils::checkCompositorRunning (void)\fC [static]\fP"

.PP
判断合成器是否开启 
.PP
\fBParameters\fP
.RS 4
\fI无\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fItrue\fP 开启 
.br
\fIfalse\fP 没开启 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
