.TH "kdk::KProgressBar" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KProgressBar \- 进度条，支持三种状态显示  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kprogressbar\&.h>\fP
.PP
Inherits QProgressBar\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKProgressBar\fP (QWidget *parent)"
.br
.ti -1c
.RI "\fBProgressBarState\fP \fBstate\fP ()"
.br
.RI "获取状态 "
.ti -1c
.RI "void \fBsetState\fP (\fBProgressBarState\fP \fBstate\fP)"
.br
.RI "设置状态 "
.ti -1c
.RI "QString \fBtext\fP () const override"
.br
.RI "获取文本 "
.ti -1c
.RI "void \fBsetOrientation\fP (Qt::Orientation)"
.br
.RI "设置方向 "
.ti -1c
.RI "void \fBsetBodyWidth\fP (int width)"
.br
.RI "设置进度条宽度 "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *event) override"
.br
.ti -1c
.RI "QSize \fBsizeHint\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
进度条，支持三种状态显示 
.PP
\fBExamples\fP
.in +1c
\fBtestprogressbar/widget\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
