.TH "kdk::KWidget" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KWidget \- 继承自QWidget,支持响应主题背景切换，图标主题切换，标题颜色响应窗口激活状态，内容区域分为side区和base区  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kwidget\&.h>\fP
.PP
Inherits QWidget, and ThemeController\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKWidget\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBsetIcon\fP (const QIcon &icon)"
.br
.RI "设置窗体图标 "
.ti -1c
.RI "void \fBsetIcon\fP (const QString &iconName)"
.br
.RI "设置窗体图标 "
.ti -1c
.RI "void \fBsetWidgetName\fP (const QString &widgetName)"
.br
.RI "设置窗体名称 "
.ti -1c
.RI "QWidget * \fBsideBar\fP ()"
.br
.RI "获取左边栏widget,通过setlayout添加自定义内容 "
.ti -1c
.RI "QWidget * \fBbaseBar\fP ()"
.br
.RI "获取主内容区widget,通过setlayout添加自定义内容 "
.ti -1c
.RI "\fBKWindowButtonBar\fP * \fBwindowButtonBar\fP ()"
.br
.RI "获取窗口三联组合控件，以控制是否显示最大化、最小化按钮和下拉菜单按钮；也可增加自定义按钮 "
.ti -1c
.RI "\fBKIconBar\fP * \fBiconBar\fP ()"
.br
.RI "获取窗口标题、图标组合控件，以控制相关样式 "
.ti -1c
.RI "void \fBsetLayoutType\fP (LayoutType type)"
.br
.RI "设置布局结构类型 "
.ti -1c
.RI "void \fBsetWindowFlags\fP (Qt::WindowFlags type)"
.br
.RI "设置窗口标志 "
.ti -1c
.RI "void \fBsetWindowFlag\fP (Qt::WindowType flag, bool on=true)"
.br
.RI "设置窗口标志 "
.ti -1c
.RI "void \fBsetSidebarFollowMode\fP (bool flag)"
.br
.RI "设置sidebar是否遵循系统更改宽度 "
.ti -1c
.RI "bool \fBsidebarFollowMode\fP ()"
.br
.RI "返回sidebar是否遵循系统更改宽度 "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBeventFilter\fP (QObject *target, QEvent *event) override"
.br
.ti -1c
.RI "virtual void \fBchangeIconStyle\fP ()"
.br
.ti -1c
.RI "virtual void \fBchangeTheme\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
继承自QWidget,支持响应主题背景切换，图标主题切换，标题颜色响应窗口激活状态，内容区域分为side区和base区 
.PP
\fBExamples\fP
.in +1c
\fBtestbadge/widget\&.h\fP, \fBtestballontip/widget\&.h\fP, \fBtestDialog/widget\&.h\fP, \fBtestinputdialog/widget\&.cpp\fP, \fBtestinputdialog/widget\&.h\fP, \fBtestnavigationbar/widget\&.h\fP, \fBtestpasswordedit/widget\&.h\fP, \fBtestprogressbar/widget\&.h\fP, \fBtestprogressdialog/widget\&.cpp\fP, \fBtestprogressdialog/widget\&.h\fP, \fBtestPushbutton/widget\&.h\fP, \fBtestsearchlinedit/widget\&.h\fP, \fBtestsecuritylevelbar/widget\&.h\fP, \fBtestslider/widget\&.h\fP, \fBtesttabbar/widget\&.h\fP, \fBtesttoolbutton/widget\&.h\fP, and \fBtestWidget/testwidget\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
