.TH "kdk::effects::KShadowHelper" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::effects::KShadowHelper
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetWidget\fP (QWidget *widget, int borderRadius=12, int shadowWidth=20, qreal darkness=0\&.5)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBKShadowHelper\fP * \fBself\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
