.TH "kdk::KPasswordEdit" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KPasswordEdit \- 密码输入框，继承于QLineEdit,支持三种不同状态显示  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kpasswordedit\&.h>\fP
.PP
Inherits QLineEdit\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKPasswordEdit\fP (QWidget *parent)"
.br
.ti -1c
.RI "void \fBsetState\fP (\fBLoginState\fP \fBstate\fP)"
.br
.RI "设置状态 "
.ti -1c
.RI "\fBLoginState\fP \fBstate\fP ()"
.br
.RI "返回状态 "
.ti -1c
.RI "void \fBsetLoading\fP (bool flag)"
.br
.RI "设置加载状态 "
.ti -1c
.RI "bool \fBisLoading\fP ()"
.br
.RI "判断是否处于加载状态 "
.ti -1c
.RI "QString \fBplaceholderText\fP ()"
.br
.RI "返回placeholderText "
.ti -1c
.RI "void \fBsetPlaceholderText\fP (QString &text)"
.br
.RI "设置PlaceholderText "
.ti -1c
.RI "void \fBsetClearButtonEnabled\fP (bool enable)"
.br
.RI "设置是否启用ClearButton "
.ti -1c
.RI "bool \fBisClearButtonEnabled\fP () const"
.br
.RI "返回是否启用了ClearButton "
.ti -1c
.RI "void \fBsetEchoModeBtnVisible\fP (bool enable)"
.br
.RI "设置EchoModeBtn是否可见 "
.ti -1c
.RI "bool \fBechoModeBtnVisible\fP ()"
.br
.RI "返回EchoModeBtn是否可见 "
.ti -1c
.RI "void \fBsetClearBtnVisible\fP (bool enable)"
.br
.RI "设置ClearBtn是否可见 "
.ti -1c
.RI "bool \fBclearBtnVisible\fP ()"
.br
.RI "返回ClearBtn是否可见 "
.ti -1c
.RI "void \fBsetEnabled\fP (bool)"
.br
.RI "设置KLineEdit是否可用 "
.ti -1c
.RI "void \fBsetEchoMode\fP (EchoMode mode)"
.br
.RI "setEchoMode "
.ti -1c
.RI "void \fBsetUseCustomPalette\fP (bool flag)"
.br
.RI "设置是否走默认palette "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBresizeEvent\fP (QResizeEvent *event)"
.br
.ti -1c
.RI "bool \fBeventFilter\fP (QObject *watched, QEvent *event)"
.br
.ti -1c
.RI "QSize \fBsizeHint\fP () const override"
.br
.in -1c
.SH "Detailed Description"
.PP 
密码输入框，继承于QLineEdit,支持三种不同状态显示 
.PP
\fBExamples\fP
.in +1c
\fBtestpasswordedit/widget\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
