.TH "kdk::KListView" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KListView \- 配合KListviewdelegate可以提供一个图片两行文字的显示效果，若只有一行文字，则对于 icon 居中显示 。  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <klistview\&.h>\fP
.PP
Inherits QListView\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKListView\fP (QWidget *parent)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBmousePressEvent\fP (QMouseEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
配合KListviewdelegate可以提供一个图片两行文字的显示效果，若只有一行文字，则对于 icon 居中显示 。 

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
