.TH "kdk::KAboutDialog" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KAboutDialog \- 关于对话框，支持两种样式，一种是无特定说明的，另一种是有特定说明的。  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kaboutdialog\&.h>\fP
.PP
Inherits \fBkdk::KDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKAboutDialog\fP (QWidget *parent=nullptr, const QIcon &appIcon=QIcon(), const QString &\fBappName\fP='', const QString &\fBappVersion\fP='', const QString &appInfo='')"
.br
.ti -1c
.RI "void \fBsetAppIcon\fP (const QIcon &icon)"
.br
.RI "设置应用程序图标 "
.ti -1c
.RI "void \fBsetAppName\fP (const QString &\fBappName\fP)"
.br
.RI "设置应用程序名称 "
.ti -1c
.RI "QString \fBappName\fP ()"
.br
.RI "获取应用程序名称 "
.ti -1c
.RI "void \fBsetAppVersion\fP (const QString &\fBappVersion\fP)"
.br
.RI "设置应用程序版本号 "
.ti -1c
.RI "QString \fBappVersion\fP ()"
.br
.RI "获取应用程序版本号 "
.ti -1c
.RI "void \fBsetBodyText\fP (const QString &\fBbodyText\fP)"
.br
.RI "设置具体的说明内容 "
.ti -1c
.RI "QString \fBbodyText\fP ()"
.br
.RI "获取具体的说明内容 "
.ti -1c
.RI "void \fBsetAppSupport\fP (const QString &\fBappSupport\fP)"
.br
.RI "设置服务与支持邮箱，有默认缺省 "
.ti -1c
.RI "QString \fBappSupport\fP ()"
.br
.RI "获取服务与支持邮箱 "
.ti -1c
.RI "void \fBsetBodyTextVisiable\fP (bool flag)"
.br
.RI "设置是否显示说明内容,应设计要求，1\&.2\&.0\&.9中不再显示说明内容 "
.ti -1c
.RI "void \fBsetAppPrivacyLabelVisible\fP (bool flag)"
.br
.RI "设置隐私按钮是否可见 "
.ti -1c
.RI "bool \fBAppPrivacyLabelIsVisible\fP ()"
.br
.RI "返回隐私按钮是否可见 "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBchangeTheme\fP () override"
.br
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *paintEvent) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
关于对话框，支持两种样式，一种是无特定说明的，另一种是有特定说明的。 

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
