.TH "MessageAlertModule" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessageAlertModule
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkdk::KBadge\fP"
.br
.RI "消息提醒气泡 "
.ti -1c
.RI "class \fBkdk::KBallonTip\fP"
.br
.RI "消息提示框，支持五种样式 "
.ti -1c
.RI "class \fBkdk::KSecurityLevelBar\fP"
.br
.RI "密码安全等级提示条，支持三个安全等级 "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBkdk::TipType\fP { \fBNothing\fP, \fBNormal\fP, \fBInfo\fP, \fBWarning\fP, \fBError\fP }"
.br
.RI "支持五种样式 "
.ti -1c
.RI "enum \fBkdk::SecurityLevel\fP { \fBLow\fP, \fBMedium\fP, \fBHigh\fP }"
.br
.RI "分为三个安全等级 "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBkdk::KBadge::KBadge\fP (QWidget *parent)"
.br
.ti -1c
.RI "int \fBkdk::KBadge::value\fP ()"
.br
.RI "返回值 "
.ti -1c
.RI "void \fBkdk::KBadge::setValue\fP (int \fBvalue\fP)"
.br
.RI "设置值，最大显示数值为999，大于999显示'\&.\&.\&.' "
.ti -1c
.RI "void \fBkdk::KBadge::setValueVisiable\fP (bool flag)"
.br
.RI "设置值是否可见 "
.ti -1c
.RI "bool \fBkdk::KBadge::isValueVisiable\fP () const"
.br
.RI "获取值是否可见 "
.ti -1c
.RI "QColor \fBkdk::KBadge::color\fP ()"
.br
.RI "获取背景色 "
.ti -1c
.RI "void \fBkdk::KBadge::setColor\fP (const QColor &\fBcolor\fP)"
.br
.RI "设置背景色 "
.ti -1c
.RI "int \fBkdk::KBadge::fontSize\fP ()"
.br
.RI "获取字体大小 "
.ti -1c
.RI "void \fBkdk::KBadge::setFontSize\fP (int size)"
.br
.RI "设置字体大小 "
.ti -1c
.RI "void \fBkdk::KBadge::paintEvent\fP (QPaintEvent *event)"
.br
.ti -1c
.RI "void \fBkdk::KBadge::resizeEvent\fP (QResizeEvent *event)"
.br
.ti -1c
.RI "\fBkdk::KBallonTip::KBallonTip\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fBkdk::KBallonTip::KBallonTip\fP (const QString &content, const \fBTipType\fP &type, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBkdk::KBallonTip::showInfo\fP ()"
.br
.RI "显示时间完毕后消失 "
.ti -1c
.RI "void \fBkdk::KBallonTip::setTipType\fP (const \fBTipType\fP &type)"
.br
.RI "设置类型 "
.ti -1c
.RI "\fBTipType\fP \fBkdk::KBallonTip::tipType\fP ()"
.br
.RI "返回类型 "
.ti -1c
.RI "void \fBkdk::KBallonTip::setText\fP (const QString &\fBtext\fP)"
.br
.RI "设置文本内容 "
.ti -1c
.RI "QString \fBkdk::KBallonTip::text\fP ()"
.br
.RI "text "
.ti -1c
.RI "void \fBkdk::KBallonTip::setContentsMargins\fP (int left, int top, int right, int bottom)"
.br
.RI "设置内容边距 "
.ti -1c
.RI "void \fBkdk::KBallonTip::setContentsMargins\fP (const QMargins &margins)"
.br
.RI "设置内容边距 "
.ti -1c
.RI "void \fBkdk::KBallonTip::setTipTime\fP (int my_time)"
.br
.RI "设置持续时间 "
.ti -1c
.RI "void \fBkdk::KBallonTip::paintEvent\fP (QPaintEvent *event) override"
.br
.ti -1c
.RI "\fBkdk::KSecurityLevelBar::KSecurityLevelBar\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBkdk::KSecurityLevelBar::setSecurityLevel\fP (\fBSecurityLevel\fP level)"
.br
.RI "设置安全等级 "
.ti -1c
.RI "\fBSecurityLevel\fP \fBkdk::KSecurityLevelBar::securityLevel\fP ()"
.br
.RI "获取安全等级 "
.ti -1c
.RI "void \fBkdk::KSecurityLevelBar::paintEvent\fP (QPaintEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "QColor kdk::KBadge::color ()"

.PP
获取背景色 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "int kdk::KBadge::fontSize ()"

.PP
获取字体大小 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "\fBSecurityLevel\fP kdk::KSecurityLevelBar::securityLevel ()"

.PP
获取安全等级 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "void kdk::KBadge::setColor (const QColor & color)"

.PP
设置背景色 
.PP
\fBParameters\fP
.RS 4
\fIcolor\fP 
.RE
.PP

.SS "void kdk::KBallonTip::setContentsMargins (const QMargins & margins)"

.PP
设置内容边距 
.PP
\fBParameters\fP
.RS 4
\fImargins\fP 
.RE
.PP

.SS "void kdk::KBallonTip::setContentsMargins (int left, int top, int right, int bottom)"

.PP
设置内容边距 
.PP
\fBParameters\fP
.RS 4
\fIleft\fP 
.br
\fItop\fP 
.br
\fIright\fP 
.br
\fIbottom\fP 
.RE
.PP

.SS "void kdk::KBadge::setFontSize (int size)"

.PP
设置字体大小 
.PP
\fBParameters\fP
.RS 4
\fIsize\fP 
.RE
.PP

.SS "void kdk::KSecurityLevelBar::setSecurityLevel (\fBSecurityLevel\fP level)"

.PP
设置安全等级 
.PP
\fBParameters\fP
.RS 4
\fIlevel\fP 
.RE
.PP

.SS "void kdk::KBallonTip::setText (const QString & text)"

.PP
设置文本内容 
.PP
\fBParameters\fP
.RS 4
\fItext\fP 
.RE
.PP

.SS "void kdk::KBallonTip::setTipTime (int my_time)"

.PP
设置持续时间 
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP

.SS "void kdk::KBallonTip::setTipType (const \fBTipType\fP & type)"

.PP
设置类型 
.PP
\fBParameters\fP
.RS 4
\fItype\fP 
.RE
.PP

.SS "void kdk::KBadge::setValue (int value)"

.PP
设置值，最大显示数值为999，大于999显示'\&.\&.\&.' 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP 
.RE
.PP

.SS "void kdk::KBadge::setValueVisiable (bool flag)"

.PP
设置值是否可见 
.PP
\fBParameters\fP
.RS 4
\fIflag\fP 
.RE
.PP

.SS "void kdk::KBallonTip::showInfo ()"

.PP
显示时间完毕后消失 
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP

.SS "QString kdk::KBallonTip::text ()"

.PP
text 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "\fBTipType\fP kdk::KBallonTip::tipType ()"

.PP
返回类型 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "int kdk::KBadge::value ()"

.PP
返回值 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
