.TH "SliderModule" 3 "Thu Oct 12 2023" "Version version:2.3" "LIBLINGMOSDK-APPLICATIONS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SliderModule
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkdk::KSlider\fP"
.br
.RI "支持三种样式的滑动条 非步数关系：步数为1，可以在任意位置点击和拖拽 步数关系：步数为固定值，可根据步数值点击和拖拽 节点关系：步数为节点间隔，可根据节点间隔点击和拖拽 "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBKSliderType\fP { \fBSmoothSlider\fP, \fBStepSlider\fP, \fBNodeSlider\fP, \fBSingleSelectSlider\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBkdk::KSlider::KSlider\fP (QWidget *parent)"
.br
.ti -1c
.RI "\fBkdk::KSlider::KSlider\fP (Qt::Orientation orientation, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBkdk::KSlider::setTickInterval\fP (int interval)"
.br
.RI "设置节点间隔 "
.ti -1c
.RI "void \fBkdk::KSlider::setSliderType\fP (KSliderType type)"
.br
.RI "设置滑动条类型 "
.ti -1c
.RI "KSliderType \fBkdk::KSlider::sliderType\fP ()"
.br
.RI "获取滑动条类型 "
.ti -1c
.RI "int \fBkdk::KSlider::tickInterval\fP () const"
.br
.RI "获取节点间隔 "
.ti -1c
.RI "void \fBkdk::KSlider::setValue\fP (int)"
.br
.RI "设置值 "
.ti -1c
.RI "void \fBkdk::KSlider::setNodeVisible\fP (bool flag)"
.br
.RI "设置是否显示节点 "
.ti -1c
.RI "bool \fBkdk::KSlider::nodeVisible\fP ()"
.br
.RI "获取是否显示节点 "
.ti -1c
.RI "void \fBkdk::KSlider::setToolTip\fP (const QString &)"
.br
.RI "设置tooltip "
.ti -1c
.RI "QString \fBkdk::KSlider::toolTip\fP () const"
.br
.RI "获取toolTip "
.ti -1c
.RI "void \fBkdk::KSlider::setTranslucent\fP (bool flag)"
.br
.RI "设置是否启用半透明效果 "
.ti -1c
.RI "bool \fBkdk::KSlider::isTranslucent\fP ()"
.br
.RI "获取是否启用半透明效果 "
.ti -1c
.RI "void \fBkdk::KSlider::paintEvent\fP (QPaintEvent *event)"
.br
.ti -1c
.RI "void \fBkdk::KSlider::resizeEvent\fP (QResizeEvent *event)"
.br
.ti -1c
.RI "void \fBkdk::KSlider::mousePressEvent\fP (QMouseEvent *event)"
.br
.ti -1c
.RI "void \fBkdk::KSlider::mouseReleaseEvent\fP (QMouseEvent *event)"
.br
.ti -1c
.RI "void \fBkdk::KSlider::mouseMoveEvent\fP (QMouseEvent *event)"
.br
.ti -1c
.RI "void \fBkdk::KSlider::wheelEvent\fP (QWheelEvent *event)"
.br
.ti -1c
.RI "bool \fBkdk::KSlider::eventFilter\fP (QObject *watched, QEvent *event)"
.br
.ti -1c
.RI "QSize \fBkdk::KSlider::sizeHint\fP () const override"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "bool kdk::KSlider::isTranslucent ()"

.PP
获取是否启用半透明效果 
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP
\fBReturns\fP
.RS 4
flag 
.RE
.PP

.SS "bool kdk::KSlider::nodeVisible ()"

.PP
获取是否显示节点 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "void kdk::KSlider::setNodeVisible (bool flag)"

.PP
设置是否显示节点 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "void kdk::KSlider::setSliderType (KSliderType type)"

.PP
设置滑动条类型 
.PP
\fBParameters\fP
.RS 4
\fItype\fP 
.RE
.PP

.SS "void kdk::KSlider::setTickInterval (int interval)"

.PP
设置节点间隔 
.PP
\fBParameters\fP
.RS 4
\fIinterval\fP 
.RE
.PP

.SS "void kdk::KSlider::setToolTip (const QString &)"

.PP
设置tooltip 
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP

.SS "void kdk::KSlider::setTranslucent (bool flag)"

.PP
设置是否启用半透明效果 
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP
\fBParameters\fP
.RS 4
\fIflag\fP 
.RE
.PP

.SS "KSliderType kdk::KSlider::sliderType ()"

.PP
获取滑动条类型 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "int kdk::KSlider::tickInterval () const"

.PP
获取节点间隔 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "QString kdk::KSlider::toolTip () const"

.PP
获取toolTip 
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-APPLICATIONS from the source code\&.
