#!/bin/sh

set -ex

cd "${AUTOPKGTEST_TMP}"

if [ -n "${DEB_HOST_GNU_TYPE:-}" ]; then
    CROSS_COMPILE="$DEB_HOST_GNU_TYPE-"
else
    CROSS_COMPILE=
fi

cat > libaudit.c <<EOF
#include <libaudit.h>

int main (void)
{
    int fd;
    fd=audit_open();

    audit_close(fd);
    return 0;
}
EOF

"${CROSS_COMPILE}gcc" -o libaudit libaudit.c $("${CROSS_COMPILE}pkg-config" --cflags --libs audit)
echo "build: OK"
./libaudit
echo "run: OK"
