// SPDX-FileCopyrightText: 2024 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#define DEF_NAMESPACE_BEGIN

#define DEF_NAMESPACE_END

#define DEF_USING_NAMESPACE

#define DEF_ANTIVIRUS_NAMESPACE_BEGIN

#define DEF_ANTIVIRUS_NAMESPACE_END

#define DEF_USING_ANTIVIRUS_NAMESPACE

#define DEF_NETPROTECTION_NAMESPACE_BEGIN

#define DEF_NETPROTECTION_NAMESPACE_END

#define DEF_USING_NETPROTECTION_NAMESPACE
