# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/bluedevil/src/sendfile/pages/connecting.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Connecting(object):
    def setupUi(self, Connecting):
        Connecting.setObjectName("Connecting")
        Connecting.resize(400, 299)
        self.verticalLayout = QtWidgets.QVBoxLayout(Connecting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.connLabel = QtWidgets.QLabel(Connecting)
        self.connLabel.setTextFormat(QtCore.Qt.PlainText)
        self.connLabel.setObjectName("connLabel")
        self.verticalLayout.addWidget(self.connLabel)
        self.progressBar = QtWidgets.QProgressBar(Connecting)
        self.progressBar.setMaximum(0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)

        self.retranslateUi(Connecting)
        QtCore.QMetaObject.connectSlotsByName(Connecting)

    def retranslateUi(self, Connecting):
        pass
