# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/kwidgetsaddons/autotests/kcolumnresizertest-grid-and-form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KColumnResizerTestGridAndForms(object):
    def setupUi(self, KColumnResizerTestGridAndForms):
        KColumnResizerTestGridAndForms.setObjectName("KColumnResizerTestGridAndForms")
        KColumnResizerTestGridAndForms.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(KColumnResizerTestGridAndForms)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(KColumnResizerTestGridAndForms)
        self.groupBox.setObjectName("groupBox")
        self.layout1 = QtWidgets.QGridLayout(self.groupBox)
        self.layout1.setObjectName("layout1")
        self.widget1 = QtWidgets.QLineEdit(self.groupBox)
        self.widget1.setObjectName("widget1")
        self.layout1.addWidget(self.widget1, 0, 1, 1, 1)
        self.label1 = QtWidgets.QLabel(self.groupBox)
        self.label1.setObjectName("label1")
        self.layout1.addWidget(self.label1, 0, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.layout1.addWidget(self.checkBox, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.layout1.addWidget(self.pushButton, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(KColumnResizerTestGridAndForms)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layout2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.layout2.setObjectName("layout2")
        self.label2 = QtWidgets.QLabel(self.groupBox_2)
        self.label2.setObjectName("label2")
        self.layout2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label2)
        self.widget2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.widget2.setObjectName("widget2")
        self.layout2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.widget2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_2.raise_()
        self.groupBox.raise_()

        self.retranslateUi(KColumnResizerTestGridAndForms)
        QtCore.QMetaObject.connectSlotsByName(KColumnResizerTestGridAndForms)

    def retranslateUi(self, KColumnResizerTestGridAndForms):
        _translate = QtCore.QCoreApplication.translate
        KColumnResizerTestGridAndForms.setWindowTitle(_translate("KColumnResizerTestGridAndForms", "Form"))
        self.groupBox.setTitle(_translate("KColumnResizerTestGridAndForms", "GroupBox"))
        self.label1.setText(_translate("KColumnResizerTestGridAndForms", "Short:"))
        self.checkBox.setText(_translate("KColumnResizerTestGridAndForms", "CheckBox"))
        self.pushButton.setText(_translate("KColumnResizerTestGridAndForms", "PushButton"))
        self.groupBox_2.setTitle(_translate("KColumnResizerTestGridAndForms", "GroupBox"))
        self.label2.setText(_translate("KColumnResizerTestGridAndForms", "Some long label:"))
