src/utils/sdkmarcos.h usr/include/lingmosdk/lingmosdk-base
src/utils/kerr.h usr/include/lingmosdk/lingmosdk-base
src/utils/cstring-extension.h usr/include/lingmosdk/lingmosdk-base
src/utils/kyutils.h usr/include/lingmosdk/lingmosdk-base
src/utils/data-structure/linklist/skip_linklist/skip_linklist.h usr/include/lingmosdk/lingmosdk-base
src/utils/data-structure/linklist/listdata.h usr/include/lingmosdk/lingmosdk-base
development-files/lingmosdk-utils.pc usr/share/pkgconfig/
