[Grand Search]
Name=org.lingmo.ocean-grand-search.ocean-control-center-setting
Mode=Trigger
DBusService=org.lingmo.ocean.ControlCenter1
DBusAddress=/org/lingmo/ocean/ControlCenter1
DBusInterface=org.lingmo.ocean.ControlCenter1.GrandSearch
InterfaceVersion=1.0
