.TH lingmo\-music 1 "2021-03-03" "Lingmo"

.SH NAME
lingmo\-music \- Lingmo music playing application

.SH SYNOPSIS
.B lingmo\-music

.SH DESCRIPTION
.B Lingmo Music
is an application developed by Lingmo Technology Team which focused on local music playing. It brings all brand new UI design, extreme playing experience, and it has local music scanning and lyric sync functions, etc.

.SH OPTIONS
This program does not accept any command line options.

.SH SEE ALSO
https://www.lingmo.org/en/original/lingmo-music/

.SH AUTHOR
.B lingmo\-music
is written by Lingmo Technology Co., Ltd.

This manual page was written by
.MT zouya@uniontech.com
Yangfl
.ME
for the Debian Project (but may be used by others).
