# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/lingmo-nm/vpn/iodine/iodine.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IodineWidget(object):
    def setupUi(self, IodineWidget):
        IodineWidget.setObjectName("IodineWidget")
        IodineWidget.resize(387, 214)
        self.formLayout = QtWidgets.QFormLayout(IodineWidget)
        self.formLayout.setObjectName("formLayout")
        self.lbl_toplevelDomain = QtWidgets.QLabel(IodineWidget)
        self.lbl_toplevelDomain.setObjectName("lbl_toplevelDomain")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_toplevelDomain)
        self.le_toplevelDomain = QtWidgets.QLineEdit(IodineWidget)
        self.le_toplevelDomain.setObjectName("le_toplevelDomain")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_toplevelDomain)
        self.lbl_nameserver = QtWidgets.QLabel(IodineWidget)
        self.lbl_nameserver.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_nameserver.setObjectName("lbl_nameserver")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_nameserver)
        self.le_nameserver = QtWidgets.QLineEdit(IodineWidget)
        self.le_nameserver.setObjectName("le_nameserver")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_nameserver)
        self.lbl_password = QtWidgets.QLabel(IodineWidget)
        self.lbl_password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_password.setObjectName("lbl_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_password)
        self.le_password = PasswordField(IodineWidget)
        self.le_password.setText("")
        self.le_password.setObjectName("le_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_password)
        self.lbl_fragmentSize = QtWidgets.QLabel(IodineWidget)
        self.lbl_fragmentSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_fragmentSize.setObjectName("lbl_fragmentSize")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_fragmentSize)
        self.sb_fragmentSize = QtWidgets.QSpinBox(IodineWidget)
        self.sb_fragmentSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_fragmentSize.setMaximum(10000)
        self.sb_fragmentSize.setObjectName("sb_fragmentSize")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sb_fragmentSize)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem)

        self.retranslateUi(IodineWidget)
        QtCore.QMetaObject.connectSlotsByName(IodineWidget)

    def retranslateUi(self, IodineWidget):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_toplevelDomain.setText(_translate("IodineWidget", "Toplevel Domain:"))
        self.lbl_nameserver.setText(_translate("IodineWidget", "Nameserver:"))
        self.lbl_password.setText(_translate("IodineWidget", "Password:"))
        self.lbl_fragmentSize.setText(_translate("IodineWidget", "Fragment Size:"))
        self.sb_fragmentSize.setSpecialValueText(_translate("IodineWidget", "Automatic"))
        self.sb_fragmentSize.setSuffix(_translate("IodineWidget", " bytes"))
from passwordfield import PasswordField
