# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/lingmo-nm/vpn/fortisslvpn/fortisslvpnadvanced.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FortisslvpnAdvancedWidget(object):
    def setupUi(self, FortisslvpnAdvancedWidget):
        FortisslvpnAdvancedWidget.setObjectName("FortisslvpnAdvancedWidget")
        FortisslvpnAdvancedWidget.resize(400, 222)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FortisslvpnAdvancedWidget.sizePolicy().hasHeightForWidth())
        FortisslvpnAdvancedWidget.setSizePolicy(sizePolicy)
        FortisslvpnAdvancedWidget.setMinimumSize(QtCore.QSize(400, 222))
        self.gridLayout = QtWidgets.QGridLayout(FortisslvpnAdvancedWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(FortisslvpnAdvancedWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.otp = QtWidgets.QCheckBox(self.groupBox_2)
        self.otp.setObjectName("otp")
        self.gridLayout_2.addWidget(self.otp, 0, 0, 1, 1)
        self.tfa = QtWidgets.QCheckBox(self.groupBox_2)
        self.tfa.setObjectName("tfa")
        self.gridLayout_2.addWidget(self.tfa, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(FortisslvpnAdvancedWidget)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.realmLabel = QtWidgets.QLabel(self.groupBox_3)
        self.realmLabel.setObjectName("realmLabel")
        self.horizontalLayout.addWidget(self.realmLabel)
        self.realm = QtWidgets.QLineEdit(self.groupBox_3)
        self.realm.setObjectName("realm")
        self.horizontalLayout.addWidget(self.realm)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(FortisslvpnAdvancedWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.trustedCertLabel = QtWidgets.QLabel(self.groupBox)
        self.trustedCertLabel.setObjectName("trustedCertLabel")
        self.verticalLayout.addWidget(self.trustedCertLabel)
        self.trustedCert = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trustedCert.sizePolicy().hasHeightForWidth())
        self.trustedCert.setSizePolicy(sizePolicy)
        self.trustedCert.setObjectName("trustedCert")
        self.verticalLayout.addWidget(self.trustedCert)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)

        self.retranslateUi(FortisslvpnAdvancedWidget)
        QtCore.QMetaObject.connectSlotsByName(FortisslvpnAdvancedWidget)

    def retranslateUi(self, FortisslvpnAdvancedWidget):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox_2.setTitle(_translate("FortisslvpnAdvancedWidget", "Authentication"))
        self.otp.setText(_translate("FortisslvpnAdvancedWidget", "Use a One-Time Password"))
        self.tfa.setText(_translate("FortisslvpnAdvancedWidget", "2FA"))
        self.realmLabel.setText(_translate("FortisslvpnAdvancedWidget", "Realm:"))
        self.groupBox.setTitle(_translate("FortisslvpnAdvancedWidget", "Security"))
        self.trustedCertLabel.setText(_translate("FortisslvpnAdvancedWidget", "Trusted certificate:"))
        self.trustedCert.setPlaceholderText(_translate("FortisslvpnAdvancedWidget", "0123456789abcdef0123456789abcdef0123456789abcdef0123456789"))
