# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/lingmo-nm/vpn/fortisslvpn/fortisslvpn.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FortisslvpnWidget(object):
    def setupUi(self, FortisslvpnWidget):
        FortisslvpnWidget.setObjectName("FortisslvpnWidget")
        FortisslvpnWidget.resize(419, 390)
        self.formLayout = QtWidgets.QFormLayout(FortisslvpnWidget)
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(314, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.advancedButton = QtWidgets.QPushButton(FortisslvpnWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advancedButton.sizePolicy().hasHeightForWidth())
        self.advancedButton.setSizePolicy(sizePolicy)
        self.advancedButton.setObjectName("advancedButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.advancedButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.generalGroupBox = QtWidgets.QGroupBox(FortisslvpnWidget)
        self.generalGroupBox.setObjectName("generalGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.generalGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gatewayLabel = QtWidgets.QLabel(self.generalGroupBox)
        self.gatewayLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gatewayLabel.setObjectName("gatewayLabel")
        self.gridLayout.addWidget(self.gatewayLabel, 0, 0, 1, 1)
        self.gateway = QtWidgets.QLineEdit(self.generalGroupBox)
        self.gateway.setObjectName("gateway")
        self.gridLayout.addWidget(self.gateway, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.generalGroupBox)
        self.authenticationGroupBox = QtWidgets.QGroupBox(FortisslvpnWidget)
        self.authenticationGroupBox.setObjectName("authenticationGroupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.authenticationGroupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.usernameLabel = QtWidgets.QLabel(self.authenticationGroupBox)
        self.usernameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.username = QtWidgets.QLineEdit(self.authenticationGroupBox)
        self.username.setObjectName("username")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username)
        self.passwordLabel = QtWidgets.QLabel(self.authenticationGroupBox)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.password = PasswordField(self.authenticationGroupBox)
        self.password.setProperty("passwordModeEnabled", True)
        self.password.setObjectName("password")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password)
        self.caCertLabel = QtWidgets.QLabel(self.authenticationGroupBox)
        self.caCertLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.caCertLabel.setObjectName("caCertLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.caCertLabel)
        self.caCert = KUrlRequester(self.authenticationGroupBox)
        self.caCert.setObjectName("caCert")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.caCert)
        self.userCertLabel = QtWidgets.QLabel(self.authenticationGroupBox)
        self.userCertLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.userCertLabel.setObjectName("userCertLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.userCertLabel)
        self.userCert = KUrlRequester(self.authenticationGroupBox)
        self.userCert.setObjectName("userCert")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.userCert)
        self.userKeyLabel = QtWidgets.QLabel(self.authenticationGroupBox)
        self.userKeyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.userKeyLabel.setObjectName("userKeyLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.userKeyLabel)
        self.userKey = KUrlRequester(self.authenticationGroupBox)
        self.userKey.setObjectName("userKey")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.userKey)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.authenticationGroupBox)

        self.retranslateUi(FortisslvpnWidget)
        QtCore.QMetaObject.connectSlotsByName(FortisslvpnWidget)

    def retranslateUi(self, FortisslvpnWidget):
        _translate = QtCore.QCoreApplication.translate
        self.advancedButton.setText(_translate("FortisslvpnWidget", "Advanced"))
        self.generalGroupBox.setTitle(_translate("FortisslvpnWidget", "General"))
        self.gatewayLabel.setText(_translate("FortisslvpnWidget", "Gateway:"))
        self.gateway.setToolTip(_translate("FortisslvpnWidget", "SSLVPN server IP or name."))
        self.authenticationGroupBox.setTitle(_translate("FortisslvpnWidget", "Authentication"))
        self.usernameLabel.setText(_translate("FortisslvpnWidget", "User name:"))
        self.username.setToolTip(_translate("FortisslvpnWidget", "Set the name used for authenticating the local system to the peer to <name>."))
        self.passwordLabel.setText(_translate("FortisslvpnWidget", "Password:"))
        self.password.setToolTip(_translate("FortisslvpnWidget", "Password passed to SSLVPN when prompted for it."))
        self.caCertLabel.setText(_translate("FortisslvpnWidget", "CA Certificate:"))
        self.userCertLabel.setText(_translate("FortisslvpnWidget", "User Certificate:"))
        self.userKeyLabel.setText(_translate("FortisslvpnWidget", "User Key:"))
from kurlrequester import KUrlRequester
from passwordfield import PasswordField
