# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/lingmo-nm/vpn/strongswan/strongswanauth.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StrongswanAuth(object):
    def setupUi(self, StrongswanAuth):
        StrongswanAuth.setObjectName("StrongswanAuth")
        StrongswanAuth.resize(309, 89)
        self.gridLayout = QtWidgets.QGridLayout(StrongswanAuth)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.passwordLabel = QtWidgets.QLabel(StrongswanAuth)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 0, 0, 1, 1)
        self.password = PasswordField(StrongswanAuth)
        self.password.setProperty("passwordModeEnabled", True)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)

        self.retranslateUi(StrongswanAuth)
        QtCore.QMetaObject.connectSlotsByName(StrongswanAuth)

    def retranslateUi(self, StrongswanAuth):
        _translate = QtCore.QCoreApplication.translate
        StrongswanAuth.setWindowTitle(_translate("StrongswanAuth", "Strong Swan VPN"))
        self.passwordLabel.setText(_translate("StrongswanAuth", "Password: "))
from passwordfield import PasswordField
