#!/bin/bash

# SPDX-FileCopyrightText: 2022 - 2023 UnionTech Software Technology Co., Ltd.
#
# SPDX-License-Identifier: GPL-3.0-or-later

#shell name: ocean-property-dialog.sh
#description: reuqest show files's or folders's property dialog.
#usage: just use it in bash like ocean-property-dialog path1 path2 ...

#!/bin/bash
process=`ps ax -o 'cmd' |grep 'ocean-file-manager$'`;
processd=`ps ax -o 'cmd' |grep 'ocean-file-manager -d$'`;
data="ZGRlLWZpbGUtbWFuYWdlcg=="

if [[ "$process" == ""&&"$processd" == "" ]]; then
    ocean-file-manager -p "$@";
else
    option="-p"
    option_base64=`echo -n $option|base64 -w 0`
    data=$data" "$option_base64

    for path in "$@";
    do
        path_base64=`echo -n $path|base64 -w 0`
        data=$data" "$path_base64
    done

    target=$XDG_RUNTIME_DIR/ocean-file-manager
    if [ ! -S $target ];then
        target=/tmp/ocean-file-manager
            if [ ! -S $target ];then
                ocean-file-manager -p "$@"
                exit "$?"
            fi
    fi

    echo $data | socat - $target

    if [ $? != 0 ]; then
        ocean-file-manager -p "$@"
    fi
fi
