.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright (C) 2019 ~ 2020 UnionTech Software Technology Co.,Ltd
.\"
.TH "deepin-devicemanager" "1" "2021-3-11" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
deepin-devicemanager \- device manager for deepin.
.SH SYNOPSIS
deepin-devicemanager [FILE(s)...] [OPTIONS...]
.SH DESCRIPTION
Device Manager helps users view device information.
.PP
Device Manager is a handy tool for viewing hardware information and managing the devices.
 Device Manager helps users manage hardware devices installed on computers,
 through which users can view parameters and export data of all hardware devices running in the system.
.SH OPTIONS
.TP
\fBFILE\fR
Specifies the file to open when
.B deepin-devicemanager
starts. If this is not specified,
.B deepin-devicemanager
will load file choose page. Multiple files can be loaded if they are
separated by spaces.
.PP
-h  --help 
       Prints the command line options.
.PP
-v  --version
       Output version information and exit.
.PP

.SH SEE ALSO
https://github.com/linuxdeepin/deepin-devicemanager
.SH AUTHOR
.PP
.B deepin-devicemanager
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT liujuna@\:uniontech.com
LiuJun
.ME
for the Debian Project (but may be used by others)
