.TH KERNEL\-WEDGE\-COPY\-MODULES 1 "June 2019" "Kernel-wedge"
.SH NAME
kernel\-wedge\-copy\-modules \- install modules into package directories
.SH SYNOPSIS
.B kernel\-wedge copy\-modules
.I version flavour installedname
.SH DESCRIPTION
Copy modules into the right directories in preparation for building udebs.

Return 1 if a required module is missing, unless $KW_CHECK_NONFATAL is
non-empty.
.SH AUTHOR
Joey Hess
