.TH KERNEL\-WEDGE\-GEN\-DEPS 1 "June 2019" "Kernel-wedge"
.SH NAME
kernel\-wedge\-gen\-deps \- generate package dependency list
.SH SYNOPSIS
.B kernel\-wedge gen\-deps
.I flavour
.SH DESCRIPTION
Generates from the package\-list a dependency file for the given kernel
flavour, suitable to be fed to tsort. The file has the base package name on
the left, and the package it depends on is on the right. It is sorted.
.SH AUTHOR
Joey Hess
