.TH KERNEL\-WEDGE\-CHECK 1 "June 2019" "Kernel-wedge"
.SH NAME
kernel\-wedge\-check \- check files installed in package directories
.SH SYNOPSIS
.B kernel\-wedge check
.SH DESCRIPTION
Check for various problems in the packages.

Return 1 if any problems are found, unless $KW_CHECK_NONFATAL is
non-empty.
.SH AUTHOR
Joey Hess
