.TH KERNEL\-WEDGE\-BUILD\-ARCH 1 "June 2019" "Kernel-wedge"
.SH NAME
kernel\-wedge\-build\-arch \- build udebs for a single architecture
.SH SYNOPSIS
.B kernel\-wedge build\-arch
.I architecture
.SH DESCRIPTION
This is a wrapper script to build a specific architecture.

It takes the architecture to be built as parameter and that architecture
needs to be listed in kernel-versions.
It expects to have the unpacked kernel packages for the architecture in
e.g. ../alpha. modules.dep files have to be put in there too if they are
not shipped in the .deb (varies)

\fBdpkg-cross\fR must be installed, but you do not need a cross compiler.
.SH AUTHOR
Frans Pop
