.TH KERNEL\-WEDGE\-FIND\-DUPS 1 "June 2019" "Kernel-wedge"
.SH NAME
kernel\-wedge\-find\-dups \- find duplicate modules in package directories
.SH SYNOPSIS
.B kernel\-wedge find\-dups
.I kernel-name
.SH DESCRIPTION
Find duplicate modules. Pass the kernel name.

Return 1 if any duplicates are found, unless $KW_CHECK_NONFATAL is
non-empty or the configuration file 'ignore\-dups' exists.
.SH AUTHOR
Joey Hess
