.TH KERNEL\-WEDGE\-FIND\-UNPACKAGED 1 "June 2019" "Kernel-wedge"
.SH NAME
kernel\-wedge\-find\-unpackaged - list modules not packaged in a udeb
.SH SYNOPSIS
.B kernel\-wedge find\-unpackaged
.I kernel\-name
.SH DESCRIPTION
List modules that are not packaged in a udeb. Pass the kernel name.

Always return 0.
.SH AUTHOR
Ben Hutchings <ben@decadent.org.uk>
