.TH KERNEL\-WEDGE 1 "June 2019" "Kernel-wedge"
.SH NAME
kernel\-wedge \- industrial strength kernel splitter
.SH SYNOPSIS
.B kernel\-wedge
.IR "subcommand " [ options ]
.SH "DESCRIPTION"
.B kernel\-wedge
is used to generate kernel module udebs for the debian installer.
Type \fBkernel\-wedge\fR without any parameters for a list of subcommands,
and use \fBkernel\-wedge help\fR \fIsubcommand\fR for details on the usage of a
particular subcommand.
See /usr/share/doc/kernel-wedge/README.md.gz for detailed documentation.
.SH AUTHOR
Joey Hess
