# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/LingmoOS/shell/bc/Notepad/addons/externaltools/toolview.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ToolView(object):
    def setupUi(self, ToolView):
        ToolView.setObjectName("ToolView")
        ToolView.resize(678, 295)
        self.tabWidget = QtWidgets.QTabWidget(ToolView)
        self.tabWidget.setGeometry(QtCore.QRect(6, 6, 451, 240))
        self.tabWidget.setObjectName("tabWidget")
        self.tabOutput = QtWidgets.QWidget()
        self.tabOutput.setObjectName("tabOutput")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabOutput)
        self.verticalLayout.setObjectName("verticalLayout")
        self.teOutput = QtWidgets.QTextEdit(self.tabOutput)
        self.teOutput.setReadOnly(True)
        self.teOutput.setObjectName("teOutput")
        self.verticalLayout.addWidget(self.teOutput)
        self.tabWidget.addTab(self.tabOutput, "")

        self.retranslateUi(ToolView)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ToolView)

    def retranslateUi(self, ToolView):
        _translate = QtCore.QCoreApplication.translate
        self.teOutput.setPlaceholderText(_translate("ToolView", "Displays output from the external tool"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOutput), _translate("ToolView", "Output"))
