# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/kwin/src/plugins/tileseditor/kcm/tileseditoreffectkcm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TilesEditorEffectConfig(object):
    def setupUi(self, TilesEditorEffectConfig):
        TilesEditorEffectConfig.setObjectName("TilesEditorEffectConfig")
        TilesEditorEffectConfig.resize(455, 177)
        self.formLayout = QtWidgets.QFormLayout(TilesEditorEffectConfig)
        self.formLayout.setObjectName("formLayout")
        self.shortcutsEditor = KShortcutsEditor(TilesEditorEffectConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortcutsEditor.sizePolicy().hasHeightForWidth())
        self.shortcutsEditor.setSizePolicy(sizePolicy)
        self.shortcutsEditor.setObjectName("shortcutsEditor")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.shortcutsEditor)

        self.retranslateUi(TilesEditorEffectConfig)
        QtCore.QMetaObject.connectSlotsByName(TilesEditorEffectConfig)

    def retranslateUi(self, TilesEditorEffectConfig):
        pass
from kshortcutseditor import KShortcutsEditor
