.TH "lingmo.lingmosdk.java.method.GpsMethod" 3 "Wed Sep 20 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lingmo.lingmosdk.java.method.GpsMethod \- 获取地址信息类 主要用来获取本地地址信息  

.SH SYNOPSIS
.br
.PP
.PP
Inherits gps\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetGPSInfo\fP ()"
.br
.RI "获取本地地址信息 "
.ti -1c
.RI "boolean \fBisRemote\fP ()"
.br
.RI "判断是否为远程对象 "
.ti -1c
.RI "String \fBgetObjectPath\fP ()"
.br
.RI "获取ObjectPath【未实现】 "
.in -1c
.SH "Detailed Description"
.PP 
获取地址信息类 主要用来获取本地地址信息 
.PP 

.SH "Function Documentation"
.PP
.SS "String lingmo\&.lingmosdk\&.java\&.method\&.GpsMethod\&.getGPSInfo ()\fC [inline]\fP"

.PP
获取本地地址信息 
.PP
\fBReturns\fP
.RS 4
String json格式的地址信息 
.RE
.PP

.SS "String lingmo\&.lingmosdk\&.java\&.method\&.GpsMethod\&.getObjectPath ()\fC [inline]\fP"

.PP
获取ObjectPath【未实现】 
.PP
\fBReturns\fP
.RS 4
String ObjectPath 
.RE
.PP

.SS "boolean lingmo\&.lingmosdk\&.java\&.method\&.GpsMethod\&.isRemote ()\fC [inline]\fP"

.PP
判断是否为远程对象 
.PP
\fBReturns\fP
.RS 4
boolean Returns true on remote objects\&. Local objects implementing this interface MUST return false\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for GpsMethod.java from the source code\&.
