.TH "lingmo.lingmosdk.java.method.PrintMethod" 3 "Wed Sep 20 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lingmo.lingmosdk.java.method.PrintMethod \- 获取打印信息类 主要用来获取本地的所有打印机(包含可用打印机和不可用打印机)、获取本地的所有可用打印机(打印机处于idle状态)、 设置打印参数，每次设置会清除之前设置打印参数,这个设置是全局设置，设置了之后所有打印机都会用这个参数进行打印、 下载网络文件、打印本地文件、清除某个打印机的所有打印队列、获取当前打印机状态(状态不是实时更新)、 获取当前打印任务状态（发送打印任务之后下需要等待一会再获取状态,状态不是实时更新）、获取url内的文件名  

.SH SYNOPSIS
.br
.PP
.PP
Inherits print\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "List< String > \fBgetPrinterList\fP ()"
.br
.RI "获取本地的所有打印机(包含可用打印机和不可用打印机) "
.ti -1c
.RI "List< String > \fBgetPrinterAvailableList\fP ()"
.br
.RI "获取本地的所有可用打印机(打印机处于idle状态) "
.ti -1c
.RI "void \fBsetPrinterOptions\fP (int page, String paperType, String cups, String sided)"
.br
.RI "设置打印参数，每次设置会清除之前设置打印参数,这个设置是全局设置，设置了之后所有打印机都会用这个参数进行打印 "
.ti -1c
.RI "int \fBgetPrinterPrintLocalFile\fP (String printer, String file)"
.br
.RI "打印本地文件 "
.ti -1c
.RI "int \fBgetPrinterCancelAllJobs\fP (String printer)"
.br
.RI "清除某个打印机的所有打印队列 "
.ti -1c
.RI "int \fBgetPrinterStatus\fP (String printer)"
.br
.RI "获取当前打印机状态(状态不是实时更新) "
.ti -1c
.RI "String \fBgetPrinterFilename\fP (String url)"
.br
.RI "获取url内的文件名 "
.ti -1c
.RI "int \fBgetPrinterJobStatus\fP (String job, int id)"
.br
.RI "获取当前打印任务状态（发送打印任务之后下需要等待一会再获取状态,状态不是实时更新） "
.ti -1c
.RI "int \fBgetPrinterDownloadRemoteFile\fP (String remoteFile, String localFile)"
.br
.RI "下载网络文件 "
.ti -1c
.RI "boolean \fBisRemote\fP ()"
.br
.RI "判断是否为远程对象 "
.ti -1c
.RI "String \fBgetObjectPath\fP ()"
.br
.RI "获取ObjectPath【未实现】 "
.in -1c
.SH "Detailed Description"
.PP 
获取打印信息类 主要用来获取本地的所有打印机(包含可用打印机和不可用打印机)、获取本地的所有可用打印机(打印机处于idle状态)、 设置打印参数，每次设置会清除之前设置打印参数,这个设置是全局设置，设置了之后所有打印机都会用这个参数进行打印、 下载网络文件、打印本地文件、清除某个打印机的所有打印队列、获取当前打印机状态(状态不是实时更新)、 获取当前打印任务状态（发送打印任务之后下需要等待一会再获取状态,状态不是实时更新）、获取url内的文件名 
.PP 

.SH "Function Documentation"
.PP
.SS "List<String> lingmo\&.lingmosdk\&.java\&.method\&.PrintMethod\&.getPrinterAvailableList ()\fC [inline]\fP"

.PP
获取本地的所有可用打印机(打印机处于idle状态) 
.PP
\fBReturns\fP
.RS 4
List<String> 本地的所有可用打印机名称列表 
.RE
.PP

.SS "int lingmo\&.lingmosdk\&.java\&.method\&.PrintMethod\&.getPrinterCancelAllJobs (String printer)\fC [inline]\fP"

.PP
清除某个打印机的所有打印队列 
.PP
\fBParameters\fP
.RS 4
\fIprinter\fP 打印机名 
.RE
.PP
\fBReturns\fP
.RS 4
int 成功返回0,失败返回-1 
.RE
.PP

.SS "int lingmo\&.lingmosdk\&.java\&.method\&.PrintMethod\&.getPrinterDownloadRemoteFile (String remoteFile, String localFile)\fC [inline]\fP"

.PP
下载网络文件 
.PP
\fBParameters\fP
.RS 4
\fIremoteFile\fP 要打印的url 
.br
\fIlocalFile\fP 保存的文件路径
.RE
.PP
\fBReturns\fP
.RS 4
int 打印作业的id 
.RE
.PP

.SS "String lingmo\&.lingmosdk\&.java\&.method\&.PrintMethod\&.getPrinterFilename (String url)\fC [inline]\fP"

.PP
获取url内的文件名 
.PP
\fBParameters\fP
.RS 4
\fIurl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
String 解析出来的函数名 
.RE
.PP

.SS "int lingmo\&.lingmosdk\&.java\&.method\&.PrintMethod\&.getPrinterJobStatus (String job, int id)\fC [inline]\fP"

.PP
获取当前打印任务状态（发送打印任务之后下需要等待一会再获取状态,状态不是实时更新） 
.PP
\fBParameters\fP
.RS 4
\fIjob\fP 打印机名 
.br
\fIid\fP 打印作业的id 
.RE
.PP
\fBReturns\fP
.RS 4
int 状态码 
.RE
.PP

.SS "List<String> lingmo\&.lingmosdk\&.java\&.method\&.PrintMethod\&.getPrinterList ()\fC [inline]\fP"

.PP
获取本地的所有打印机(包含可用打印机和不可用打印机) 
.PP
\fBReturns\fP
.RS 4
List<String> 地的所有打印机名称列表 
.RE
.PP

.SS "int lingmo\&.lingmosdk\&.java\&.method\&.PrintMethod\&.getPrinterPrintLocalFile (String printer, String file)\fC [inline]\fP"

.PP
打印本地文件 
.PP
\fBParameters\fP
.RS 4
\fIprinter\fP 打印机名 
.br
\fIfile\fP 文件绝对路径
.RE
.PP
\fBReturns\fP
.RS 4
int 打印作业的id
.RE
.PP
@notice 虽然支持多种格式的打印，但是打印除pdf之外的格式打印的效果都不够好，建议打印pdf格式的文件 打印机处于stop状态函数返回0 格式不对的文件可以成功创建打印任务，但是打印不出来。什么叫格式不对，举个例子，比如当前要打印日志文件a\&.log, 然后把a\&.log改名叫a\&.pdf,这个时候a\&.pdf就变成了格式不对的文件，打印不出来了 
.SS "int lingmo\&.lingmosdk\&.java\&.method\&.PrintMethod\&.getPrinterStatus (String printer)\fC [inline]\fP"

.PP
获取当前打印机状态(状态不是实时更新) 
.PP
\fBParameters\fP
.RS 4
\fIprinter\fP 打印机名 
.RE
.PP
\fBReturns\fP
.RS 4
int 状态码 
.RE
.PP

.SS "void lingmo\&.lingmosdk\&.java\&.method\&.PrintMethod\&.setPrinterOptions (int page, String paperType, String cups, String sided)\fC [inline]\fP"

.PP
设置打印参数，每次设置会清除之前设置打印参数,这个设置是全局设置，设置了之后所有打印机都会用这个参数进行打印 
.PP
\fBParameters\fP
.RS 4
\fIpage\fP cups属性，一张纸打印几页，如2 4等 
.br
\fIpaperType\fP cups属性，纸张类型，如A4 
.br
\fIcups\fP cups属性，如lrtb 
.br
\fIsided\fP ups属性，单面如one-sided，双面如two-sided-long-edge(长边翻转),two-sided-short-edge(短边翻转) 
.RE
.PP

.SS "String lingmo\&.lingmosdk\&.java\&.method\&.PrintMethod\&.getObjectPath ()\fC [inline]\fP"

.PP
获取ObjectPath【未实现】 
.PP
\fBReturns\fP
.RS 4
String ObjectPath 
.RE
.PP

.SS "boolean lingmo\&.lingmosdk\&.java\&.method\&.PrintMethod\&.isRemote ()\fC [inline]\fP"

.PP
判断是否为远程对象 
.PP
\fBReturns\fP
.RS 4
boolean Returns true on remote objects\&. Local objects implementing this interface MUST return false\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PrintMethod.java from the source code\&.
