.TH "lingmo.lingmosdk.java.method.NetMethod" 3 "Wed Sep 20 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lingmo.lingmosdk.java.method.NetMethod \- 获取网络信息类 主要用来获取指定网络端口的状态、区间端口状态、网关信息、获取防火墙信息  

.SH SYNOPSIS
.br
.PP
.PP
Inherits net\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetPortState\fP (int port)"
.br
.RI "获取指定网络端口的状态 "
.ti -1c
.RI "List< String > \fBgetMultiplePortStat\fP (int begin, int end)"
.br
.RI "获取区间端口状态 "
.ti -1c
.RI "List< String > \fBgetGatewayInfo\fP ()"
.br
.RI "获取网关信息 "
.ti -1c
.RI "List< String > \fBgetFirewallState\fP ()"
.br
.RI "获取防火墙信息 "
.ti -1c
.RI "boolean \fBisRemote\fP ()"
.br
.RI "判断是否为远程对象 "
.ti -1c
.RI "String \fBgetObjectPath\fP ()"
.br
.RI "获取ObjectPath【未实现】 "
.in -1c
.SH "Detailed Description"
.PP 
获取网络信息类 主要用来获取指定网络端口的状态、区间端口状态、网关信息、获取防火墙信息 
.PP 

.SH "Function Documentation"
.PP
.SS "List<String> lingmo\&.lingmosdk\&.java\&.method\&.NetMethod\&.getFirewallState ()\fC [inline]\fP"

.PP
获取防火墙信息 
.PP
\fBReturns\fP
.RS 4
List<String> 防火墙信息列表 
.RE
.PP

.SS "List<String> lingmo\&.lingmosdk\&.java\&.method\&.NetMethod\&.getGatewayInfo ()\fC [inline]\fP"

.PP
获取网关信息 
.PP
\fBReturns\fP
.RS 4
List<String> 网关信息网卡名和地址列表 
.RE
.PP

.SS "List<String> lingmo\&.lingmosdk\&.java\&.method\&.NetMethod\&.getMultiplePortStat (int begin, int end)\fC [inline]\fP"

.PP
获取区间端口状态 
.PP
\fBParameters\fP
.RS 4
\fIbegin\fP 开始端口 
.br
\fIend\fP 结束端口 
.RE
.PP
\fBReturns\fP
.RS 4
List<String> 区间端口状态列表 
.RE
.PP

.SS "int lingmo\&.lingmosdk\&.java\&.method\&.NetMethod\&.getPortState (int port)\fC [inline]\fP"

.PP
获取指定网络端口的状态 
.PP
\fBParameters\fP
.RS 4
\fIport\fP 端口号 
.RE
.PP
\fBReturns\fP
.RS 4
int 端口状态 TCP_ESTABLISHED:0x1 TCP_SYN_SENT:0x2 TCP_SYN_RECV:0x3 TCP_FIN_WAIT1:0x4 TCP_FIN_WAIT2:0x5 TCP_TIME_WAIT:0x6 TCP_CLOSE:0x7 TCP_CLOSE_WAIT:0x8 TCP_LAST_ACL:0x9 TCP_LISTEN:0xa TCP_CLOSING:0xb 
.RE
.PP

.SS "String lingmo\&.lingmosdk\&.java\&.method\&.NetMethod\&.getObjectPath ()\fC [inline]\fP"

.PP
获取ObjectPath【未实现】 
.PP
\fBReturns\fP
.RS 4
String ObjectPath 
.RE
.PP

.SS "boolean lingmo\&.lingmosdk\&.java\&.method\&.NetMethod\&.isRemote ()\fC [inline]\fP"

.PP
判断是否为远程对象 
.PP
\fBReturns\fP
.RS 4
boolean Returns true on remote objects\&. Local objects implementing this interface MUST return false\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for NetMethod.java from the source code\&.
