.TH "lingmo.lingmosdk.java.method.ResourceMethod" 3 "Wed Sep 20 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lingmo.lingmosdk.java.method.ResourceMethod \- 获取当前系统资源占用信息类 主要用来获取系统中物理内存总大小、物理内存使用率、物理内存使用大小、实际可用的物理内存大小、实际空闲的物理内存大小、 所有应用申请的虚拟内存总量、系统中Swap分区总大小、Swap分区使用率、Swap分区使用量、Swap分区空闲大小、CPU瞬时使用率、 操作系统开机时长  

.SH SYNOPSIS
.br
.PP
.PP
Inherits resource\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBgetMemTotalKiB\fP ()"
.br
.RI "获取系统中物理内存总大小 "
.ti -1c
.RI "double \fBgetMemUsagePercent\fP ()"
.br
.RI "获取物理内存使用率 "
.ti -1c
.RI "double \fBgetMemUsageKiB\fP ()"
.br
.RI "获取物理内存使用大小，注意Buffer/Cache被计算为已使用内存 "
.ti -1c
.RI "double \fBgetMemAvailableKiB\fP ()"
.br
.RI "获取实际可用的物理内存大小，该数值约等于Free + Buffer + Cache "
.ti -1c
.RI "double \fBgetMemFreeKiB\fP ()"
.br
.RI "获取实际空闲的物理内存大小，注意Buffer/Cache被计算为已使用内存 "
.ti -1c
.RI "double \fBgetMemVirtAllocKiB\fP ()"
.br
.RI "获取所有应用申请的虚拟内存总量 "
.ti -1c
.RI "double \fBgetMemSwapTotalKiB\fP ()"
.br
.RI "获取系统中Swap分区总大小 "
.ti -1c
.RI "double \fBgetMemSwapUsagePercent\fP ()"
.br
.RI "获取Swap分区使用率 "
.ti -1c
.RI "double \fBgetMemSwapUsageKiB\fP ()"
.br
.RI "获取Swap分区使用量 "
.ti -1c
.RI "double \fBgetMemSwapFreeKiB\fP ()"
.br
.RI "获取Swap分区空闲大小 "
.ti -1c
.RI "double \fBgetCpuCurrentUsage\fP ()"
.br
.RI "获取CPU瞬时使用率 "
.ti -1c
.RI "String \fBgetUpTime\fP ()"
.br
.RI "获取操作系统开机时长 "
.ti -1c
.RI "boolean \fBisRemote\fP ()"
.br
.RI "判断是否为远程对象 "
.ti -1c
.RI "String \fBgetObjectPath\fP ()"
.br
.RI "获取ObjectPath【未实现】 "
.in -1c
.SH "Detailed Description"
.PP 
获取当前系统资源占用信息类 主要用来获取系统中物理内存总大小、物理内存使用率、物理内存使用大小、实际可用的物理内存大小、实际空闲的物理内存大小、 所有应用申请的虚拟内存总量、系统中Swap分区总大小、Swap分区使用率、Swap分区使用量、Swap分区空闲大小、CPU瞬时使用率、 操作系统开机时长 
.PP 

.SH "Function Documentation"
.PP
.SS "double lingmo\&.lingmosdk\&.java\&.method\&.ResourceMethod\&.getCpuCurrentUsage ()\fC [inline]\fP"

.PP
获取CPU瞬时使用率 
.PP
\fBReturns\fP
.RS 4
double CPU瞬时使用率，该值 < 1\&.00 
.RE
.PP

.SS "double lingmo\&.lingmosdk\&.java\&.method\&.ResourceMethod\&.getMemAvailableKiB ()\fC [inline]\fP"

.PP
获取实际可用的物理内存大小，该数值约等于Free + Buffer + Cache 
.PP
\fBReturns\fP
.RS 4
double 可用物理内存大小，KiB为单位 
.RE
.PP

.SS "double lingmo\&.lingmosdk\&.java\&.method\&.ResourceMethod\&.getMemFreeKiB ()\fC [inline]\fP"

.PP
获取实际空闲的物理内存大小，注意Buffer/Cache被计算为已使用内存 
.PP
\fBReturns\fP
.RS 4
double 空闲的物理内存大小，KiB为单位 
.RE
.PP

.SS "double lingmo\&.lingmosdk\&.java\&.method\&.ResourceMethod\&.getMemSwapFreeKiB ()\fC [inline]\fP"

.PP
获取Swap分区空闲大小 
.PP
\fBReturns\fP
.RS 4
double Swap分区空闲大小，KiB为单位 
.RE
.PP

.SS "double lingmo\&.lingmosdk\&.java\&.method\&.ResourceMethod\&.getMemSwapTotalKiB ()\fC [inline]\fP"

.PP
获取系统中Swap分区总大小 
.PP
\fBReturns\fP
.RS 4
double Swap分区大小，KiB为单位 
.RE
.PP

.SS "double lingmo\&.lingmosdk\&.java\&.method\&.ResourceMethod\&.getMemSwapUsageKiB ()\fC [inline]\fP"

.PP
获取Swap分区使用量 
.PP
\fBReturns\fP
.RS 4
double Swap分区使用量，KiB为单位 
.RE
.PP

.SS "double lingmo\&.lingmosdk\&.java\&.method\&.ResourceMethod\&.getMemSwapUsagePercent ()\fC [inline]\fP"

.PP
获取Swap分区使用率 
.PP
\fBReturns\fP
.RS 4
double Swap分区使用率 
.RE
.PP

.SS "double lingmo\&.lingmosdk\&.java\&.method\&.ResourceMethod\&.getMemTotalKiB ()\fC [inline]\fP"

.PP
获取系统中物理内存总大小 
.PP
\fBReturns\fP
.RS 4
double 物理内存大小，KiB为单位 
.RE
.PP

.SS "double lingmo\&.lingmosdk\&.java\&.method\&.ResourceMethod\&.getMemUsageKiB ()\fC [inline]\fP"

.PP
获取物理内存使用大小，注意Buffer/Cache被计算为已使用内存 
.PP
\fBReturns\fP
.RS 4
double 物理内存使用大小，KiB为单位 
.RE
.PP

.SS "double lingmo\&.lingmosdk\&.java\&.method\&.ResourceMethod\&.getMemUsagePercent ()\fC [inline]\fP"

.PP
获取物理内存使用率 
.PP
\fBReturns\fP
.RS 4
double 物理内存使用率 
.RE
.PP

.SS "double lingmo\&.lingmosdk\&.java\&.method\&.ResourceMethod\&.getMemVirtAllocKiB ()\fC [inline]\fP"

.PP
获取所有应用申请的虚拟内存总量 
.PP
\fBReturns\fP
.RS 4
double 虚拟内存总申请量，KiB为单位 
.RE
.PP

.SS "String lingmo\&.lingmosdk\&.java\&.method\&.ResourceMethod\&.getUpTime ()\fC [inline]\fP"

.PP
获取操作系统开机时长 
.PP
\fBReturns\fP
.RS 4
String 开机时长 
.RE
.PP

.SS "String lingmo\&.lingmosdk\&.java\&.method\&.ResourceMethod\&.getObjectPath ()\fC [inline]\fP"

.PP
获取ObjectPath【未实现】 
.PP
\fBReturns\fP
.RS 4
String ObjectPath 
.RE
.PP

.SS "boolean lingmo\&.lingmosdk\&.java\&.method\&.ResourceMethod\&.isRemote ()\fC [inline]\fP"

.PP
判断是否为远程对象 
.PP
\fBReturns\fP
.RS 4
boolean Returns true on remote objects\&. Local objects implementing this interface MUST return false\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for ResourceMethod.java from the source code\&.
