.TH "lingmo.lingmosdk.java.method.BiosMethod" 3 "Wed Sep 20 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lingmo.lingmosdk.java.method.BiosMethod \- 获取bios信息类 主要用来获取bios的厂商和版本信息  

.SH SYNOPSIS
.br
.PP
.PP
Inherits bios\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetBiosVendor\fP ()"
.br
.RI "获取bios厂商 "
.ti -1c
.RI "String \fBgetBiosVersion\fP ()"
.br
.RI "获取bios版本 "
.ti -1c
.RI "boolean \fBisRemote\fP ()"
.br
.RI "判断是否为远程对象 "
.ti -1c
.RI "String \fBgetObjectPath\fP ()"
.br
.RI "获取ObjectPath【未实现】 "
.in -1c
.SH "Detailed Description"
.PP 
获取bios信息类 主要用来获取bios的厂商和版本信息 
.PP

.SH "Function Documentation"
.PP
.SS "String lingmo\&.lingmosdk\&.java\&.method\&.BiosMethod\&.getBiosVendor ()\fC [inline]\fP"

.PP
获取bios厂商 
.PP
\fBReturns\fP
.RS 4
String 厂商名 
.RE
.PP

.SS "String lingmo\&.lingmosdk\&.java\&.method\&.BiosMethod\&.getBiosVersion ()\fC [inline]\fP"

.PP
获取bios版本 
.PP
\fBReturns\fP
.RS 4
String 版本号 
.RE
.PP

.SS "String lingmo\&.lingmosdk\&.java\&.method\&.BiosMethod\&.getObjectPath ()\fC [inline]\fP"

.PP
获取ObjectPath【未实现】 
.PP
\fBReturns\fP
.RS 4
String ObjectPath 
.RE
.PP

.SS "boolean lingmo\&.lingmosdk\&.java\&.method\&.BiosMethod\&.isRemote ()\fC [inline]\fP"

.PP
判断是否为远程对象 
.PP
\fBReturns\fP
.RS 4
boolean Returns true on remote objects\&. Local objects implementing this interface MUST return false\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BiosMethod.java from the source code\&.
