.TH "lingmo.lingmosdk.java.method.RunInfoMethod" 3 "Wed Sep 20 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lingmo.lingmosdk.java.method.RunInfoMethod \- 获取瞬时信息类 主要用来获取瞬时网速，cpu温度、磁盘温度、磁盘转速  

.SH SYNOPSIS
.br
.PP
.PP
Inherits runinfo\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBgetNetSpeed\fP (String nc)"
.br
.RI "获取瞬时网速信息 "
.ti -1c
.RI "int \fBgetDiskRate\fP (String disk)"
.br
.RI "获取磁盘转速 "
.ti -1c
.RI "double \fBgetCpuTemperature\fP ()"
.br
.RI "获取CPU温度 "
.ti -1c
.RI "double \fBgetDiskTemperature\fP (String name)"
.br
.RI "获取磁盘温度 "
.ti -1c
.RI "boolean \fBisRemote\fP ()"
.br
.RI "判断是否为远程对象 "
.ti -1c
.RI "String \fBgetObjectPath\fP ()"
.br
.RI "获取ObjectPath【未实现】 "
.in -1c
.SH "Detailed Description"
.PP 
获取瞬时信息类 主要用来获取瞬时网速，cpu温度、磁盘温度、磁盘转速 
.PP 

.SH "Function Documentation"
.PP
.SS "double lingmo\&.lingmosdk\&.java\&.method\&.RunInfoMethod\&.getCpuTemperature ()\fC [inline]\fP"

.PP
获取CPU温度 
.PP
\fBReturns\fP
.RS 4
double CPU温度 
.RE
.PP

.SS "int lingmo\&.lingmosdk\&.java\&.method\&.RunInfoMethod\&.getDiskRate (String disk)\fC [inline]\fP"

.PP
获取磁盘转速 
.PP
\fBParameters\fP
.RS 4
\fIdisk\fP 磁盘名称，应当是例如/dev/sda这种绝对路径 
.RE
.PP
\fBReturns\fP
.RS 4
int 磁盘转速 
.RE
.PP

.SS "double lingmo\&.lingmosdk\&.java\&.method\&.RunInfoMethod\&.getDiskTemperature (String name)\fC [inline]\fP"

.PP
获取磁盘温度 
.PP
\fBParameters\fP
.RS 4
\fIname\fP 磁盘名称，应当是例如/dev/sda这种绝对路径 
.RE
.PP
\fBReturns\fP
.RS 4
double 磁盘温度 
.RE
.PP

.SS "double lingmo\&.lingmosdk\&.java\&.method\&.RunInfoMethod\&.getNetSpeed (String nc)\fC [inline]\fP"

.PP
获取瞬时网速信息 
.PP
\fBParameters\fP
.RS 4
\fInc\fP 网卡名称，如eno1 
.RE
.PP
\fBReturns\fP
.RS 4
double 瞬时网速 
.RE
.PP

.SS "String lingmo\&.lingmosdk\&.java\&.method\&.RunInfoMethod\&.getObjectPath ()\fC [inline]\fP"

.PP
获取ObjectPath【未实现】 
.PP
\fBReturns\fP
.RS 4
String ObjectPath 
.RE
.PP

.SS "boolean lingmo\&.lingmosdk\&.java\&.method\&.RunInfoMethod\&.isRemote ()\fC [inline]\fP"

.PP
判断是否为远程对象 
.PP
\fBReturns\fP
.RS 4
boolean Returns true on remote objects\&. Local objects implementing this interface MUST return false\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for RunInfoMethod.java from the source code\&.
