{
    "KPlugin": {
        "Authors": [
            {
                "Email": "kde-artists@kde.org",
                "Name": "KDE Visual Design Group",
                "Name[ar]": "مجموعة التصميم المرئي لكِيدِي",
                "Name[az]": "KDE Vizual Dizayn Qrupu",
                "Name[be]": "Суполка візуальнага дызайну KDE",
                "Name[ca@valencia]": "Grup de disseny visual de KDE",
                "Name[ca]": "Grup de disseny visual de KDE",
                "Name[cs]": "Skupina vizuálního návrhu KDE",
                "Name[eo]": "KDE Vida Dezajna Grupo",
                "Name[es]": "El grupo de diseño visual de KDE",
                "Name[eu]": "KDE Diseinu bisualeko taldea",
                "Name[fi]": "KDE:n visuaalinen suunnitteluryhmä",
                "Name[fr]": "Groupe de conception graphique de KDE « VDG » (Visual Design Group)",
                "Name[gl]": "Grupo de deseño visual de KDE",
                "Name[he]": "קבוצת העיצוב החזותי של KDE",
                "Name[ia]": "KDE Visual Design Group (Gruppo de Designo Visual de KDE)",
                "Name[id]": "Grup Desain Visual KDE",
                "Name[is]": "Myndrænn hönnunarhópur KDE",
                "Name[ko]": "KDE 시각 디자인 그룹",
                "Name[lt]": "KDE vaizdinio dizaino grupė",
                "Name[lv]": "KDE Vizuālā dizaina grupa",
                "Name[nl]": "KDE Visuele ontwerpgroep",
                "Name[pl]": "Grupa oprawy graficznej KDE",
                "Name[pt]": "Grupo de Desenho Visual do KDE",
                "Name[pt_BR]": "Grupo de design visual do KDE (KDE VDG)",
                "Name[ru]": "Группа KDE Visual Design",
                "Name[sl]": "Skupina vizualnega designa KDE",
                "Name[sv]": "KDE:s visuella designgrupp",
                "Name[ta]": "கே.டீ.யீ. வரைகலை வடிவமைப்புக் குழு",
                "Name[tr]": "KDE Görsel Tasarım Grubu",
                "Name[uk]": "Група з візуального дизайну KDE",
                "Name[vi]": "Đội Thiết kế Trực quan KDE",
                "Name[x-test]": "xxKDE Visual Design Groupxx",
                "Name[zh_CN]": "KDE 视觉设计团队",
                "Name[zh_TW]": "KDE VDG 視覺設計組"
            }
        ],
        "Category": "",
        "Description": "Ocean Dark by the KDE VDG",
        "Description[ar]": "نسيم داكن من من مجموعة تصميم كِيدِي",
        "Description[az]": "KDE VDG tərəfindən Ocean Qara",
        "Description[be]": "Ocean Dark ад KDE VDG",
        "Description[bg]": "Ocean Тъмен от KDE VDG",
        "Description[ca@valencia]": "Brisa fosca, creat pel VDG de KDE",
        "Description[ca]": "Brisa fosca, creat pel VDG del KDE",
        "Description[cs]": "Ocean Dark od KDE VDG",
        "Description[de]": "Ocean Dunkel von der KDE VDG",
        "Description[eo]": "Ocean Dark de la KDE VDG",
        "Description[es]": "Brisa oscuro, por KDE VDG",
        "Description[eu]": "Brisa iluna KDEren VDGk egina",
        "Description[fi]": "Tumma Ocean KDE VDG:ltä",
        "Description[fr]": "Ocean sombre par l'équipe « KDE VDG »",
        "Description[gl]": "Brisa escura do KDE VDG.",
        "Description[he]": "בריזה כהה מאת קבוצת העיצוב החזותי של KDE",
        "Description[hu]": "Ocean Dark a KDE VDG-től",
        "Description[ia]": "Ocean Dark (Brisa Obscure) per le KDE VDG",
        "Description[id]": "Ocean Gelap oleh KDE VDG",
        "Description[is]": "Ocean Dark frá KDE VDG",
        "Description[it]": "Brezza scuro a cura del KDE VDG",
        "Description[ka]": "Ocean Dark \"KDE VDG\"-სგან",
        "Description[ko]": "KDE 시각 디자인 그룹에서 제작한 어두운 Ocean",
        "Description[lt]": "Ocean tamsus pagal KDE VDG",
        "Description[lv]": "KDE VDG veidotā „Ocean Dark“",
        "Description[nl]": "Ocean Dark door de KDE VDG",
        "Description[nn]": "Ocean mørk frå KDE VDG",
        "Description[pl]": "Ciemna Bryza autorstwa KDE VDG",
        "Description[pt]": "Brisa Escuro da VDG do KDE",
        "Description[pt_BR]": "Ocean pelo KDE VDG",
        "Description[ro]": "Briză, întunecat, de KDE VDG",
        "Description[ru]": "Тёмный вариант Ocean от KDE VDG",
        "Description[sa]": "KDE VDG द्वारा Ocean Dark",
        "Description[sk]": "Vánok Tmavý od KDE VDG",
        "Description[sl]": "Temna sapica od KDE VDG",
        "Description[sv]": "Ocean mörk av KDE:s visuella designgrupp",
        "Description[ta]": "கே.டீ.யீ. VDG வழங்கும் கரும் பிரீஸ்",
        "Description[tr]": "KDE VDG tarafından Esinti Koyu",
        "Description[uk]": "Темна Ocean, автори — KDE VDG",
        "Description[vi]": "Ocean Tối, do KDE VDG",
        "Description[x-test]": "xxOcean Dark by the KDE VDGxx",
        "Description[zh_CN]": "Ocean 微风深色主题，由 KDE VDG (视觉设计团队) 设计制作",
        "Description[zh_TW]": "由 KDE VDG 設計的 Ocean Dark",
        "EnabledByDefault": true,
        "Id": "ocean-dark",
        "License": "LGPL",
        "Name": "Ocean Dark",
        "Name[ar]": "نسيم داكن",
        "Name[az]": "Ocean Qara",
        "Name[bg]": "Ocean Тъмен",
        "Name[ca@valencia]": "Brisa fosca",
        "Name[ca]": "Brisa fosca",
        "Name[cs]": "Ocean Tmavé",
        "Name[de]": "Ocean Dunkel",
        "Name[eo]": "Vento Malhela",
        "Name[es]": "Brisa oscuro",
        "Name[eu]": "Brisa iluna",
        "Name[fi]": "Tumma Ocean",
        "Name[fr]": "Ocean Sombre",
        "Name[gl]": "Brisa escura",
        "Name[he]": "בריזה כהה",
        "Name[ia]": "Brisa obscure",
        "Name[id]": "Ocean Gelap",
        "Name[it]": "Brezza scuro",
        "Name[ko]": "어두운 Ocean",
        "Name[lt]": "Ocean tamsus",
        "Name[nn]": "Ocean mørk",
        "Name[pl]": "Ciemna Bryza",
        "Name[pt]": "Brisa Escura",
        "Name[ro]": "Briză, întunecat",
        "Name[ru]": "Ocean, тёмный вариант",
        "Name[sk]": "Vánok Tmavý",
        "Name[sl]": "Temna sapica",
        "Name[sv]": "Ocean mörk",
        "Name[ta]": "கரும் பிரீஸ்",
        "Name[tr]": "Esinti Koyu",
        "Name[uk]": "Темна Ocean",
        "Name[vi]": "Ocean Tối",
        "Name[x-test]": "xxOcean Darkxx",
        "Name[zh_CN]": "Ocean 微风深色",
        "Version": "@KF6_MIN_VERSION@",
        "Website": "https://www.kde.org/"
    },
    "X-Lingmo-API": "5.0"
}
