debian/local/etc/bindresvport.blacklist etc
debian/local/etc/ld.so.conf etc
debian/local/etc/ld.so.conf.d etc
debian/local/etc/nsswitch.conf usr/share/libc-bin
debian/local/etc/nss etc/default
posix/gai.conf etc
sbin/ldconfig usr/sbin
usr/bin/getconf
usr/bin/getent
usr/bin/iconv
usr/bin/ldd
usr/bin/ld.so
usr/bin/localedef
usr/bin/locale
usr/bin/pldd
usr/bin/tzselect
usr/lib/pt_chown
usr/sbin/iconvconfig
usr/bin/zdump
usr/sbin/zic
var/cache/ldconfig
${env:build-tree}/C.utf8 usr/lib/locale
