# This file is used for making biarch libraries development packages.
TMPDIR/LIBDIR/libanl.a LIBDIR
TMPDIR/LIBDIR/libBrokenLocale.a LIBDIR
TMPDIR/LIBDIR/libc.a LIBDIR
TMPDIR/LIBDIR/libc_nonshared.a LIBDIR
TMPDIR/LIBDIR/libdl.a LIBDIR
TMPDIR/LIBDIR/libg.a LIBDIR
TMPDIR/LIBDIR/libm.a LIBDIR
TMPDIR/LIBDIR/libm-*.a LIBDIR
TMPDIR/LIBDIR/libmcheck.a LIBDIR
TMPDIR/LIBDIR/libmvec.a LIBDIR
TMPDIR/LIBDIR/libpthread.a LIBDIR
TMPDIR/LIBDIR/libpthread_nonshared.a LIBDIR
TMPDIR/LIBDIR/libresolv.a LIBDIR
TMPDIR/LIBDIR/librt.a LIBDIR
TMPDIR/LIBDIR/libutil.a LIBDIR

TMPDIR/LIBDIR/*.o LIBDIR
TMPDIR/LIBDIR/*.so LIBDIR

TMPDIR/usr/share/gdb/* usr/share/gdb
