usr/bin/lingmo-search
etc/xdg/autostart/lingmo-search.desktop
usr/share/applications/lingmo-search-menu.desktop
usr/share/lingmo-search/translations/lingmo-search
usr/share/glib-2.0/schemas/org.lingmo.log4qt.lingmo-search.gschema.xml
usr/lib/*/lingmo-control-center/*
usr/share/lingmo-search/search-ukcc-plugin/translations/*
usr/share/lingmo-search/search-ukcc-plugin/image/*

usr/share/dbus-1/services/org.lingmo.appwidget.provider.search.service
usr/share/appwidget/*