#!/bin/sh
set -e

if [ "$1" = configure ]; then
	if command -v setcap >/dev/null; then
		if setcap cap_net_raw+ep /usr/bin/lingmo-system-monitor; then
			chmod u-s /usr/bin/lingmo-system-monitor
		else
			echo "Setcap failed, falling back to setuid" >&2
			chmod u+s /usr/bin/lingmo-system-monitor
		fi
	else
		echo "Setcap is not installed, falling back to setuid" >&2
		chmod u+s /usr/bin/lingmo-system-monitor
	fi
fi

# Restart service
if [ "$1" = "configure" ]; then
	if [ -d /run/systemd/system ]; then
		deb-systemd-invoke restart 'lingmo-service-manager.service' >/dev/null || true
	fi
fi

exit 0
