#!/bin/bash

set -e

DISK=*.iso

md5sum $DISK >> md5sum.README
md5sum $DISK >> md5sum.txt
sha1sum $DISK >> sha1sum.README
sha1sum $DISK >> sha1sum.txt
sha256sum $DISK >> sha256sum.README
sha256sum $DISK >> sha256sum.txt
sha384sum $DISK >> sha384sum.README
sha384sum $DISK >> sha384sum.txt
sha512sum $DISK >> sha512sum.README
sha512sum $DISK >> sha512sum.txt
