// SPDX-FileCopyrightText: 2022 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: LGPL-3.0-or-later

#ifndef DTKAUDIOMANAGER_GLOBAL_H
#define DTKAUDIOMANAGER_GLOBAL_H

#define DTK_NAMESPACE Dtk
#define DAUDIOMANAGER_NAMESPACE AudioManager
#define DTK_AUDIOMANAGER_NAMESPACE DTK_NAMESPACE::DAUDIOMANAGER_NAMESPACE

#define DAUDIOMANAGER_USE_NAMESPACE using namespace DTK_AUDIOMANAGER_NAMESPACE;

#define DAUDIOMANAGER_BEGIN_NAMESPACE namespace DTK_NAMESPACE { namespace DAUDIOMANAGER_NAMESPACE {
#define DAUDIOMANAGER_END_NAMESPACE }}

#include <QObject>

#if defined(DTK_STATIC_LIB)
#  define LIBDTKAUDIOMANAGERSHARED_EXPORT
#else
#if defined(LIBDTKAUDIOMANAGER_LIBRARY)
#  define LIBDTKAUDIOMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBDTKAUDIOMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif
#endif

#endif
