image: registry.salsa.debian.org/salsa-ci-team/ci-image-git-buildpackage:latest

pages:
  stage: deploy
  artifacts:
    paths:
      - public
  only:
    - master
  script:
    - gitlab-ci-git-buildpackage-all
    - gitlab-ci-aptly
