#!/bin/bash

PREREQ=""

prereqs()
{
    echo "${PREREQ}"
}

case "${1}" in
    prepare)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

TOOL_SCRIPT="/var/lib/deepin-boot-kit/scripts"
BOOTKIT="/usr/share/bootkit"

export INITRAMFS_UPDATE=n

/usr/sbin/deepin-boot-kit --action=mkinitrd || true
chmod -R 0755 $TOOL_SCRIPT
mkdir -p "${DESTDIR}/${BOOTKIT}" 2>/dev/null
cp -r "$TOOL_SCRIPT" "${DESTDIR}/$BOOTKIT" 2>/dev/null

INITRAMFS_UPDATE=