# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/plasma-nm/vpn/vpnc/vpncauth.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VpncAuth(object):
    def setupUi(self, VpncAuth):
        VpncAuth.setObjectName("VpncAuth")
        VpncAuth.resize(372, 171)
        self.gridlayout = QtWidgets.QGridLayout(VpncAuth)
        self.gridlayout.setContentsMargins(0, 0, 0, 0)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.userPasswordLabel = QtWidgets.QLabel(VpncAuth)
        self.userPasswordLabel.setWordWrap(False)
        self.userPasswordLabel.setObjectName("userPasswordLabel")
        self.gridlayout.addWidget(self.userPasswordLabel, 1, 0, 1, 1)
        self.groupPasswordLabel = QtWidgets.QLabel(VpncAuth)
        self.groupPasswordLabel.setWordWrap(False)
        self.groupPasswordLabel.setObjectName("groupPasswordLabel")
        self.gridlayout.addWidget(self.groupPasswordLabel, 3, 0, 1, 1)
        self.leUserPassword = PasswordField(VpncAuth)
        self.leUserPassword.setProperty("passwordModeEnabled", True)
        self.leUserPassword.setObjectName("leUserPassword")
        self.gridlayout.addWidget(self.leUserPassword, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem, 4, 1, 1, 1)
        self.leGroupPassword = PasswordField(VpncAuth)
        self.leGroupPassword.setProperty("passwordModeEnabled", True)
        self.leGroupPassword.setObjectName("leGroupPassword")
        self.gridlayout.addWidget(self.leGroupPassword, 3, 2, 1, 1)
        self.leUserName = QtWidgets.QLineEdit(VpncAuth)
        self.leUserName.setEnabled(False)
        self.leUserName.setObjectName("leUserName")
        self.gridlayout.addWidget(self.leUserName, 0, 2, 1, 1)
        self.userNameLabel = QtWidgets.QLabel(VpncAuth)
        self.userNameLabel.setObjectName("userNameLabel")
        self.gridlayout.addWidget(self.userNameLabel, 0, 0, 1, 1)
        self.leGroupName = QtWidgets.QLineEdit(VpncAuth)
        self.leGroupName.setEnabled(False)
        self.leGroupName.setObjectName("leGroupName")
        self.gridlayout.addWidget(self.leGroupName, 2, 2, 1, 1)
        self.groupNameLabel = QtWidgets.QLabel(VpncAuth)
        self.groupNameLabel.setWordWrap(False)
        self.groupNameLabel.setObjectName("groupNameLabel")
        self.gridlayout.addWidget(self.groupNameLabel, 2, 0, 1, 1)
        self.userPasswordLabel.setBuddy(self.leUserPassword)
        self.groupPasswordLabel.setBuddy(self.leGroupPassword)
        self.userNameLabel.setBuddy(self.leUserName)
        self.groupNameLabel.setBuddy(self.leGroupName)

        self.retranslateUi(VpncAuth)
        QtCore.QMetaObject.connectSlotsByName(VpncAuth)
        VpncAuth.setTabOrder(self.leUserName, self.leUserPassword)
        VpncAuth.setTabOrder(self.leUserPassword, self.leGroupName)
        VpncAuth.setTabOrder(self.leGroupName, self.leGroupPassword)

    def retranslateUi(self, VpncAuth):
        _translate = QtCore.QCoreApplication.translate
        VpncAuth.setWindowTitle(_translate("VpncAuth", "VPNCAuthentication"))
        self.userPasswordLabel.setText(_translate("VpncAuth", "User Password:"))
        self.groupPasswordLabel.setText(_translate("VpncAuth", "Group Password:"))
        self.leUserPassword.setToolTip(_translate("VpncAuth", "User password for the connection."))
        self.leGroupPassword.setToolTip(_translate("VpncAuth", "Group password."))
        self.leUserName.setToolTip(_translate("VpncAuth", "User name for the connection."))
        self.userNameLabel.setText(_translate("VpncAuth", "Username:"))
        self.leGroupName.setToolTip(_translate("VpncAuth", "Group name."))
        self.groupNameLabel.setText(_translate("VpncAuth", "Group name:"))
from passwordfield import PasswordField
