# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/utils/kate/addons/snippets/editrepository.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditRepositoryBase(object):
    def setupUi(self, EditRepositoryBase):
        EditRepositoryBase.setObjectName("EditRepositoryBase")
        EditRepositoryBase.resize(500, 323)
        EditRepositoryBase.setMinimumSize(QtCore.QSize(500, 0))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(EditRepositoryBase)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(EditRepositoryBase)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.repoNameLabel = QtWidgets.QLabel(self.widget)
        self.repoNameLabel.setObjectName("repoNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.repoNameLabel)
        self.repoNamespaceLabel = QtWidgets.QLabel(self.widget)
        self.repoNamespaceLabel.setObjectName("repoNamespaceLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.repoNamespaceLabel)
        self.repoLicenseLabel = QtWidgets.QLabel(self.widget)
        self.repoLicenseLabel.setObjectName("repoLicenseLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.repoLicenseLabel)
        self.repoLicenseEdit = QtWidgets.QComboBox(self.widget)
        self.repoLicenseEdit.setObjectName("repoLicenseEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.repoLicenseEdit)
        self.repoAuthorsLabel = QtWidgets.QLabel(self.widget)
        self.repoAuthorsLabel.setObjectName("repoAuthorsLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.repoAuthorsLabel)
        self.repoAuthorsEdit = KLineEdit(self.widget)
        self.repoAuthorsEdit.setObjectName("repoAuthorsEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.repoAuthorsEdit)
        self.repoFileTypesLabel = QtWidgets.QLabel(self.widget)
        self.repoFileTypesLabel.setObjectName("repoFileTypesLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.repoFileTypesLabel)
        self.repoFileTypesListLabel = QtWidgets.QLabel(self.widget)
        self.repoFileTypesListLabel.setText("list of selected filetypes")
        self.repoFileTypesListLabel.setObjectName("repoFileTypesListLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.repoFileTypesListLabel)
        self.repoFileTypesList = QtWidgets.QListWidget(self.widget)
        self.repoFileTypesList.setObjectName("repoFileTypesList")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.repoFileTypesList)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)
        self.repoNameEdit = QtWidgets.QLineEdit(self.widget)
        self.repoNameEdit.setObjectName("repoNameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.repoNameEdit)
        self.repoNamespaceEdit = QtWidgets.QLineEdit(self.widget)
        self.repoNamespaceEdit.setObjectName("repoNamespaceEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.repoNamespaceEdit)
        self.verticalLayout_2.addWidget(self.widget)
        self.repoLicenseLabel.setBuddy(self.repoLicenseEdit)
        self.repoAuthorsLabel.setBuddy(self.repoAuthorsEdit)
        self.repoFileTypesLabel.setBuddy(self.repoFileTypesList)

        self.retranslateUi(EditRepositoryBase)
        QtCore.QMetaObject.connectSlotsByName(EditRepositoryBase)

    def retranslateUi(self, EditRepositoryBase):
        _translate = QtCore.QCoreApplication.translate
        self.repoNameLabel.setText(_translate("EditRepositoryBase", "Name:"))
        self.repoNamespaceLabel.setText(_translate("EditRepositoryBase", "Namespace:"))
        self.repoLicenseLabel.setText(_translate("EditRepositoryBase", "&License:"))
        self.repoAuthorsLabel.setText(_translate("EditRepositoryBase", "&Authors:"))
        self.repoFileTypesLabel.setText(_translate("EditRepositoryBase", "&File types:"))
        self.repoNameEdit.setPlaceholderText(_translate("EditRepositoryBase", "A short name for the repository"))
        self.repoNamespaceEdit.setPlaceholderText(_translate("EditRepositoryBase", "Prefix to show in code completion"))
from klineedit import KLineEdit
