# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/utils/kate/addons/katebuild-plugin/buildconfigwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BuildConfigWidget(object):
    def setupUi(self, BuildConfigWidget):
        BuildConfigWidget.setObjectName("BuildConfigWidget")
        BuildConfigWidget.resize(699, 770)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(BuildConfigWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(BuildConfigWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtCore.Qt.QFormLayout::FieldGrowthPolicy::ExpandingFieldsGrow)
        self.formLayout.setFormAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignHCenter|QtCore.Qt.Qt::AlignmentFlag::AlignTop)
        self.formLayout.setContentsMargins(-1, -1, -1, 0)
        self.formLayout.setObjectName("formLayout")
        self.useDiagnosticsCB = QtWidgets.QCheckBox(self.tab)
        self.useDiagnosticsCB.setObjectName("useDiagnosticsCB")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.useDiagnosticsCB)
        self.autoSwitchToOutput = QtWidgets.QCheckBox(self.tab)
        self.autoSwitchToOutput.setObjectName("autoSwitchToOutput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.autoSwitchToOutput)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.verticalLayout_6.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtCore.Qt.QSizePolicy::Policy::Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.allowedAndBlockedCommands = QtWidgets.QListWidget(self.tab_4)
        self.allowedAndBlockedCommands.setObjectName("allowedAndBlockedCommands")
        self.verticalLayout.addWidget(self.allowedAndBlockedCommands)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_3.addWidget(self.tabWidget)

        self.retranslateUi(BuildConfigWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BuildConfigWidget)

    def retranslateUi(self, BuildConfigWidget):
        _translate = QtCore.QCoreApplication.translate
        self.useDiagnosticsCB.setText(_translate("BuildConfigWidget", "Add errors and warnings to Diagnostics"))
        self.autoSwitchToOutput.setText(_translate("BuildConfigWidget", "Automatically switch to output pane on executing the selected target"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("BuildConfigWidget", "General Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("BuildConfigWidget", "Allowed && Blocked Commands"))
