.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 hufeng <hufeng@uniontech.com>,
.\"
.TH "deepin-compressor" "1" "2021-1-28" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
deepin-compressor \- archive manager for deepin.
.SH SYNOPSIS
deepin-compressor [FILE(s)...] [OPTIONS...]
.SH DESCRIPTION
Archive Manager is a fast and lightweight application for creating and extracting archives.
.PP
It supports multiple compressing formats such as 7z, jar, tar, tar.bz2, tar.gz, tar.lz, tar.lzm, tar.lzo, tar.Z, tar.7z, zip as well as encrypted compressing settings
.SH OPTIONS
.PP
Note: file(s) + command
.PP
compress                Compress files，e.g. xx.txt xx1.txt compress
.PP
compress_to_7z          Compress to 7z format, e.g. xx.txt xx1.txt compress_to_7z
.PP
compress_to_zip         Compress to zip format, e.g. xx.txt xx1.txt compress_to_zip
.PP
extract                 Extract files, e.g. xx.zip xx1.zip extract
.PP
extract_here            Extract to current folder, e.g. xx.zip xx1.zip extract_here
.PP
extract_to_specifypath  Extract to a specified folder, e.g. xx.zip xx1.zip extract_to_specifypath
.PP
dragdropadd             Drag and drop files from File Manager, e.g. xx.zip xx.txt xx1.txt dragdropadd
.SH SEE ALSO
https://github.com/linuxdeepin/deepin-compressor
.SH AUTHOR
.PP
.B deepin-compressor
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT gaoxiang@\:uniontech.com
Gao Xiang
.ME
for the Debian Project (but may be used by others)
