#!/usr/bin/perl
# Just boot whatever is default in the boot loader.
use strict;
use Expect;

my $exp = new Expect;
#$exp->exp_internal(1);
$exp->raw_pty(1);

$exp->spawn($ENV{CONSOLECOMMAND}) or die "cannot connect: $!\n";

$exp->expect(600, "boot: ");
$exp->send("\r");

