#!/bin/sh
# This script uses the HP Integrated Lights Out system to boot a Proliant
# or similar server. The server may be in a powered off state (though ILO
# must be functional) before being booted.
hp-ilo force_restart
