# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/lingmo-nm/vpn/pptp/pptpauth.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PptpAuthenticationWidget(object):
    def setupUi(self, PptpAuthenticationWidget):
        PptpAuthenticationWidget.setObjectName("PptpAuthenticationWidget")
        PptpAuthenticationWidget.resize(372, 85)
        self.formLayout = QtWidgets.QFormLayout(PptpAuthenticationWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.textLabel1 = QtWidgets.QLabel(PptpAuthenticationWidget)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.textLabel1)
        self.lePassword = PasswordField(PptpAuthenticationWidget)
        self.lePassword.setProperty("passwordModeEnabled", True)
        self.lePassword.setObjectName("lePassword")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lePassword)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.textLabel1.setBuddy(self.lePassword)

        self.retranslateUi(PptpAuthenticationWidget)
        QtCore.QMetaObject.connectSlotsByName(PptpAuthenticationWidget)

    def retranslateUi(self, PptpAuthenticationWidget):
        _translate = QtCore.QCoreApplication.translate
        PptpAuthenticationWidget.setWindowTitle(_translate("PptpAuthenticationWidget", "PPTPAuthentication"))
        self.textLabel1.setText(_translate("PptpAuthenticationWidget", "Password:"))
        self.lePassword.setToolTip(_translate("PptpAuthenticationWidget", "Password passed to PPTP when prompted for it."))
from passwordfield import PasswordField
