usr/lib/*/lingmo-control-center
usr/bin
audio/translations/* usr/share/lingmo-media/translations/audio
lingmo-volume-control-applet-qt/translations/*.qm usr/share/lingmo-media/translations/
lingmo-volume-control-applet-qt/data/img/* /usr/share/lingmo-media/img
lingmo-volume-control-applet-qt/data/qss/* /usr/share/lingmo-media/qss
lingmo-volume-control-applet-qt/data/sounds/* /usr/share/lingmo-media/sounds
lingmo-volume-control-applet-qt/data/org.lingmo.sound.gschema.xml /usr/share/glib-2.0/schemas
scripts/detection_output_mode.sh /usr/share/lingmo-media/scripts
data/org.lingmo.media.sound.gschema.xml /usr/share/glib-2.0/schemas
data/lingmo-media-control-mute-led.service /lib/systemd/system
data/sound-theme-player.desktop /etc/xdg/autostart

#Sound card adaptation
scripts/soundCardAdaptation.sh /usr/share/lingmo-media/scripts
configuration/99-lingmo-media.rules /usr/lib/udev/rules.d
configuration/lingmo-profiles/* /usr/share/pulseaudio/alsa-mixer/profile-sets
configuration/lingmo-paths/* /usr/share/pulseaudio/alsa-mixer/paths
