[Desktop Entry]
Type=XSession
Exec=${CMAKE_INSTALL_FULL_BINDIR}/startlingmo-x11
TryExec=${CMAKE_INSTALL_FULL_BINDIR}/startlingmo-x11
DesktopNames=KDE
Name=Lingmo OS Desktop (X11)
Name[az]=Lingmo OS Desktop (X11)
Name[be]=Lingmo OS Desktop (X11)
Name[bg]=Lingmo OS Desktop (X11)
Name[ca]=Lingmo OS Desktop (X11)
Name[ca@valencia]=Lingmo OS Desktop (X11)
Name[cs]=Lingmo OS Desktop (X11)
Name[da]=Lingmo OS Desktop (X11)
Name[de]=Lingmo OS Desktop (X11)
Name[en_GB]=Lingmo OS Desktop (X11)
Name[eo]=Lingmo OS Desktop (X11)
Name[es]=Lingmo OS Desktop (X11)
Name[eu]=Lingmo OS Desktop (X11)
Name[fi]=Lingmo OS Desktop (X11)
Name[fr]=Lingmo OS Desktop (X11)
Name[hu]=Lingmo OS Desktop (X11)
Name[ia]=Lingmo OS Desktop (X11)
Name[id]=Lingmo OS Desktop (X11)
Name[is]=Lingmo OS Desktop (X11)
Name[it]=Lingmo OS Desktop (X11)
Name[ja]=Lingmo OS Desktop (X11)
Name[ka]=Lingmo OS Desktop (X11)
Name[ko]=Lingmo OS Desktop(X11)
Name[lt]=Lingmo OS Desktop (X11)
Name[nl]=Lingmo OS Desktop (X11)
Name[nn]=Lingmo OS Desktop (X11)
Name[pt]=Lingmo OS Desktop (X11)
Name[pt_BR]=Lingmo OS Desktop (X11)
Name[ro]=Lingmo OS Desktop (X11)
Name[ru]=Lingmo OS Desktop (X11)
Name[sk]=Lingmo OS Desktop (X11)
Name[sl]=Lingmo OS Desktop (X11)
Name[sv]=Lingmo OS Desktop (X11)
Name[tr]=Lingmo OS Desktop (X11)
Name[vi]=Lingmo OS Desktop (X11)
Name[x-test]=xxLingmo OS Desktop (X11)xx
Name[zh_CN]=Lingmo OS Desktop (X11)
Name[zh_TW]=Lingmo OS Desktop (X11)
Comment=Lingmo OS Desktop
Comment[az]=Lingmo OS Desktop
Comment[be]=Lingmo OS Desktop
Comment[bg]=Lingmo OS Desktop
Comment[bs]=Plazma od strane
Comment[ca]=Lingmo OS Desktop
Comment[ca@valencia]=Lingmo OS Desktop
Comment[cs]=Lingmo OS Desktop
Comment[da]=Lingmo OS Desktop
Comment[de]=Lingmo OS Desktop
Comment[el]=Lingmo OS Desktop
Comment[en_GB]=Lingmo OS Desktop
Comment[es]=Lingmo OS Desktop
Comment[et]=Lingmo OS Desktop
Comment[eu]=KDEren Lingmo OS Desktop
Comment[fi]=Lingmo OS Desktop
Comment[fr]=Lingmo OS Desktop
Comment[gl]=Lingmo OS Desktop
Comment[hsb]=Lingmo OS Desktop
Comment[hu]=Lingmo OS Desktop
Comment[ia]=Lingmo OS Desktop
Comment[id]=Lingmo OS Desktop
Comment[is]=Lingmo OS Desktop
Comment[it]=Lingmo OS Desktop
Comment[ja]=Lingmo OS Desktop
Comment[ka]=Lingmo OS Desktop
Comment[ko]=Lingmo OS Desktop
Comment[lt]=Lingmo OS Desktop
Comment[nb]=Lingmo OS Desktop
Comment[nds]=Lingmo OS Desktop
Comment[nl]=Lingmo OS Desktop
Comment[nn]=Lingmo OS Desktop
Comment[pt]=Lingmo OS Desktop
Comment[pt_BR]=Lingmo OS Desktop
Comment[ro]=Lingmo OS Desktop
Comment[ru]=Lingmo OS Desktop
Comment[sk]=Lingmo OS Desktop
Comment[sl]=Lingmo OS Desktop
Comment[sr@ijekavianlatin]=Lingmo OS Desktop
Comment[sr@latin]=Lingmo OS Desktop
Comment[sv]=Lingmo OS Desktop
Comment[tg]=Lingmo OS Desktop
Comment[tr]=Lingmo OS Desktop
Comment[vi]=Lingmo OS Desktop
Comment[x-test]=xxLingmo OS Desktopxx
Comment[zh_CN]=Lingmo 桌面
Comment[zh_TW]=Lingmo 桌面
X-KDE-PluginInfo-Version=${PROJECT_VERSION}
