[Desktop Entry]
Type=XSession
Exec=@CMAKE_INSTALL_FULL_LIBEXECDIR@/startlingmo-dev.sh -x11
DesktopNames=KDE
Name=Lingmo OS Desktop (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[az]=Lingmo OS Desktop (Tərtib mərhələsində olan X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[be]=Lingmo OS Desktop (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[bg]=Lingmo OS Desktop (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ca]=Lingmo OS Desktop (Desenvolupament, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ca@valencia]=Lingmo OS Desktop (Desenvolupament, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[da]=Lingmo OS Desktop (udvikling, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[de]=Lingmo OS Desktop (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[en_GB]=Lingmo OS Desktop (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[es]=Lingmo OS Desktop (Desarrollo, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[et]=Lingmo OS Desktop (arendus, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[eu]=Lingmo OS Desktop (Garapena, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[fi]=Lingmo OS Desktop (kehitys, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[fr]=Lingmo OS Desktop (Développement, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[gl]=Lingmo OS Desktop (desenvolvemento, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[hu]=Lingmo OS Desktop (Fejlesztői verzió, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ia]=Lingmo OS Desktop (Disveloppamento, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[id]=Lingmo OS Desktop (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[is]=Lingmo OS Desktop (Þróunarútgáfa, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[it]=Lingmo OS Desktop (Sviluppo, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ja]=Lingmo OS Desktop (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ka]=Lingmo OS Desktop (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ko]=Lingmo OS Desktop(개발, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[lt]=Lingmo OS Desktop (Plėtojimas, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[nl]=Lingmo OS Desktop (Ontwikkeling, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[nn]=Lingmo OS Desktop (utvikling, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[pt]=Lingmo OS Desktop (Desenvolvimento, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[pt_BR]=Lingmo OS Desktop (Desenvolvimento, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ro]=Lingmo OS Desktop (Dezvoltare, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ru]=Lingmo OS Desktop (разрабатываемая версия, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[sk]=Lingmo OS Desktop (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[sl]=Lingmo OS Desktop (Razvoj, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[sv]=Lingmo OS Desktop (utveckling, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[tr]=Lingmo OS Desktop (Geliştirme, X11 $ {CMAKE_INSTALL_FULL_BINDIR})
Name[uk]=Плазма (Розробка, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[vi]=Lingmo OS Desktop (Phát triển, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[x-test]=xxLingmo OS Desktop (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})xx
Name[zh_CN]=Lingmo OS Desktop (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[zh_TW]=Lingmo OS Desktop (開發版本，X11 ${CMAKE_INSTALL_FULL_BINDIR})
Comment=Lingmo OS Desktop
Comment[x-test]=xxLingmo OS Desktopxx
Comment[zh_CN]=Lingmo OS
Comment[zh_TW]=Lingmo OS Desktop
X-KDE-PluginInfo-Version=${PROJECT_VERSION}
