Document: libdareader
Title: Debian libdareader Manual
Author: <insert document author here>
Abstract: This manual describes what libdareader is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libdareader/libdareader.sgml.gz

Format: postscript
Files: /usr/share/doc/libdareader/libdareader.ps.gz

Format: text
Files: /usr/share/doc/libdareader/libdareader.text.gz

Format: HTML
Index: /usr/share/doc/libdareader/html/index.html
Files: /usr/share/doc/libdareader/html/*.html
