.\" Man page for Peony-Qt desktop
.TH Peony-Qt 1 "09 December 2019" "LINGMO Desktop Environment"
.SH "NAME"
Peony-Qt-Desktop \- The LINGMO3.0 desktop program.
.SH "SYNOPSIS"
.B explor-qt-desktop [OPTION]
.SH "DESCRIPTION"
Peony-Qt is the default file manager for LINGMO3.0. 
.PP
This is the desktop program command line tool for interaction of terminal.
.SH "OPTIONS"
.TP
\fB -q, --quit\fR
Close the desktop window, stop the running service and quit.
.TP
\fB -d, --daemon\fR
Run program with DBus service.
.TP
\fB -w, --desktop-window\fR
Show desktop window.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at:
https://github.com/lingmo/explor/issues
.SH "AUTHORS"
.SS This Manual Page has been written for the LINGMO Desktop Environment by:
Yue Lan <lanyue@kylinos.cn> (2019)
