# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/lingmo-nm/libs/editor/connectioneditortabwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConnectionEditorTabWidget(object):
    def setupUi(self, ConnectionEditorTabWidget):
        ConnectionEditorTabWidget.setObjectName("ConnectionEditorTabWidget")
        ConnectionEditorTabWidget.resize(498, 427)
        self.gridLayout = QtWidgets.QGridLayout(ConnectionEditorTabWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(ConnectionEditorTabWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.connectionName = QtWidgets.QLineEdit(ConnectionEditorTabWidget)
        self.connectionName.setObjectName("connectionName")
        self.gridLayout.addWidget(self.connectionName, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(ConnectionEditorTabWidget)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 2)
        self.label.setBuddy(self.connectionName)

        self.retranslateUi(ConnectionEditorTabWidget)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(ConnectionEditorTabWidget)

    def retranslateUi(self, ConnectionEditorTabWidget):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("ConnectionEditorTabWidget", "Connection name:"))
