.TH "LIBKYUTILS" 3 "Fri Sep 22 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libkyutils \- 单位进制转换组件
.SH SYNOPSIS

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBKDKUtilsErrCode\fP { \fBKDK_NOERR\fP, \fBKDK_INVAILD_BASE\fP, \fBKDK_INVAILD_ARGUMENT\fP, \fBKDK_INVAILD_DATA_FORMAT\fP, \fBKDK_SYSTEM_UNKOWNERR\fP }"
.br
.ti -1c
.RI "enum \fBKDKVolumeBaseType\fP { \fBKDK_KILOBYTE\fP = 1, \fBKDK_MEGABYTE\fP, \fBKDK_GIGABYTE\fP, \fBKDK_TERABYTE\fP, \fBKDK_PETABYTE\fP, \fBKDK_EXABYTE\fP, \fBKDK_KILO\fP, \fBKDK_MEGA\fP, \fBKDK_GIGA\fP, \fBKDK_TERA\fP, \fBKDK_PETA\fP, \fBKDK_EXA\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBkdkVolumeBaseCharacterConvert\fP (const char *origin_data, \fBKDKVolumeBaseType\fP result_base, char *result_data)"
.br
.RI "字符格式单位进制转换 "
.ti -1c
.RI "int \fBkdkVolumeBaseNumericalConvert\fP (double origin_numerical, \fBKDKVolumeBaseType\fP origin_base, \fBKDKVolumeBaseType\fP result_base, double *result_numerical)"
.br
.RI "数字格式单位进制转换 "
.in -1c
.SH "Detailed Description"
单位进制转换组件
.SH "CONFORMING TO"
These functions are as per the withdrawn POSIX.1e draft specification.
The following functions are Linux extensions:
.BR kdkVolumeBaseCharacterConvert ()
and
.BR kdkVolumeBaseNumericalConvert ().
.SH "SEE ALSO"
.BR kdkVolumeBaseCharacterConvert (3)
and
.BR kdkVolumeBaseNumericalConvert (3).

.SH "Author"
.PP 
Generated automatically by Doxygen for kyutils.h from the source code\&.
