.TH "STRENDWITH" 3 "Sat Sep 23 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
strendwith \-  判断str是否以postfix结尾；注意该函数区分大小写 

.SH SYNOPSIS
.br
.PP
\fC#include <cstring-extension\&.h>\fP
.br

.SS "Functions"
.SS "static int strendwith (const char * str, const char * postfix)\fC [inline]\fP, \fC [static]\fP"

.PP
判断str是否以postfix结尾；注意该函数区分大小写 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP 原字符串 
.br
\fIpostfix\fP 需要匹配的字符串后缀 
.RE
.PP
\fBReturns\fP
.RS 4
int 若str以postfix结尾，则返回0；否则返回1 
.RE
.PP
.SH "Detailed Description"
.PP 
接口的主要功能是判断str是否以postfix结尾；注意该函数区分大小写 
.SH "CONFORMING TO"
These functions are as per the withdrawn POSIX.1e draft specification.
The following functions are Linux extensions:
.BR strstrip (),
.BR strstripspace (),
.BR strstripblank (),
.BR strskipspace (),
.BR strskipblank (),
.BR str2upper (),
.BR str2lower (),
.BR strfirstof (),
.BR strlastof (),
.BR strstartswith (),
.BR strstartswith_nocase (),
.BR strcounts ()
and
.BR strsplit ().
.SH "SEE ALSO"
.BR strstrip (3),
.BR strstripspace (3),
.BR strstripblank (3),
.BR strskipspace (3),
.BR strskipblank (3),
.BR str2upper (3),
.BR str2lower (3),
.BR strfirstof (3),
.BR strlastof (3),
.BR strstartswith (3),
.BR strstartswith_nocase (3),
.BR strcounts (3)
and
.BR strsplit (3).

.SH "Author"
.PP 
Generated automatically by Doxygen for cstring-extension.h from the source code\&.
