.TH "STRFIRSTOF" 3 "Sat Sep 23 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
strfirstof \-  在给定的字符串中查找给定字符第一次出现的位置  

.SH SYNOPSIS
.br
.PP
\fC#include <cstring-extension\&.h>\fP
.br

.SS "Functions"
.SS "static int strfirstof (const char * str, char ch)\fC [inline]\fP, \fC [static]\fP"

.PP
在给定的字符串中查找给定字符第一次出现的位置；计数从0开始 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP 原字符串 
.br
\fIch\fP 需要查找的字符 
.RE
.PP
\fBReturns\fP
.RS 4
int 第一次出现的位置，若未找到给定的字符，则返回-1 
.RE
.PP
.SH "Detailed Description"
.PP 
接口的主要功能是在给定的字符串中查找给定字符第一次出现的位置；计数从0开始
.SH "CONFORMING TO"
These functions are as per the withdrawn POSIX.1e draft specification.
The following functions are Linux extensions:
.BR strstrip (),
.BR strstripspace (),
.BR strstripblank (),
.BR strskipspace (),
.BR strskipblank (),
.BR str2upper (),
.BR str2lower (),
.BR strlastof (),
.BR strstartswith (),
.BR strstartswith_nocase (),
.BR strendwith (),
.BR strendwith_nocase (),
.BR strcounts ()
and
.BR strsplit ().
.SH "SEE ALSO"
.BR strstrip (3),
.BR strstripspace (3),
.BR strstripblank (3),
.BR strskipspace (3),
.BR strskipblank (3),
.BR str2upper (3),
.BR str2lower (3),
.BR strlastof (3),
.BR strstartswith (3),
.BR strstartswith_nocase (3),
.BR strendwith (3),
.BR strendwith_nocase (3),
.BR strcounts (3)
and
.BR strsplit (3).

.SH "Author"
.PP 
Generated automatically by Doxygen for cstring-extension.h from the source code\&.
