.TH "STRSTRIP" 3 "Sat Sep 23 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
strstrip \- 对给定的字符串进行strip操作，删减字符串前后的指定字符  

.SH SYNOPSIS
.br
.PP
\fC#include <cstring-extension\&.h>\fP
.br

.SS "Functions"
.SS "static void str2lower (char * str)\fC [inline]\fP, \fC [static]\fP"

.PP
将字符串中的所有大写字母转化为小写字母；注意该操作会修改原字符串 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP 需要操作的字符串指针 
.RE
.PP
.SH "Detailed Description"
.PP 
接口的主要功能是将字符串中的所有大写字母转化为小写字母；注意该操作会修改原字符串
.SH "CONFORMING TO"
These functions are as per the withdrawn POSIX.1e draft specification.
The following functions are Linux extensions:
.BR strstripspace (),
.BR strstripblank (),
.BR strskipspace (),
.BR strskipblank (),
.BR str2upper (),
.BR str2lower (),
.BR strfirstof (),
.BR strlastof (),
.BR strstartswith (),
.BR strstartswith_nocase (),
.BR strendwith (),
.BR strendwith_nocase (),
.BR strcounts ()
and
.BR strsplit ().
.SH "SEE ALSO"
.BR strstripspace (3),
.BR strstripblank (3),
.BR strskipspace (3),
.BR strskipblank (3),
.BR str2upper (3),
.BR str2lower (3),
.BR strfirstof (3),
.BR strlastof (3),
.BR strstartswith (3),
.BR strstartswith_nocase (3),
.BR strendwith (3),
.BR strendwith_nocase (3),
.BR strcounts (3)
and
.BR strsplit (3).

.SH "Author"
.PP 
Generated automatically by Doxygen for cstring-extension.h from the source code\&.
