# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/kwidgetsaddons/src/kdatetimeedit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KDateTimeEdit(object):
    def setupUi(self, KDateTimeEdit):
        KDateTimeEdit.setObjectName("KDateTimeEdit")
        KDateTimeEdit.resize(450, 33)
        self.horizontalLayout = QtWidgets.QHBoxLayout(KDateTimeEdit)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.m_calendarCombo = QtWidgets.QComboBox(KDateTimeEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_calendarCombo.sizePolicy().hasHeightForWidth())
        self.m_calendarCombo.setSizePolicy(sizePolicy)
        self.m_calendarCombo.setObjectName("m_calendarCombo")
        self.horizontalLayout.addWidget(self.m_calendarCombo)
