# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/kwidgetsaddons/src/knewpasswordwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KNewPasswordWidget(object):
    def setupUi(self, KNewPasswordWidget):
        KNewPasswordWidget.setObjectName("KNewPasswordWidget")
        KNewPasswordWidget.resize(273, 130)
        self.verticalLayout = QtWidgets.QVBoxLayout(KNewPasswordWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelPassword = QtWidgets.QLabel(KNewPasswordWidget)
        self.labelPassword.setObjectName("labelPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelPassword)
        self.labelVerifyPassword = QtWidgets.QLabel(KNewPasswordWidget)
        self.labelVerifyPassword.setObjectName("labelVerifyPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelVerifyPassword)
        self.linePassword = KPasswordLineEdit(KNewPasswordWidget)
        self.linePassword.setObjectName("linePassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.linePassword)
        self.lineVerifyPassword = QtWidgets.QLineEdit(KNewPasswordWidget)
        self.lineVerifyPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineVerifyPassword.setObjectName("lineVerifyPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineVerifyPassword)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelStrengthMeter = QtWidgets.QLabel(KNewPasswordWidget)
        self.labelStrengthMeter.setObjectName("labelStrengthMeter")
        self.horizontalLayout.addWidget(self.labelStrengthMeter)
        self.strengthBar = QtWidgets.QProgressBar(KNewPasswordWidget)
        self.strengthBar.setProperty("value", 0)
        self.strengthBar.setTextVisible(False)
        self.strengthBar.setObjectName("strengthBar")
        self.horizontalLayout.addWidget(self.strengthBar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.labelPassword.setBuddy(self.linePassword)
        self.labelVerifyPassword.setBuddy(self.lineVerifyPassword)
        self.labelStrengthMeter.setBuddy(self.strengthBar)

        self.retranslateUi(KNewPasswordWidget)
        QtCore.QMetaObject.connectSlotsByName(KNewPasswordWidget)

    def retranslateUi(self, KNewPasswordWidget):
        _translate = QtCore.QCoreApplication.translate
        self.labelPassword.setText(_translate("KNewPasswordWidget", "Password:", "@label:textbox"))
        self.labelVerifyPassword.setText(_translate("KNewPasswordWidget", "&Verify:", "@label:textbox"))
        self.labelStrengthMeter.setText(_translate("KNewPasswordWidget", "Password strength &meter:", "@label"))
from kpasswordlineedit import KPasswordLineEdit
