# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/kwidgetsaddons/src/kpassworddialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KPasswordDialog(object):
    def setupUi(self, KPasswordDialog):
        KPasswordDialog.setObjectName("KPasswordDialog")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(KPasswordDialog.sizePolicy().hasHeightForWidth())
        KPasswordDialog.setSizePolicy(sizePolicy)
        self.vBoxLayout = QtWidgets.QVBoxLayout(KPasswordDialog)
        self.vBoxLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.vBoxLayout.setObjectName("vBoxLayout")
        self.hboxLayout = QtWidgets.QHBoxLayout()
        self.hboxLayout.setObjectName("hboxLayout")
        self.pixmapLabel = QtWidgets.QLabel(KPasswordDialog)
        self.pixmapLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pixmapLabel.setObjectName("pixmapLabel")
        self.hboxLayout.addWidget(self.pixmapLabel)
        self.prompt = QtWidgets.QLabel(KPasswordDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prompt.sizePolicy().hasHeightForWidth())
        self.prompt.setSizePolicy(sizePolicy)
        self.prompt.setTextFormat(QtCore.Qt.RichText)
        self.prompt.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.prompt.setWordWrap(True)
        self.prompt.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.prompt.setObjectName("prompt")
        self.hboxLayout.addWidget(self.prompt)
        self.vBoxLayout.addLayout(self.hboxLayout)
        spacerItem = QtWidgets.QSpacerItem(400, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.vBoxLayout.addItem(spacerItem)
        self.errorMessage = KTitleWidget(KPasswordDialog)
        self.errorMessage.setObjectName("errorMessage")
        self.vBoxLayout.addWidget(self.errorMessage)
        self.anonymousRadioButton = QtWidgets.QRadioButton(KPasswordDialog)
        self.anonymousRadioButton.setObjectName("anonymousRadioButton")
        self.vBoxLayout.addWidget(self.anonymousRadioButton)
        self.usePasswordButton = QtWidgets.QRadioButton(KPasswordDialog)
        self.usePasswordButton.setChecked(True)
        self.usePasswordButton.setObjectName("usePasswordButton")
        self.vBoxLayout.addWidget(self.usePasswordButton)
        self.credentialsGroup = QtWidgets.QWidget(KPasswordDialog)
        self.credentialsGroup.setObjectName("credentialsGroup")
        self.formLayout = QtWidgets.QFormLayout(self.credentialsGroup)
        self.formLayout.setContentsMargins(1, 1, 1, 1)
        self.formLayout.setObjectName("formLayout")
        self.userNameLabel = QtWidgets.QLabel(self.credentialsGroup)
        self.userNameLabel.setObjectName("userNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.userNameLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.userEdit = QtWidgets.QLineEdit(self.credentialsGroup)
        self.userEdit.setClearButtonEnabled(True)
        self.userEdit.setObjectName("userEdit")
        self.horizontalLayout.addWidget(self.userEdit)
        self.userEditContextHelpButton = QtWidgets.QPushButton(self.credentialsGroup)
        self.userEditContextHelpButton.setText("")
        self.userEditContextHelpButton.setObjectName("userEditContextHelpButton")
        self.horizontalLayout.addWidget(self.userEditContextHelpButton)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.domainLabel = QtWidgets.QLabel(self.credentialsGroup)
        self.domainLabel.setObjectName("domainLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.domainLabel)
        self.domainEdit = QtWidgets.QLineEdit(self.credentialsGroup)
        self.domainEdit.setClearButtonEnabled(True)
        self.domainEdit.setObjectName("domainEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.domainEdit)
        self.passwordLabel = QtWidgets.QLabel(self.credentialsGroup)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passEdit = KPasswordLineEdit(self.credentialsGroup)
        self.passEdit.setProperty("clearButtonEnabled", True)
        self.passEdit.setObjectName("passEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.passEdit)
        self.keepCheckBox = QtWidgets.QCheckBox(self.credentialsGroup)
        self.keepCheckBox.setObjectName("keepCheckBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.keepCheckBox)
        self.vBoxLayout.addWidget(self.credentialsGroup)
        self.buttonBox = QtWidgets.QDialogButtonBox(KPasswordDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vBoxLayout.addWidget(self.buttonBox)

        self.retranslateUi(KPasswordDialog)
        self.buttonBox.accepted.connect(KPasswordDialog.accept) # type: ignore
        self.usePasswordButton.toggled['bool'].connect(self.credentialsGroup.setEnabled) # type: ignore
        self.buttonBox.rejected.connect(KPasswordDialog.reject) # type: ignore
        self.usePasswordButton.clicked.connect(self.credentialsGroup.setFocus) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(KPasswordDialog)
        KPasswordDialog.setTabOrder(self.anonymousRadioButton, self.usePasswordButton)
        KPasswordDialog.setTabOrder(self.usePasswordButton, self.userEdit)
        KPasswordDialog.setTabOrder(self.userEdit, self.domainEdit)
        KPasswordDialog.setTabOrder(self.domainEdit, self.passEdit)
        KPasswordDialog.setTabOrder(self.passEdit, self.keepCheckBox)

    def retranslateUi(self, KPasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        self.prompt.setText(_translate("KPasswordDialog", "Supply a username and password below."))
        self.anonymousRadioButton.setText(_translate("KPasswordDialog", "No password, use anonymous (or &guest) login", "@option:radio"))
        self.usePasswordButton.setText(_translate("KPasswordDialog", "Use this password:", "@option:radio"))
        self.userNameLabel.setText(_translate("KPasswordDialog", "Username:", "@label:textbox"))
        self.domainLabel.setText(_translate("KPasswordDialog", "Domain:", "@label:textbox"))
        self.passwordLabel.setText(_translate("KPasswordDialog", "Password:", "@label:textbox"))
        self.keepCheckBox.setText(_translate("KPasswordDialog", "Remember password", "@option:check"))
from kpasswordlineedit import KPasswordLineEdit
from ktitlewidget import KTitleWidget
