#!/bin/bash

set -e

#DEBHELPER#

home="/home/"

db_file="/.config/lingmo/Clock_database.db"
feedback="/.config/lingmo/url.conf"

for file in $(ls /home)
do
  db_file_path=${home}${file}${db_file}  
  feedback_path=${home}${file}${feedback}  
  if [  -f "$db_file_path" ]; then
 	rm "$db_file_path"
  fi
  if [  -f "$feedback_path" ]; then
 	rm "$feedback_path"
  fi
done
