# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/sonnet/src/ui/configui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SonnetConfigUI(object):
    def setupUi(self, SonnetConfigUI):
        SonnetConfigUI.setObjectName("SonnetConfigUI")
        SonnetConfigUI.resize(700, 833)
        self.gridLayout = QtWidgets.QGridLayout(SonnetConfigUI)
        self.gridLayout.setObjectName("gridLayout")
        self.nobackendfound = QtWidgets.QLabel(SonnetConfigUI)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.nobackendfound.setFont(font)
        self.nobackendfound.setAlignment(QtCore.Qt.AlignCenter)
        self.nobackendfound.setObjectName("nobackendfound")
        self.gridLayout.addWidget(self.nobackendfound, 0, 0, 1, 2)
        self.textLabel1 = QtWidgets.QLabel(SonnetConfigUI)
        self.textLabel1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel1.setObjectName("textLabel1")
        self.gridLayout.addWidget(self.textLabel1, 1, 0, 1, 1)
