# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/sonnet/src/ui/sonnetui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SonnetUi(object):
    def setupUi(self, SonnetUi):
        SonnetUi.setObjectName("SonnetUi")
        SonnetUi.resize(481, 311)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SonnetUi.sizePolicy().hasHeightForWidth())
        SonnetUi.setSizePolicy(sizePolicy)
        SonnetUi.setMinimumSize(QtCore.QSize(430, 300))
        self.gridlayout = QtWidgets.QGridLayout(SonnetUi)
        self.gridlayout.setContentsMargins(0, 0, 0, 0)
        self.gridlayout.setObjectName("gridlayout")
        self.textLabel2 = QtWidgets.QLabel(SonnetUi)
        self.textLabel2.setObjectName("textLabel2")
        self.gridlayout.addWidget(self.textLabel2, 1, 0, 1, 2)
        self.m_unknownWord = QtWidgets.QLabel(SonnetUi)
        self.m_unknownWord.setObjectName("m_unknownWord")
        self.gridlayout.addWidget(self.m_unknownWord, 1, 2, 1, 1)
        self.textLabel5 = QtWidgets.QLabel(SonnetUi)
        self.textLabel5.setObjectName("textLabel5")
        self.gridlayout.addWidget(self.textLabel5, 4, 0, 1, 1)
        self.m_contextLabel = QtWidgets.QLabel(SonnetUi)
        self.m_contextLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.m_contextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.m_contextLabel.setObjectName("m_contextLabel")
        self.gridlayout.addWidget(self.m_contextLabel, 0, 0, 1, 6)
        self.m_addBtn = QtWidgets.QPushButton(SonnetUi)
        self.m_addBtn.setObjectName("m_addBtn")
        self.gridlayout.addWidget(self.m_addBtn, 1, 4, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(74, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 1, 3, 1, 1)
        self.m_suggestions = QtWidgets.QListView(SonnetUi)
        self.m_suggestions.setResizeMode(QtWidgets.QListView.Adjust)
        self.m_suggestions.setObjectName("m_suggestions")
        self.gridlayout.addWidget(self.m_suggestions, 3, 0, 1, 5)
        self.textLabel4 = QtWidgets.QLabel(SonnetUi)
        self.textLabel4.setObjectName("textLabel4")
        self.gridlayout.addWidget(self.textLabel4, 2, 0, 1, 2)
        self.m_replacement = QtWidgets.QLineEdit(SonnetUi)
        self.m_replacement.setObjectName("m_replacement")
        self.gridlayout.addWidget(self.m_replacement, 2, 2, 1, 3)
