# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/kdeplasma-addons/runners/characters/charrunner_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CharacterRunnerConfigUi(object):
    def setupUi(self, CharacterRunnerConfigUi):
        CharacterRunnerConfigUi.setObjectName("CharacterRunnerConfigUi")
        CharacterRunnerConfigUi.resize(308, 252)
        self.verticalLayout = QtWidgets.QVBoxLayout(CharacterRunnerConfigUi)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main = QtWidgets.QGroupBox(CharacterRunnerConfigUi)
        self.main.setObjectName("main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_trigger = QtWidgets.QHBoxLayout()
        self.layout_trigger.setObjectName("layout_trigger")
        self.label_trigger = QtWidgets.QLabel(self.main)
        self.label_trigger.setObjectName("label_trigger")
        self.layout_trigger.addWidget(self.label_trigger)
        self.edit_trigger = QtWidgets.QLineEdit(self.main)
        self.edit_trigger.setClearButtonEnabled(True)
        self.edit_trigger.setObjectName("edit_trigger")
        self.layout_trigger.addWidget(self.edit_trigger)
        self.verticalLayout_2.addLayout(self.layout_trigger)
        self.layout_shortcut = QtWidgets.QHBoxLayout()
        self.layout_shortcut.setObjectName("layout_shortcut")
        self.label_alias = QtWidgets.QLabel(self.main)
        self.label_alias.setObjectName("label_alias")
        self.layout_shortcut.addWidget(self.label_alias)
        self.edit_alias = QtWidgets.QLineEdit(self.main)
        self.edit_alias.setText("")
        self.edit_alias.setObjectName("edit_alias")
        self.layout_shortcut.addWidget(self.edit_alias)
        self.label_hex = QtWidgets.QLabel(self.main)
        self.label_hex.setObjectName("label_hex")
        self.layout_shortcut.addWidget(self.label_hex)
        self.edit_hex = QtWidgets.QLineEdit(self.main)
        self.edit_hex.setText("")
        self.edit_hex.setObjectName("edit_hex")
        self.layout_shortcut.addWidget(self.edit_hex)
        self.verticalLayout_2.addLayout(self.layout_shortcut)
        self.layout_list = QtWidgets.QHBoxLayout()
        self.layout_list.setObjectName("layout_list")
        self.list = QtWidgets.QTreeWidget(self.main)
        self.list.setColumnCount(2)
        self.list.setObjectName("list")
        self.list.header().setDefaultSectionSize(75)
        self.layout_list.addWidget(self.list)
        self.layout_Itemactions = QtWidgets.QVBoxLayout()
        self.layout_Itemactions.setObjectName("layout_Itemactions")
        self.addItem = QtWidgets.QPushButton(self.main)
        self.addItem.setEnabled(False)
        self.addItem.setObjectName("addItem")
        self.layout_Itemactions.addWidget(self.addItem)
        self.deleteItem = QtWidgets.QPushButton(self.main)
        self.deleteItem.setEnabled(False)
        self.deleteItem.setObjectName("deleteItem")
        self.layout_Itemactions.addWidget(self.deleteItem)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_Itemactions.addItem(spacerItem)
        self.layout_list.addLayout(self.layout_Itemactions)
        self.verticalLayout_2.addLayout(self.layout_list)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.main)
        self.label_trigger.setBuddy(self.edit_trigger)

        self.retranslateUi(CharacterRunnerConfigUi)
        QtCore.QMetaObject.connectSlotsByName(CharacterRunnerConfigUi)

    def retranslateUi(self, CharacterRunnerConfigUi):
        _translate = QtCore.QCoreApplication.translate
        self.main.setTitle(_translate("CharacterRunnerConfigUi", "Character Runner Config"))
        self.label_trigger.setText(_translate("CharacterRunnerConfigUi", "&Trigger word:"))
        self.label_alias.setText(_translate("CharacterRunnerConfigUi", "Alias:"))
        self.label_hex.setText(_translate("CharacterRunnerConfigUi", "Hex code:"))
        self.list.headerItem().setText(0, _translate("CharacterRunnerConfigUi", "Alias"))
        self.list.headerItem().setText(1, _translate("CharacterRunnerConfigUi", "Code"))
        self.addItem.setText(_translate("CharacterRunnerConfigUi", "Add Item"))
        self.deleteItem.setText(_translate("CharacterRunnerConfigUi", "Delete Item"))
