target:
 backup_list: # v23替代v20的文件目录，需要进行提交的目录和文件
      - "/boot"
      - "/usr"
      - "/var"
      - "/etc"
 hold_list: # v23中保留v20的文件目录，不需要进行提交的目录和文件
      - "/boot/efi"
      - "/usr/lib/dpkg-db"
      - "/var/spool"
      - "/var/login.defs"
      - "/var/lib/AccountsService/users"
      - "/var/lib/AccountsService/lingmo"
      - "/var/lib/lingmo/developer-mode"
      - "/var/lib/lingmo-boot-kit/version.data"
      - "/var/cache/lingmo-system-upgrade/migrate.list"
      - "/etc/fstab"
      - "/etc/lingmo-upgrade-manager"
 after_run: "/usr/bin/lingmo-system-upgrade-tool"
 plymouth_theme: "lingmo-upgrade"
