.TH "LIBKYDIAGNOSTICS" 3 "Fri Sep 22 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libkydiagnostics \- 上传埋点数据  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBkdk_buried_point\fP (char *appName, char *messageType, \fBKBuriedPoint\fP *data, int length)"
.br
.RI "上传埋点数据 "
.in -1c
.SH DATA STRUCTURES

Structure \fBKBuriedPoint\fR is an array of buried data:

\fBtypedef struct {
.br
    const char *key;
    const char *value;
.br
} KBuriedPoint;\fP

There are other members not documented here, which are only meant for
libkydiagnostics internal use.
.SH "Detailed Description"
.PP 
上传埋点数据 
.SH "CONFORMING TO"
These functions are as per the withdrawn POSIX.1e draft specification.
The following functions are Linux extensions:
.BR kdk_buried_point ().
.SH "SEE ALSO"
.BR kdk_buried_point (3).

.SH "Author"
.PP 
Generated automatically by Doxygen for libkydiagnostics.h from the source code\&.
