# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/kconfigwidgets/tests/krecentfilesactiontest.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(434, 201)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbAddUrl = QtWidgets.QPushButton(self.centralwidget)
        self.pbAddUrl.setObjectName("pbAddUrl")
        self.horizontalLayout.addWidget(self.pbAddUrl)
        self.lineEditUrl = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditUrl.setObjectName("lineEditUrl")
        self.horizontalLayout.addWidget(self.lineEditUrl)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbLoadEntries = QtWidgets.QPushButton(self.centralwidget)
        self.pbLoadEntries.setObjectName("pbLoadEntries")
        self.horizontalLayout_3.addWidget(self.pbLoadEntries)
        self.pbSaveEntries = QtWidgets.QPushButton(self.centralwidget)
        self.pbSaveEntries.setObjectName("pbSaveEntries")
        self.horizontalLayout_3.addWidget(self.pbSaveEntries)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        self.label1.setObjectName("label1")
        self.horizontalLayout_2.addWidget(self.label1)
        self.labelOutputAvailable = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOutputAvailable.sizePolicy().hasHeightForWidth())
        self.labelOutputAvailable.setSizePolicy(sizePolicy)
        self.labelOutputAvailable.setObjectName("labelOutputAvailable")
        self.horizontalLayout_2.addWidget(self.labelOutputAvailable)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 434, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KRecentFilesAction Test"))
        self.label.setText(_translate("MainWindow", "Look in the File menu to use the Open Recent menu"))
        self.pbAddUrl.setText(_translate("MainWindow", "Add URL"))
        self.lineEditUrl.setText(_translate("MainWindow", "~/tmp/test1.txt"))
        self.label_3.setText(_translate("MainWindow", "Add URL to recent file list"))
        self.label_2.setText(_translate("MainWindow", "Note that nonexisting entries will not be restored."))
        self.pbLoadEntries.setText(_translate("MainWindow", "LoadEntries"))
        self.pbSaveEntries.setText(_translate("MainWindow", "SaveEntries"))
        self.label1.setText(_translate("MainWindow", "New console output:"))
        self.labelOutputAvailable.setText(_translate("MainWindow", "A"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
