[Desktop Entry]
Exec=@CMAKE_INSTALL_PREFIX@/bin/lingmoshell
X-DBUS-StartupType=Unique
Name=Lingmo Desktop Workspace
Name[ar]=مساحة عمل سطح مكتب بلازما
Name[az]=Lingmo İş masası Mühiti
Name[be]=Працоўныя прасторы Lingmo
Name[bg]=Работен плот на Lingmo
Name[bs]=Radni prostor plazma radne površi
Name[ca]=Espai de treball de l'escriptori Lingmo
Name[ca@valencia]=Espai de treball de l'escriptori Lingmo
Name[cs]=Pracovní plocha Lingmo
Name[da]=Lingmo Desktop Workspace
Name[de]=Lingmo-Arbeitsflächenbereich
Name[el]=Χώρος επιφάνειας εργασίας Lingmo
Name[en_GB]=Lingmo Desktop Workspace
Name[eo]=Lingmo Fenestrila Laborspaco
Name[es]=Espacio de trabajo del escritorio Lingmo
Name[et]=Lingmo töölaua töötsoon
Name[eu]=Lingmo mahaigainaren lanerako guneak
Name[fi]=Lingmo-työpöytä
Name[fr]=Espace de travail Lingmo
Name[ga]=Spás Oibre Deisce Lingmo
Name[gl]=Espazo de traballo do escritorio Lingmo
Name[he]=מרחב שולחן העבודה פלזמה
Name[hi]=प्लाज़्मा डेस्कटॉप कार्यक्षेत्र
Name[hr]=Lingmo radno okruženje
Name[hsb]=Lingmo-dźěłowy rum z dźěłowym powjerchom
Name[hu]=Lingmo asztali munkaterület
Name[ia]=Spatio de labor de scriptorio de Lingmo
Name[id]=Ruangkerja Desktop Lingmo
Name[is]=Vinnusvæði Lingmo
Name[it]=Spazio di lavoro del desktop di Lingmo
Name[ja]=Lingmo デスクトップワークスペース
Name[ka]=Lingmo Desktop Workspace
Name[ko]=Lingmo 데스크톱 작업 공간
Name[lt]=Lingmo darbalaukio darbo sritis
Name[lv]=„Lingmo“ darbvirsma
Name[ml]=പ്ലാസ്മ ഡെസ്ക്ടോപ്പ് പണിയിടം
Name[nb]=Arbeidsrom for Lingmo skrivebord
Name[nds]=Lingmo-Schriefdischarbeitrebeet
Name[nl]=Lingmo Bureaublad Werkplek
Name[nn]=Arbeidsområde for Lingmo-skrivebord
Name[pa]=ਪਲਾਜ਼ਮਾ ਡੈਸਕਟਾਪ ਵਰਕਸਪੇਸ
Name[pl]=Przestrzeń Pracy Pulpitu Plazmy
Name[pt]=Área de Trabalho do Lingmo
Name[pt_BR]=Espaço de Trabalho Lingmo
Name[ro]=Spațiu de lucru al biroului Lingmo
Name[ru]=Рабочая среда Lingmo
Name[sa]=प्लाज्मा कार्यमुखम् कार्यक्षेत्र
Name[sk]=Pracovná plocha Lingmo
Name[sl]=Delovni prostor Lingmo Desktop
Name[sr]=Плазма, радни простор површи
Name[sr@ijekavian]=Плазма, радни простор површи
Name[sr@ijekavianlatin]=Lingmo, radni prostor površi
Name[sr@latin]=Lingmo, radni prostor površi
Name[sv]=Lingmo arbetsområde för skrivbordet
Name[ta]=பிளாஸ்மா பணிமேடை
Name[tg]=Фазои мизи кории Плазма
Name[tr]=Lingmo Masaüstü Çalışma Alanı
Name[uk]=Робочий простір Плазми для комп’ютерів
Name[vi]=Không gian bàn làm việc Lingmo
Name[x-test]=xxLingmo Desktop Workspacexx
Name[zh_CN]=Lingmo 桌面工作空间
Name[zh_TW]=Lingmo 桌面工作空間
Type=Application
StartupNotify=false
X-DBUS-ServiceName=org.kde.lingmoshell
OnlyShowIn=KDE;
X-KDE-autostart-phase=0
Icon=lingmoshell
NoDisplay=true
X-systemd-skip=true

X-KDE-Wayland-Interfaces=org_kde_lingmo_window_management,org_kde_kwin_keystate,zkde_screencast_unstable_v1,org_kde_lingmo_activation_feedback
X-KDE-DBUS-Restricted-Interfaces=org.kde.KWin.ScreenShot2
