#!/bin/bash
freezer_controller_dir_v1=/sys/fs/cgroup/freezer
if [ -d $freezer_controller_dir_v1 ]; then
    for freezer_sub_dir in `ls $freezer_controller_dir_v1/user.slice`; do
        user_id_slice_dir_name=$(basename "$freezer_sub_dir")
        if [[ "$user_id_slice_dir_name" =~ ^user-[0-9]+\.slice$ ]]; then
            for user_id_slice_sub_dir in `ls $freezer_controller_dir_v1/user.slice/$user_id_slice_dir_name`; do
                user_id_service_dir_name=$(basename "$user_id_slice_sub_dir")
                if [[ "$user_id_service_dir_name" =~ ^user@[0-9]+\.service$ ]]; then
                    echo THAWED > $freezer_controller_dir_v1/user.slice/$user_id_slice_dir_name/$user_id_service_dir_name/app.slice/app-cached.slice/freezer.state
                fi
            done
        fi
    done
fi
