.TH "lingmosdk.Runinfo" 3 "Thu Sep 21 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lingmosdk.Runinfo \- 获取瞬时信息 主要用来获取瞬时网速，cpu温度、磁盘温度、磁盘转速  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlingmosdk\&.Base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBgetNetSpeed\fP (self, netcard)"
.br
.RI "获取瞬时网速信息 "
.ti -1c
.RI "def \fBgetDiskRate\fP (self, disk_path)"
.br
.RI "获取磁盘转速 "
.ti -1c
.RI "def \fBgetCpuTemperature\fP (self)"
.br
.RI "获取CPU温度 "
.ti -1c
.RI "def \fBgetDiskTemperature\fP (self, disk_path)"
.br
.RI "获取磁盘温度 "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
获取瞬时信息 主要用来获取瞬时网速，cpu温度、磁盘温度、磁盘转速 


.SH "Member Function Documentation"
.PP 
.SS "def lingmosdk\&.Runinfo\&.getCpuTemperature ( self)"

.PP
获取CPU温度 
.PP
\fBReturns\fP
.RS 4
CPU温度 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Runinfo\&.getDiskRate ( self,  disk_path)"

.PP
获取磁盘转速 
.PP
\fBParameters\fP
.RS 4
\fIdisk_path\fP 磁盘名称，应当是例如/dev/sda这种绝对路径 
.RE
.PP
\fBReturns\fP
.RS 4
磁盘转速 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Runinfo\&.getDiskTemperature ( self,  disk_path)"

.PP
获取磁盘温度 
.PP
\fBParameters\fP
.RS 4
\fIdisk_path\fP 磁盘名称，应当是例如/dev/sda这种绝对路径 
.RE
.PP
\fBReturns\fP
.RS 4
磁盘温度 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Runinfo\&.getNetSpeed ( self,  netcard)"

.PP
获取瞬时网速信息 
.PP
\fBParameters\fP
.RS 4
\fInetcard\fP 网卡名称，如eno1 
.RE
.PP
\fBReturns\fP
.RS 4
瞬时网速 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lingmosdk.py from the source code\&.
