.TH "lingmosdk.Peripheralsenum" 3 "Thu Sep 21 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lingmosdk.Peripheralsenum \- 获取usb设备信息dbus信号类 主要用来获取usb设备的名称、类型、pid、vid、序列号、路径信息  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlingmosdk\&.Base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBgetAllUsbInfo\fP (self)"
.br
.RI "获取外接usb设备信息 "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
获取usb设备信息dbus信号类 主要用来获取usb设备的名称、类型、pid、vid、序列号、路径信息 


.SH "Member Function Documentation"
.PP 
.SS "def lingmosdk\&.Peripheralsenum\&.getAllUsbInfo ( self)"

.PP
获取外接usb设备信息 
.PP
\fBReturns\fP
.RS 4
QStringList usb设备名称、类型、pid、vid、序列号、路径信息列表 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lingmosdk.py from the source code\&.
