.TH "lingmosdk.Packageinfo" 3 "Thu Sep 21 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lingmosdk.Packageinfo \- 获取包列表信息 主要用来获取系统中所有包列表、获取系统中指定包的版本号、检测指定包名的软件包是否正确安装  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlingmosdk\&.Base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBgetPackageList\fP (self)"
.br
.RI "获取系统中所有包列表 "
.ti -1c
.RI "def \fBgetPackageVersion\fP (self, package_name)"
.br
.RI "获取系统中指定包的版本号 "
.ti -1c
.RI "def \fBgetPackageInstalled\fP (self, package_name, version=None)"
.br
.RI "检测指定包名的软件包是否正确安装 "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
获取包列表信息 主要用来获取系统中所有包列表、获取系统中指定包的版本号、检测指定包名的软件包是否正确安装 


.SH "Member Function Documentation"
.PP 
.SS "def lingmosdk\&.Packageinfo\&.getPackageInstalled ( self,  package_name,  version = \fCNone\fP)"

.PP
检测指定包名的软件包是否正确安装 
.PP
\fBParameters\fP
.RS 4
\fIpackage_name\fP 包名 
.br
\fIversion\fP 版本号，大部分情况下为NULL，预留为snap做准备 
.RE
.PP
\fBReturns\fP
.RS 4
成功返回0，失败返回错误码 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Packageinfo\&.getPackageList ( self)"

.PP
获取系统中所有包列表 
.PP
\fBReturns\fP
.RS 4
系统中所有包列表 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Packageinfo\&.getPackageVersion ( self,  package_name)"

.PP
获取系统中指定包的版本号 
.PP
\fBParameters\fP
.RS 4
\fIpackage_name\fP 软件包名 
.RE
.PP
\fBReturns\fP
.RS 4
版本号 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lingmosdk.py from the source code\&.
