.TH "lingmosdk.Process" 3 "Thu Sep 21 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lingmosdk.Process \- 获取某一进程的瞬时详细信息 主要用来获取某一进程的CPU使用率、获取某一进程的内存占用率、获取某一进程的进程状态、获取某一进程的端口号占用、 获取某一进程的启动时间、获取某一进程的运行时间、获取某一进程的cpu时间、获取某一进程的Command、获取某一进程的属主、 获取某一进程的信息、获取进程所有信息  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlingmosdk\&.Base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBgetProcInfoCpuUsage\fP (self, pid)"
.br
.RI "获取某一进程的CPU使用率 "
.ti -1c
.RI "def \fBgetProcInfoMemUsage\fP (self, pid)"
.br
.RI "获取某一进程的内存占用率 "
.ti -1c
.RI "def \fBgetProcInfoStatus\fP (self, pid)"
.br
.RI "获取某一进程的进程状态 "
.ti -1c
.RI "def \fBgetProcInfoPort\fP (self, pid)"
.br
.RI "获取某一进程的端口号占用 "
.ti -1c
.RI "def \fBgetProcInfoStartTime\fP (self, pid)"
.br
.RI "获取某一进程的启动时间 "
.ti -1c
.RI "def \fBgetProcInfoRunningTime\fP (self, pid)"
.br
.RI "获取某一进程的运行时间 "
.ti -1c
.RI "def \fBgetProcInfoCpuTime\fP (self, pid)"
.br
.RI "获取某一进程的cpu时间 "
.ti -1c
.RI "def \fBgetProcInfoCmd\fP (self, pid)"
.br
.RI "获取某一进程的Command "
.ti -1c
.RI "def \fBgetProcInfoUser\fP (self, pid)"
.br
.RI "获取某一进程的属主 "
.ti -1c
.RI "def \fBgetProcInfo\fP (self, process_name)"
.br
.RI "获取某一进程的信息 "
.ti -1c
.RI "def \fBgetAllProcInfo\fP (self)"
.br
.RI "获取进程所有信息 "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
获取某一进程的瞬时详细信息 主要用来获取某一进程的CPU使用率、获取某一进程的内存占用率、获取某一进程的进程状态、获取某一进程的端口号占用、 获取某一进程的启动时间、获取某一进程的运行时间、获取某一进程的cpu时间、获取某一进程的Command、获取某一进程的属主、 获取某一进程的信息、获取进程所有信息 


.SH "Member Function Documentation"
.PP 
.SS "def lingmosdk\&.Process\&.getAllProcInfo ( self)"

.PP
获取进程所有信息 
.PP
\fBReturns\fP
.RS 4
所有进程的CPU使用率、内存占用率、状态、端口号占用、启动时间、运行时间、cpu时间、Command、属主信息列表 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Process\&.getProcInfo ( self,  process_name)"

.PP
获取某一进程的信息 
.PP
\fBParameters\fP
.RS 4
\fIprocess_name\fP 进程名 
.RE
.PP
\fBReturns\fP
.RS 4
某一进程CPU使用率、内存占用率、状态、端口号占用、启动时间、运行时间、cpu时间、Command、属主信息列表 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Process\&.getProcInfoCmd ( self,  pid)"

.PP
获取某一进程的Command 
.PP
\fBParameters\fP
.RS 4
\fIpid\fP 进程号 
.RE
.PP
\fBReturns\fP
.RS 4
进程的Command 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Process\&.getProcInfoCpuTime ( self,  pid)"

.PP
获取某一进程的cpu时间 
.PP
\fBParameters\fP
.RS 4
\fIpid\fP 进程号 
.RE
.PP
\fBReturns\fP
.RS 4
进程的cpu时间 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Process\&.getProcInfoCpuUsage ( self,  pid)"

.PP
获取某一进程的CPU使用率 
.PP
\fBParameters\fP
.RS 4
\fIpid\fP 进程号 
.RE
.PP
\fBReturns\fP
.RS 4
进程的CPU使用率 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Process\&.getProcInfoMemUsage ( self,  pid)"

.PP
获取某一进程的内存占用率 
.PP
\fBParameters\fP
.RS 4
\fIpid\fP 进程号 
.RE
.PP
\fBReturns\fP
.RS 4
进程的内存占用率 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Process\&.getProcInfoPort ( self,  pid)"

.PP
获取某一进程的端口号占用 
.PP
\fBParameters\fP
.RS 4
\fIpid\fP 进程号 
.RE
.PP
\fBReturns\fP
.RS 4
进程使用的端口号 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Process\&.getProcInfoRunningTime ( self,  pid)"

.PP
获取某一进程的运行时间 
.PP
\fBParameters\fP
.RS 4
\fIpid\fP 进程号 
.RE
.PP
\fBReturns\fP
.RS 4
进程的运行时间 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Process\&.getProcInfoStartTime ( self,  pid)"

.PP
获取某一进程的启动时间 
.PP
\fBParameters\fP
.RS 4
\fIpid\fP 进程号 
.RE
.PP
\fBReturns\fP
.RS 4
进程的启动时间 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Process\&.getProcInfoStatus ( self,  pid)"

.PP
获取某一进程的进程状态 
.PP
\fBParameters\fP
.RS 4
\fIpid\fP 进程号 
.RE
.PP
\fBReturns\fP
.RS 4
进程状态 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Process\&.getProcInfoUser ( self,  pid)"

.PP
获取某一进程的属主 
.PP
\fBParameters\fP
.RS 4
\fIpid\fP 进程号 
.RE
.PP
\fBReturns\fP
.RS 4
进程的属主 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lingmosdk.py from the source code\&.
