.TH "lingmosdk.Gps" 3 "Thu Sep 21 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lingmosdk.Gps \- 获取地址信息 主要用来获取本地地址信息  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlingmosdk\&.Base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBgetGPSInfo\fP (self)"
.br
.RI "获取本地地址信息 "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
获取地址信息 主要用来获取本地地址信息 


.SH "Member Function Documentation"
.PP 
.SS "def lingmosdk\&.Gps\&.getGPSInfo ( self)"

.PP
获取本地地址信息 
.PP
\fBReturns\fP
.RS 4
json格式的地址信息 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lingmosdk.py from the source code\&.
