.TH "lingmosdk.Net" 3 "Thu Sep 21 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lingmosdk.Net \- 获取网络信息 主要用来获取指定网络端口的状态、区间端口状态、网关信息、防火墙信息  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlingmosdk\&.Base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBgetPortState\fP (self, port)"
.br
.RI "获取指定网络端口的状态 "
.ti -1c
.RI "def \fBgetMultiplePortStat\fP (self, start_port, end_port)"
.br
.RI "获取区间端口状态 "
.ti -1c
.RI "def \fBgetGatewayInfo\fP (self)"
.br
.RI "获取网关信息 "
.ti -1c
.RI "def \fBgetFirewallState\fP (self)"
.br
.RI "获取防火墙信息 "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
获取网络信息 主要用来获取指定网络端口的状态、区间端口状态、网关信息、防火墙信息 


.SH "Member Function Documentation"
.PP 
.SS "def lingmosdk\&.Net\&.getFirewallState ( self)"

.PP
获取防火墙信息 
.PP
\fBReturns\fP
.RS 4
防火墙信息列表 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Net\&.getGatewayInfo ( self)"

.PP
获取网关信息 
.PP
\fBReturns\fP
.RS 4
网关信息网卡名和地址列表 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Net\&.getMultiplePortStat ( self,  start_port,  end_port)"

.PP
获取区间端口状态 
.PP
\fBParameters\fP
.RS 4
\fIstart_port\fP 开始端口 
.br
\fIend_port\fP 结束端口 
.RE
.PP
\fBReturns\fP
.RS 4
区间端口状态列表 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Net\&.getPortState ( self,  port)"

.PP
获取指定网络端口的状态 
.PP
\fBParameters\fP
.RS 4
\fIport\fP 端口号 
.RE
.PP
\fBReturns\fP
.RS 4
端口状态 TCP_ESTABLISHED:0x1 TCP_SYN_SENT:0x2 TCP_SYN_RECV:0x3 TCP_FIN_WAIT1:0x4 TCP_FIN_WAIT2:0x5 TCP_TIME_WAIT:0x6 TCP_CLOSE:0x7 TCP_CLOSE_WAIT:0x8 TCP_LAST_ACL:0x9 TCP_LISTEN:0xa TCP_CLOSING:0xb 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lingmosdk.py from the source code\&.
