.TH "lingmosdk.GetSysLegalResolution" 3 "Thu Sep 21 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lingmosdk.GetSysLegalResolution \- 获取屏幕分辨率信息 主要用来获取系统当前显示屏幕,分辨率,系统支持分辨率  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlingmosdk\&.SessionBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBgetSysLegalResolution\fP (self)"
.br
.RI "获取系统当前显示屏幕,分辨率,系统支持分辨率 "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
获取屏幕分辨率信息 主要用来获取系统当前显示屏幕,分辨率,系统支持分辨率 


.SH "Member Function Documentation"
.PP 
.SS "def lingmosdk\&.GetSysLegalResolution\&.getSysLegalResolution ( self)"

.PP
获取系统当前显示屏幕,分辨率,系统支持分辨率 
.PP
\fBReturns\fP
.RS 4
当前显示屏幕,分辨率,系统支持分辨率信息列表 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lingmosdk.py from the source code\&.
