.TH "lingmosdk.Print" 3 "Thu Sep 21 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lingmosdk.Print \- 获取打印信息 主要用来生成本地的所有打印机(包含可用打印机和不可用打印机)、获取本地的所有可用打印机(打印机处于idle状态)、 设置打印参数，每次设置会清除之前设置打印参数,这个设置是全局设置，设置了之后所有打印机都会用这个参数进行打印、 下载网络文件、打印本地文件、清除某个打印机的所有打印队列、获取当前打印机状态(状态不是实时更新)、 获取当前打印任务状态（发送打印任务之后下需要等待一会再获取状态,状态不是实时更新）、获取url内的文件名  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlingmosdk\&.Base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBgetPrinterList\fP (self)"
.br
.RI "获取本地的所有打印机(包含可用打印机和不可用打印机) "
.ti -1c
.RI "def \fBgetPrinterAvailableList\fP (self)"
.br
.RI "获取本地的所有可用打印机(打印机处于idle状态) "
.ti -1c
.RI "def \fBsetPrinterOptions\fP (self, num, paper_type, cups, option)"
.br
.RI "设置打印参数，每次设置会清除之前设置打印参数,这个设置是全局设置，设置了之后所有打印机都会用这个参数进行打印 "
.ti -1c
.RI "def \fBgetPrinterPrintLocalFile\fP (self, print_name, file_path)"
.br
.RI "打印本地文件 "
.ti -1c
.RI "def \fBgetPrinterCancelAllJobs\fP (self, print_name)"
.br
.RI "清除某个打印机的所有打印队列 "
.ti -1c
.RI "def \fBgetPrinterStatus\fP (self, print_name)"
.br
.RI "获取当前打印机状态(状态不是实时更新) "
.ti -1c
.RI "def \fBgetPrinterFilename\fP (self, url)"
.br
.RI "获取url内的文件名 "
.ti -1c
.RI "def \fBgetPrinterJobStatus\fP (self, print_name, jobid)"
.br
.RI "获取当前打印任务状态（发送打印任务之后下需要等待一会再获取状态,状态不是实时更新） "
.ti -1c
.RI "def \fBgetPrinterDownloadRemoteFile\fP (self, url, path)"
.br
.RI "下载网络文件 "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
获取打印信息 主要用来生成本地的所有打印机(包含可用打印机和不可用打印机)、获取本地的所有可用打印机(打印机处于idle状态)、 设置打印参数，每次设置会清除之前设置打印参数,这个设置是全局设置，设置了之后所有打印机都会用这个参数进行打印、 下载网络文件、打印本地文件、清除某个打印机的所有打印队列、获取当前打印机状态(状态不是实时更新)、 获取当前打印任务状态（发送打印任务之后下需要等待一会再获取状态,状态不是实时更新）、获取url内的文件名 


.SH "Member Function Documentation"
.PP 
.SS "def lingmosdk\&.Print\&.getPrinterAvailableList ( self)"

.PP
获取本地的所有可用打印机(打印机处于idle状态) 
.PP
\fBReturns\fP
.RS 4
本地的所有可用打印机名称列表 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Print\&.getPrinterCancelAllJobs ( self,  print_name)"

.PP
清除某个打印机的所有打印队列 
.PP
\fBParameters\fP
.RS 4
\fIprint_name\fP 打印机名 
.RE
.PP
\fBReturns\fP
.RS 4
成功返回0,失败返回-1 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Print\&.getPrinterDownloadRemoteFile ( self,  url,  path)"

.PP
下载网络文件 
.PP
\fBParameters\fP
.RS 4
\fIurl\fP 要打印的url 
.br
\fIpath\fP 保存的文件路径
.RE
.PP
\fBReturns\fP
.RS 4
打印作业的id 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Print\&.getPrinterFilename ( self,  url)"

.PP
获取url内的文件名 
.PP
\fBParameters\fP
.RS 4
\fIurl\fP 路径 
.RE
.PP
\fBReturns\fP
.RS 4
解析出来的函数名 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Print\&.getPrinterJobStatus ( self,  print_name,  jobid)"

.PP
获取当前打印任务状态（发送打印任务之后下需要等待一会再获取状态,状态不是实时更新） 
.PP
\fBParameters\fP
.RS 4
\fIprint_name\fP 打印机名 
.br
\fIjobid\fP 打印作业的id 
.RE
.PP
\fBReturns\fP
.RS 4
状态码 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Print\&.getPrinterList ( self)"

.PP
获取本地的所有打印机(包含可用打印机和不可用打印机) 
.PP
\fBReturns\fP
.RS 4
地的所有打印机名称列表 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Print\&.getPrinterPrintLocalFile ( self,  print_name,  file_path)"

.PP
打印本地文件 
.PP
\fBParameters\fP
.RS 4
\fIprint_name\fP 打印机名 
.br
\fIfile_path\fP 文件绝对路径
.RE
.PP
\fBReturns\fP
.RS 4
打印作业的id
.RE
.PP
@notice 虽然支持多种格式的打印，但是打印除pdf之外的格式打印的效果都不够好，建议打印pdf格式的文件 打印机处于stop状态函数返回0 格式不对的文件可以成功创建打印任务，但是打印不出来。什么叫格式不对，举个例子，比如当前要打印日志文件a\&.log, 然后把a\&.log改名叫a\&.pdf,这个时候a\&.pdf就变成了格式不对的文件，打印不出来了 
.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Print\&.getPrinterStatus ( self,  print_name)"

.PP
获取当前打印机状态(状态不是实时更新) 
.PP
\fBParameters\fP
.RS 4
\fIprint_name\fP 打印机名 
.RE
.PP
\fBReturns\fP
.RS 4
状态码 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Print\&.setPrinterOptions ( self,  num,  paper_type,  cups,  option)"

.PP
设置打印参数，每次设置会清除之前设置打印参数,这个设置是全局设置，设置了之后所有打印机都会用这个参数进行打印 
.PP
\fBParameters\fP
.RS 4
\fInum\fP cups属性，一张纸打印几页，如2 4等 
.br
\fIpaper_type\fP cups属性，纸张类型，如A4 
.br
\fIcups\fP cups属性，如lrtb 
.br
\fIoption\fP cups属性，单面如one-sided，双面如two-sided-long-edge(长边翻转),two-sided-short-edge(短边翻转) 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lingmosdk.py from the source code\&.
