.TH "lingmosdk.Bios" 3 "Thu Sep 21 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lingmosdk.Bios \- 获取bios信息 主要用来获取bios的厂商和版本信息  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlingmosdk\&.Base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBgetBiosVendor\fP (self)"
.br
.RI "获取bios厂商 "
.ti -1c
.RI "def \fBgetBiosVersion\fP (self)"
.br
.RI "获取bios版本 "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
获取bios信息 主要用来获取bios的厂商和版本信息 


.SH "Member Function Documentation"
.PP 
.SS "def lingmosdk\&.Bios\&.getBiosVendor ( self)"

.PP
获取bios厂商 
.PP
\fBReturns\fP
.RS 4
厂商名 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Bios\&.getBiosVersion ( self)"

.PP
获取bios版本 
.PP
\fBReturns\fP
.RS 4
版本号 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lingmosdk.py from the source code\&.
