.TH "lingmosdk.Mainboard" 3 "Thu Sep 21 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lingmosdk.Mainboard \- 获取主板信息 主要用来获取主板型号、生产日期、序列号、厂商信息  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlingmosdk\&.Base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBgetMainboardName\fP (self)"
.br
.RI "获取主板型号 "
.ti -1c
.RI "def \fBgetMainboardDate\fP (self)"
.br
.RI "获取主板生产日期 "
.ti -1c
.RI "def \fBgetMainboardSerial\fP (self)"
.br
.RI "获取主板序列号 "
.ti -1c
.RI "def \fBgetMainboardVendor\fP (self)"
.br
.RI "获取主板厂商 "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
获取主板信息 主要用来获取主板型号、生产日期、序列号、厂商信息 


.SH "Member Function Documentation"
.PP 
.SS "def lingmosdk\&.Mainboard\&.getMainboardDate ( self)"

.PP
获取主板生产日期 
.PP
\fBReturns\fP
.RS 4
主板生产日期 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Mainboard\&.getMainboardName ( self)"

.PP
获取主板型号 
.PP
\fBReturns\fP
.RS 4
主板型号 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Mainboard\&.getMainboardSerial ( self)"

.PP
获取主板序列号 
.PP
\fBReturns\fP
.RS 4
主板序列号 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.
.SS "def lingmosdk\&.Mainboard\&.getMainboardVendor ( self)"

.PP
获取主板厂商 
.PP
\fBReturns\fP
.RS 4
主板厂商名 
.RE
.PP

.PP
References lingmosdk\&.SessionBase\&.interface, and lingmosdk\&.Base\&.interface\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lingmosdk.py from the source code\&.
