# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/bluedevil/src/wizard/pages/discover.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Discover(object):
    def setupUi(self, Discover):
        Discover.setObjectName("Discover")
        Discover.resize(571, 444)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Discover)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchField = QtWidgets.QLineEdit(Discover)
        self.searchField.setClearButtonEnabled(True)
        self.searchField.setObjectName("searchField")
        self.verticalLayout.addWidget(self.searchField)
        self.deviceView = QtWidgets.QListView(Discover)
        self.deviceView.setIconSize(QtCore.QSize(48, 48))
        self.deviceView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.deviceView.setObjectName("deviceView")
        self.verticalLayout.addWidget(self.deviceView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.busyIndicator = KBusyIndicatorWidget(Discover)
        self.busyIndicator.setObjectName("busyIndicator")
        self.horizontalLayout_2.addWidget(self.busyIndicator)
        spacerItem = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Discover)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.manualPin = QtWidgets.QCheckBox(Discover)
        self.manualPin.setChecked(False)
        self.manualPin.setObjectName("manualPin")
        self.horizontalLayout_2.addWidget(self.manualPin)
        self.pinText = QtWidgets.QLineEdit(Discover)
        self.pinText.setEnabled(False)
        self.pinText.setMinimumSize(QtCore.QSize(100, 0))
        self.pinText.setMaximumSize(QtCore.QSize(50, 40))
        self.pinText.setReadOnly(False)
        self.pinText.setObjectName("pinText")
        self.horizontalLayout_2.addWidget(self.pinText)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Discover)
        QtCore.QMetaObject.connectSlotsByName(Discover)

    def retranslateUi(self, Discover):
        _translate = QtCore.QCoreApplication.translate
        self.searchField.setPlaceholderText(_translate("Discover", "Search…"))
        self.label.setText(_translate("Discover", "Scanning…"))
        self.manualPin.setText(_translate("Discover", "Manual PIN:"))
        self.pinText.setPlaceholderText(_translate("Discover", "0000"))
from kbusyindicatorwidget import KBusyIndicatorWidget
