.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 Clay Stan <claystan97@gmail.com>,
.\"
.TH "DEEPIN-SCREENSAVER" "1" "April 2021" "deepin-screensaver deepin-screensaver" "User Commands"

.SH NAME
deepin-screensaver \- Deepin screensaver viewer and tools

.SH SYNOPSIS
.B deepin-screensaver
[\fI\,options\/\fR] [\fI\,name\/\fR]

.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-dbus\fR
Register DBus service.
.TP
\fB\-s\fR, \fB\-\-start\fR
Start screen saver.
.TP
\fB\-h\fR, \fB\-\-help\fR
Displays help on commandline options.
.TP
\fB\-v\fR, \fB\-\-version\fR
Displays version information.

.SH AUTHOR
.PP
.B deepin-screensaver
is written by linuxdeepin <https://github.com/linuxdeepin>.
.PP
This manual page was written by
.MT claystan97@\:gmail.com
Clay Stan
.ME
for the Debian Project (but may be used by others).
