# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/kuserfeedback/src/console/connectdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KUserFeedback::Console::ConnectDialog(object):
    def setupUi(self, KUserFeedback::Console::ConnectDialog):
        KUserFeedback::Console::ConnectDialog.setObjectName("KUserFeedback::Console::ConnectDialog")
        KUserFeedback::Console::ConnectDialog.resize(387, 298)
        self.verticalLayout = QtWidgets.QVBoxLayout(KUserFeedback::Console::ConnectDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(KUserFeedback::Console::ConnectDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(KUserFeedback::Console::ConnectDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.userName = QtWidgets.QLineEdit(KUserFeedback::Console::ConnectDialog)
        self.userName.setObjectName("userName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.userName)
        self.label_3 = QtWidgets.QLabel(KUserFeedback::Console::ConnectDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.password = QtWidgets.QLineEdit(KUserFeedback::Console::ConnectDialog)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.password)
        self.serverName = QtWidgets.QComboBox(KUserFeedback::Console::ConnectDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverName.sizePolicy().hasHeightForWidth())
        self.serverName.setSizePolicy(sizePolicy)
        self.serverName.setEditable(True)
        self.serverName.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.serverName.setObjectName("serverName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.serverName)
        self.label_4 = QtWidgets.QLabel(KUserFeedback::Console::ConnectDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.serverUrl = QtWidgets.QLineEdit(KUserFeedback::Console::ConnectDialog)
        self.serverUrl.setObjectName("serverUrl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.serverUrl)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(KUserFeedback::Console::ConnectDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label.setBuddy(self.serverName)
        self.label_2.setBuddy(self.userName)
        self.label_3.setBuddy(self.password)
        self.label_4.setBuddy(self.serverUrl)

        self.retranslateUi(KUserFeedback::Console::ConnectDialog)
        self.buttonBox.accepted.connect(KUserFeedback::Console::ConnectDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(KUserFeedback::Console::ConnectDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(KUserFeedback::Console::ConnectDialog)
        KUserFeedback::Console::ConnectDialog.setTabOrder(self.serverName, self.serverUrl)
        KUserFeedback::Console::ConnectDialog.setTabOrder(self.serverUrl, self.userName)
        KUserFeedback::Console::ConnectDialog.setTabOrder(self.userName, self.password)

    def retranslateUi(self, KUserFeedback::Console::ConnectDialog):
        _translate = QtCore.QCoreApplication.translate
        KUserFeedback::Console::ConnectDialog.setWindowTitle(_translate("KUserFeedback::Console::ConnectDialog", "Connect To Analytics Server"))
        self.label.setText(_translate("KUserFeedback::Console::ConnectDialog", "Server &name:"))
        self.label_2.setText(_translate("KUserFeedback::Console::ConnectDialog", "&User name:"))
        self.label_3.setText(_translate("KUserFeedback::Console::ConnectDialog", "P&assword:"))
        self.label_4.setText(_translate("KUserFeedback::Console::ConnectDialog", "Server UR&L:"))
