# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/kuserfeedback/src/console/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KUserFeedback::Console::MainWindow(object):
    def setupUi(self, KUserFeedback::Console::MainWindow):
        KUserFeedback::Console::MainWindow.setObjectName("KUserFeedback::Console::MainWindow")
        KUserFeedback::Console::MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(KUserFeedback::Console::MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.viewStack = QtWidgets.QStackedWidget(self.centralwidget)
        self.viewStack.setObjectName("viewStack")
