.TH "LIBKYPOWERMANAGEMENT" 3 "Mon Sep 18 2023" "Linux Programmer's Manual" \"
.SH NAME
kdk_set_inhibit_lockscreen, kdk_un_inhibit_lockscreen  - 提供锁屏设置能力
.SH SYNOPSIS
.nf
.B #include <libkylockscreen.h>
.sp
.BI "extern uint32_t kdk_set_inhibit_lockscreen(const char *"appName ", const char *"reason ");" 
.sp
.BI "extern int kdk_un_inhibit_lockscreen(uint32_t "flag ");" 
.sp
Link with \fI\-lkypowermanagement\fP.
.SH "Detailed Description"
This library provides lock screen setting capabilities.
.SH "RETURN VALUE"
The return value is generally specific to the individual function called.
.SH "CONFORMING TO"
These functions are as per the withdrawn POSIX.1e draft specification.
The following functions are Linux extensions:
.BR kdk_set_inhibit_lockscreen ()
and
.BR kdk_un_inhibit_lockscreen ().
.SH "SEE ALSO"
.BR kdk_set_inhibit_lockscreen (3)
and
.BR kdk_un_inhibit_lockscreen (3).