# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/plasma-nm/libs/editor/settings/ui/connectionwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConnectionWidget(object):
    def setupUi(self, ConnectionWidget):
        ConnectionWidget.setObjectName("ConnectionWidget")
        ConnectionWidget.resize(471, 262)
        self.formLayout = QtWidgets.QFormLayout(ConnectionWidget)
        self.formLayout.setObjectName("formLayout")
        self.autoconnect = QtWidgets.QCheckBox(ConnectionWidget)
        self.autoconnect.setChecked(True)
        self.autoconnect.setObjectName("autoconnect")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.autoconnect)
        self.prioritySpin = QtWidgets.QSpinBox(ConnectionWidget)
        self.prioritySpin.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prioritySpin.sizePolicy().hasHeightForWidth())
        self.prioritySpin.setSizePolicy(sizePolicy)
        self.prioritySpin.setMinimum(-100)
        self.prioritySpin.setObjectName("prioritySpin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.prioritySpin)
        self.allUsers = QtWidgets.QCheckBox(ConnectionWidget)
        self.allUsers.setChecked(False)
        self.allUsers.setObjectName("allUsers")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.allUsers)
        self.pushButtonPermissions = QtWidgets.QPushButton(ConnectionWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPermissions.sizePolicy().hasHeightForWidth())
        self.pushButtonPermissions.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("preferences-desktop-user")
        self.pushButtonPermissions.setIcon(icon)
        self.pushButtonPermissions.setObjectName("pushButtonPermissions")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButtonPermissions)
        self.autoconnectVpn = QtWidgets.QCheckBox(ConnectionWidget)
        self.autoconnectVpn.setObjectName("autoconnectVpn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.autoconnectVpn)
        self.vpnCombobox = KComboBox(ConnectionWidget)
        self.vpnCombobox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vpnCombobox.sizePolicy().hasHeightForWidth())
        self.vpnCombobox.setSizePolicy(sizePolicy)
        self.vpnCombobox.setObjectName("vpnCombobox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.vpnCombobox)
        self.firewallZoneLabel = QtWidgets.QLabel(ConnectionWidget)
        self.firewallZoneLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.firewallZoneLabel.setObjectName("firewallZoneLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.firewallZoneLabel)
        self.firewallZone = KComboBox(ConnectionWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firewallZone.sizePolicy().hasHeightForWidth())
        self.firewallZone.setSizePolicy(sizePolicy)
        self.firewallZone.setEditable(True)
        self.firewallZone.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.firewallZone.setObjectName("firewallZone")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.firewallZone)
        self.meteredLabel = QtWidgets.QLabel(ConnectionWidget)
        self.meteredLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meteredLabel.setObjectName("meteredLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.meteredLabel)
        self.metered = KComboBox(ConnectionWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metered.sizePolicy().hasHeightForWidth())
        self.metered.setSizePolicy(sizePolicy)
        self.metered.setEditable(False)
        self.metered.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.metered.setObjectName("metered")
        self.metered.addItem("")
        self.metered.addItem("")
        self.metered.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.metered)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.firewallZoneLabel.setBuddy(self.firewallZone)
        self.meteredLabel.setBuddy(self.firewallZone)

        self.retranslateUi(ConnectionWidget)
        self.allUsers.toggled['bool'].connect(self.pushButtonPermissions.setDisabled) # type: ignore
        self.autoconnect.toggled['bool'].connect(self.prioritySpin.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConnectionWidget)
        ConnectionWidget.setTabOrder(self.autoconnect, self.allUsers)
        ConnectionWidget.setTabOrder(self.allUsers, self.pushButtonPermissions)
        ConnectionWidget.setTabOrder(self.pushButtonPermissions, self.autoconnectVpn)
        ConnectionWidget.setTabOrder(self.autoconnectVpn, self.vpnCombobox)
        ConnectionWidget.setTabOrder(self.vpnCombobox, self.firewallZone)

    def retranslateUi(self, ConnectionWidget):
        _translate = QtCore.QCoreApplication.translate
        self.autoconnect.setText(_translate("ConnectionWidget", "Connect automatically with priority"))
        self.prioritySpin.setToolTip(_translate("ConnectionWidget", "If the connection is set to autoconnect, connections with higher priority will be preferred. Defaults to 0.\n"
"The higher number means higher priority. A negative number can be used to indicate priority lower than the default.\n"
"           "))
        self.allUsers.setText(_translate("ConnectionWidget", "All users may connect to this network"))
        self.pushButtonPermissions.setToolTip(_translate("ConnectionWidget", "Edit advanced permissions for this connection"))
        self.pushButtonPermissions.setWhatsThis(_translate("ConnectionWidget", "Fine-grained permissions editor for this connection. It lets you choose which users can activate/modify/delete this connection."))
        self.pushButtonPermissions.setText(_translate("ConnectionWidget", "Advanced…"))
        self.autoconnectVpn.setText(_translate("ConnectionWidget", "Automatically connect to VPN"))
        self.firewallZoneLabel.setText(_translate("ConnectionWidget", "Firewall zone:"))
        self.meteredLabel.setText(_translate("ConnectionWidget", "Metered:"))
        self.metered.setToolTip(_translate("ConnectionWidget", "NetworkManager indicates to applications whether the connection is metered and therefore\n"
"data usage should be restricted."))
        self.metered.setItemText(0, _translate("ConnectionWidget", "Automatic", "Item in the Metered: list"))
        self.metered.setItemText(1, _translate("ConnectionWidget", "Yes"))
        self.metered.setItemText(2, _translate("ConnectionWidget", "No"))
from kcombobox import KComboBox
