.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 niecheng <niecheng@uniontech.com>,
.\"
.TH "dde-lock" "1" "2021-1-28" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .v         disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dde-session-shell \- package manager for deepin.
.SH DESCRIPTION
Package dde-session-shell.deb - login，the entry to the desktop, and also  lock screen, to protect privacy
.SH OPTIONS
.TP
.B \-h <help>
Displays this help.
.TP
.B \-v <version>
Displays version information
.B \-d <daemon>
start to daemon mode
.B \-s <switch>
show user switch
.B \-t <shutdown>
show shut down
.PP
Package Installer is an easy-to-use .deb package is lock screen, login and switch user.
.SH AUTHOR
.PP
.B dde-lock
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT niecheng@\:uniontech.com
.ME
for the Debian Project (but may be used by others)