######################################################################
# Automatically generated by qmake (3.1) Wed Dec 13 16:02:06 2023
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += properties-window
SUBDIRS += windows
