.TH "LIBKYLOCATION" 3 "Thu Sep 14 2023" "Linux Programmer's Manual" \"
.SH NAME
kdk_loaction_get - 获取地址信息
.SH SYNOPSIS
.nf
.B #include <libkylocation.h>
.sp
.BI "extern char *kdk_loaction_get();" 
.sp
Link with \fI\-lkylocation\fP.
.SH "Detailed Description"
This library contains address information.
.SH "RETURN VALUE"
The return value is generally specific to the individual function called.
.SH "CONFORMING TO"
These functions are as per the withdrawn POSIX.1e draft specification.
The following functions are Linux extensions:
.BR kdk_loaction_get ().
.SH "SEE ALSO"
.BR kdk_loaction_get (3).