import infra.basetest


class TestATFAllwinner(infra.basetest.BRTest):
    config = \
        """
        LINGMO_aarch64=y
        LINGMO_TOOLCHAIN_EXTERNAL=y
        LINGMO_TOOLCHAIN_EXTERNAL_LINARO_AARCH64=y
        LINGMO_TARGET_ARM_TRUSTED_FIRMWARE=y
        LINGMO_TARGET_ARM_TRUSTED_FIRMWARE_CUSTOM_VERSION=y
        LINGMO_TARGET_ARM_TRUSTED_FIRMWARE_CUSTOM_VERSION_VALUE="v2.9"
        LINGMO_TARGET_ARM_TRUSTED_FIRMWARE_PLATFORM="sun50i_a64"
        # LINGMO_TARGET_ARM_TRUSTED_FIRMWARE_SSP is not set
        LINGMO_TARGET_ARM_TRUSTED_FIRMWARE_BL31=y
        LINGMO_TARGET_UBOOT=y
        LINGMO_TARGET_UBOOT_BUILD_SYSTEM_KCONFIG=y
        LINGMO_TARGET_UBOOT_CUSTOM_VERSION=y
        LINGMO_TARGET_UBOOT_CUSTOM_VERSION_VALUE="2023.10"
        LINGMO_TARGET_UBOOT_BOARD_DEFCONFIG="orangepi_zero_plus2"
        LINGMO_TARGET_UBOOT_NEEDS_DTC=y
        LINGMO_TARGET_UBOOT_NEEDS_OPENSSL=y
        LINGMO_TARGET_UBOOT_NEEDS_PYTHON3=y
        LINGMO_TARGET_UBOOT_NEEDS_PYLIBFDT=y
        LINGMO_TARGET_UBOOT_NEEDS_ATF_BL31=y
        LINGMO_TARGET_UBOOT_SPL=y
        LINGMO_TARGET_UBOOT_SPL_NAME="u-boot-sunxi-with-spl.bin"
        LINGMO_TARGET_UBOOT_CUSTOM_MAKEOPTS="SCP=/dev/null"
        """

    def test_run(self):
        pass
