# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/kpeople/src/widgets/person-details-presentation.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PersonDetailsPresentation(object):
    def setupUi(self, PersonDetailsPresentation):
        PersonDetailsPresentation.setObjectName("PersonDetailsPresentation")
        PersonDetailsPresentation.setMaximumSize(QtCore.QSize(16777215, 96))
        self.gridLayout = QtWidgets.QGridLayout(PersonDetailsPresentation)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.detailsLabel = QtWidgets.QLabel(PersonDetailsPresentation)
        self.detailsLabel.setText("")
        self.detailsLabel.setObjectName("detailsLabel")
        self.gridLayout.addWidget(self.detailsLabel, 1, 2, 1, 1)
        self.avatarPixmapLabel = QtWidgets.QLabel(PersonDetailsPresentation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.avatarPixmapLabel.sizePolicy().hasHeightForWidth())
        self.avatarPixmapLabel.setSizePolicy(sizePolicy)
        self.avatarPixmapLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.avatarPixmapLabel.setMaximumSize(QtCore.QSize(96, 96))
        self.avatarPixmapLabel.setObjectName("avatarPixmapLabel")
        self.gridLayout.addWidget(self.avatarPixmapLabel, 0, 0, 4, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.presencePixmapLabel = QtWidgets.QLabel(PersonDetailsPresentation)
        self.presencePixmapLabel.setMaximumSize(QtCore.QSize(64, 64))
        self.presencePixmapLabel.setText("")
        self.presencePixmapLabel.setObjectName("presencePixmapLabel")
        self.gridLayout.addWidget(self.presencePixmapLabel, 0, 1, 1, 1)
        self.nameLabel = QtWidgets.QLabel(PersonDetailsPresentation)
        self.nameLabel.setText("")
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)

        self.retranslateUi(PersonDetailsPresentation)
        QtCore.QMetaObject.connectSlotsByName(PersonDetailsPresentation)

    def retranslateUi(self, PersonDetailsPresentation):
        _translate = QtCore.QCoreApplication.translate
        self.avatarPixmapLabel.setText(_translate("PersonDetailsPresentation", "Avatar"))
