# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/lingmo-nm/libs/editor/settings/ui/bt.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BtWidget(object):
    def setupUi(self, BtWidget):
        BtWidget.setObjectName("BtWidget")
        BtWidget.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(BtWidget)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(BtWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.bdaddr = HwAddrComboBox(BtWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bdaddr.sizePolicy().hasHeightForWidth())
        self.bdaddr.setSizePolicy(sizePolicy)
        self.bdaddr.setObjectName("bdaddr")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bdaddr)
        self.label_2 = QtWidgets.QLabel(BtWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.type = KComboBox(BtWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type.sizePolicy().hasHeightForWidth())
        self.type.setSizePolicy(sizePolicy)
        self.type.setObjectName("type")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.type)
        self.label.setBuddy(self.bdaddr)
        self.label_2.setBuddy(self.type)

        self.retranslateUi(BtWidget)
        QtCore.QMetaObject.connectSlotsByName(BtWidget)

    def retranslateUi(self, BtWidget):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("BtWidget", "Address of the device:"))
        self.label_2.setText(_translate("BtWidget", "Connection type:"))
from hwaddrcombobox import HwAddrComboBox
from kcombobox import KComboBox
