# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/lingmo-nm/libs/editor/settings/ui/wireguardtabwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WireGuardTabWidget(object):
    def setupUi(self, WireGuardTabWidget):
        WireGuardTabWidget.setObjectName("WireGuardTabWidget")
        WireGuardTabWidget.resize(498, 427)
        self.gridLayout = QtWidgets.QGridLayout(WireGuardTabWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(WireGuardTabWidget)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(WireGuardTabWidget)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAdd = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout.addWidget(self.btnAdd)
        self.btnRemove = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnRemove.setObjectName("btnRemove")
        self.horizontalLayout.addWidget(self.btnRemove)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.horizontalLayoutWidget, 2, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(WireGuardTabWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 8, 1, 1, 1)

        self.retranslateUi(WireGuardTabWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WireGuardTabWidget)

    def retranslateUi(self, WireGuardTabWidget):
        _translate = QtCore.QCoreApplication.translate
        self.btnAdd.setText(_translate("WireGuardTabWidget", "Add new Peer"))
        self.btnRemove.setText(_translate("WireGuardTabWidget", "Remove this Peer"))
