# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/kwin/src/plugins/magnifier/magnifier_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KWin::MagnifierEffectConfigForm(object):
    def setupUi(self, KWin::MagnifierEffectConfigForm):
        KWin::MagnifierEffectConfigForm.setObjectName("KWin::MagnifierEffectConfigForm")
        KWin::MagnifierEffectConfigForm.resize(246, 181)
        self.vboxlayout = QtWidgets.QVBoxLayout(KWin::MagnifierEffectConfigForm)
        self.vboxlayout.setObjectName("vboxlayout")
        self.groupSize = QtWidgets.QGroupBox(KWin::MagnifierEffectConfigForm)
        self.groupSize.setObjectName("groupSize")
        self.gridLayout = QtWidgets.QGridLayout(self.groupSize)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupSize)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.kcfg_Width = QtWidgets.QSpinBox(self.groupSize)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kcfg_Width.sizePolicy().hasHeightForWidth())
        self.kcfg_Width.setSizePolicy(sizePolicy)
        self.kcfg_Width.setMaximum(9999)
        self.kcfg_Width.setSingleStep(10)
        self.kcfg_Width.setObjectName("kcfg_Width")
        self.gridLayout.addWidget(self.kcfg_Width, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupSize)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.kcfg_Height = QtWidgets.QSpinBox(self.groupSize)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kcfg_Height.sizePolicy().hasHeightForWidth())
        self.kcfg_Height.setSizePolicy(sizePolicy)
        self.kcfg_Height.setMaximum(9999)
        self.kcfg_Height.setSingleStep(10)
        self.kcfg_Height.setObjectName("kcfg_Height")
        self.gridLayout.addWidget(self.kcfg_Height, 1, 1, 1, 1)
        self.vboxlayout.addWidget(self.groupSize)
        self.editor = KShortcutsEditor(KWin::MagnifierEffectConfigForm)
        self.editor.setActionTypes(KShortcutsEditor.GlobalAction)
        self.editor.setObjectName("editor")
        self.vboxlayout.addWidget(self.editor)
        self.label.setBuddy(self.kcfg_Width)
        self.label_2.setBuddy(self.kcfg_Height)

        self.retranslateUi(KWin::MagnifierEffectConfigForm)
        QtCore.QMetaObject.connectSlotsByName(KWin::MagnifierEffectConfigForm)

    def retranslateUi(self, KWin::MagnifierEffectConfigForm):
        _translate = QtCore.QCoreApplication.translate
        self.groupSize.setTitle(_translate("KWin::MagnifierEffectConfigForm", "Size"))
        self.label.setText(_translate("KWin::MagnifierEffectConfigForm", "&Width:"))
        self.kcfg_Width.setSuffix(_translate("KWin::MagnifierEffectConfigForm", " px"))
        self.label_2.setText(_translate("KWin::MagnifierEffectConfigForm", "&Height:"))
        self.kcfg_Height.setSuffix(_translate("KWin::MagnifierEffectConfigForm", " px"))
from KShortcutsEditor import KShortcutsEditor
