.\" This file is processed to generate manpages in the
.\" build diretory.
.TH "dde-calendar" "1" "2021-3-11" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dde-calendar \- a smart daily planner to schedule all things in life
.SH SYNOPSIS
dde-calendar [OPTIONS...]
.SH DESCRIPTION
Calendar is a smart daily planner to schedule all things in life.
.PP
Calendar is a small management tool for personal life that combines time and events and integrates the function of memorizing and scheduling.
.SH OPTIONS
.PP
-h  --help 
       Prints the command line options.
.PP
-v  --version
       Output version information and exit.
.PP
.SH SEE ALSO
https://github.com/linuxdeepin/dde-calendar
.SH AUTHOR
.PP
.B dde-calendar
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT chenhaifeng@\:uniontech.com
Chen Haifeng
.ME
for the Debian Project (but may be used by others)
