[Desktop Entry]
Type=XSession
Exec=${CMAKE_INSTALL_FULL_BINDIR}/startlingmo-x11
TryExec=${CMAKE_INSTALL_FULL_BINDIR}/startlingmo-x11
DesktopNames=KDE
Name=Lingmo (X11)
Name[ar]=بلازما (اكس11)
Name[ast]=Lingmo (X11)
Name[az]=Lingmo (X11)
Name[be]=Lingmo (X11)
Name[bg]=Lingmo (X11)
Name[ca]=Lingmo (X11)
Name[ca@valencia]=Lingmo (X11)
Name[cs]=Lingmo (X11)
Name[da]=Lingmo (X11)
Name[de]=Lingmo (X11)
Name[en_GB]=Lingmo (X11)
Name[eo]=Lingmo (X11)
Name[es]=Lingmo (X11)
Name[eu]=Lingmo (X11)
Name[fi]=Lingmo (X11)
Name[fr]=Lingmo (X11)
Name[gl]=Lingmo (X11)
Name[he]=פלזמה (X11)
Name[hi]=प्लाज़्मा (एक्स ११)
Name[hu]=Lingmo (X11)
Name[ia]=Lingmo (X11)
Name[id]=Lingmo (X11)
Name[is]=Lingmo (X11)
Name[it]=Lingmo (X11)
Name[ja]=Lingmo (X11)
Name[ka]=Lingmo (X11)
Name[ko]=Lingmo(X11)
Name[lt]=Lingmo (X11)
Name[lv]=Lingmo (X11)
Name[ml]=പ്ലാസ്മ (X11)
Name[nl]=Lingmo (X11)
Name[nn]=Lingmo (X11)
Name[pa]=ਪਲਾਜ਼ਮਾ (X11)
Name[pl]=Plazma (X11)
Name[pt]=Lingmo (X11)
Name[pt_BR]=Lingmo (X11)
Name[ro]=Lingmo (X11)
Name[ru]=Lingmo (X11)
Name[sa]=प्लाज्मा (X११)
Name[sk]=Lingmo (X11)
Name[sl]=Lingmo (X11)
Name[sv]=Lingmo (X11)
Name[ta]=பிளாஸ்மா (X11)
Name[tg]=Плазма (X11)
Name[tr]=Lingmo (X11)
Name[uk]=Плазма (X11)
Name[vi]=Lingmo (X11)
Name[x-test]=xxLingmo (X11)xx
Name[zh_CN]=Lingmo (X11)
Name[zh_TW]=Lingmo (X11)
Comment=Lingmo by KDE
Comment[ar]=بلازما كِيدِي
Comment[az]=KDE Lingmo
Comment[be]=Lingmo KDE
Comment[bg]=Lingmo от KDE
Comment[bs]=Plazma od strane KDe
Comment[ca]=Lingmo, creat per la comunitat KDE
Comment[ca@valencia]=Lingmo, creat per la comunitat KDE
Comment[cs]=Lingmo z KDE
Comment[da]=Lingmo fra KDE
Comment[de]=Lingmo von KDE
Comment[el]=Lingmo από το KDE
Comment[en_GB]=Lingmo by KDE
Comment[eo]=Lingmo de KDE
Comment[es]=Lingmo, por KDE
Comment[et]=KDE Lingmo
Comment[eu]=KDEren Lingmo
Comment[fi]=Lingmo KDE:ltä
Comment[fr]=Lingmo, par KDE
Comment[gl]=Lingmo, fornecido por KDE.
Comment[he]=פלזמה מבית KDE
Comment[hi]=केडीइ द्वारा प्लाज़्मा
Comment[hsb]=Lingmo wot KDE
Comment[hu]=Lingmo a KDE-től
Comment[ia]=Lingmo per KDE
Comment[id]=Lingmo oleh KDE
Comment[is]=Lingmo frá KDE
Comment[it]=Lingmo di KDE
Comment[ja]=Lingmo by KDE
Comment[ka]=Lingmo, KDE-სგან
Comment[ko]=KDE Lingmo
Comment[lt]=Lingmo pagal KDE
Comment[lv]=„Lingmo“ no KDE
Comment[ml]=കെഡിഇയുടെ പ്ലാസ്മ
Comment[nb]=Lingmo av KDE
Comment[nds]=Lingmo vun KDE
Comment[nl]=Lingmo door KDE
Comment[nn]=Lingmo frå KDE
Comment[pa]=KDE ਵਲੋਂ ਪਲਾਜ਼ਮਾ
Comment[pl]=Plazma dzięki KDE
Comment[pt]=Lingmo do KDE
Comment[pt_BR]=Lingmo do KDE
Comment[ro]=Lingmo, de către KDE
Comment[ru]=KDE Lingmo
Comment[sa]=KDE इत्यस्मात् प्लाज्मा
Comment[sk]=Lingmo od KDE
Comment[sl]=KDE Lingmo
Comment[sr]=Плазма од КДЕ‑а
Comment[sr@ijekavian]=Плазма од КДЕ‑а
Comment[sr@ijekavianlatin]=Lingmo od KDE‑a
Comment[sr@latin]=Lingmo od KDE‑a
Comment[sv]=Lingmo av KDE
Comment[ta]=கே.டீ.யீ. வழங்கும் பிளாஸ்மா
Comment[tg]=Lingmo аз ҷониби KDE
Comment[tr]=KDE Lingmo
Comment[uk]=Плазма KDE
Comment[vi]=Lingmo, do KDE
Comment[x-test]=xxLingmo by KDExx
Comment[zh_CN]=KDE Lingmo
Comment[zh_TW]=Lingmo by KDE
X-KDE-PluginInfo-Version=${PROJECT_VERSION}
