[Desktop Entry]
Type=XSession
Exec=@CMAKE_INSTALL_FULL_LIBEXECDIR@/startlingmo-dev.sh -x11
DesktopNames=KDE
Name=Lingmo (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ar]=بلازما (تطوير, اكس11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[az]=Lingmo (Tərtib mərhələsində olan X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[be]=Lingmo (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[bg]=Lingmo (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ca]=Lingmo (Desenvolupament, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ca@valencia]=Lingmo (Desenvolupament, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[da]=Lingmo (udvikling, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[de]=Lingmo (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[en_GB]=Lingmo (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[eo]=Lingmo (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[es]=Lingmo (Desarrollo, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[et]=Lingmo (arendus, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[eu]=Lingmo (Garapena, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[fi]=Lingmo (kehitys, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[fr]=Lingmo (Développement, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[gl]=Lingmo (desenvolvemento, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[he]=פלזמה (פיתוח, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[hi]=प्लाज़्मा (विकास, एक्स ११ ${CMAKE_INSTALL_FULL_BINDIR})
Name[hu]=Lingmo (Fejlesztői verzió, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ia]=Lingmo (Disveloppamento, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[id]=Lingmo (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[is]=Lingmo (Þróunarútgáfa, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[it]=Lingmo (Sviluppo, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ja]=Lingmo (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ka]=Lingmo (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ko]=Lingmo(개발, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[lt]=Lingmo (Plėtojimas, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[lv]=„Lingmo“ (izstrāde, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ml]=പ്ലാസ്മ (വികസനം, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[nl]=Lingmo (Ontwikkeling, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[nn]=Lingmo (utvikling, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[pa]=ਪਲਾਜ਼ਮਾ (ਡਿਵੈਲਪਮੈਂਟ, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[pl]=Plazma (Rozwój , X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[pt]=Lingmo (Desenvolvimento, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[pt_BR]=Lingmo (Desenvolvimento, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ro]=Lingmo (Dezvoltare, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ru]=Lingmo (разрабатываемая версия, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[sa]=प्लाज्मा (विकास, X११ ${CMAKE_INSTALL_FULL_BINDIR})
Name[sk]=Lingmo (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[sl]=Lingmo (Razvoj, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[sv]=Lingmo (utveckling, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ta]=பிளாஸ்மா (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[tr]=Lingmo (Geliştirme, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[uk]=Плазма (Розробка, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[vi]=Lingmo (Phát triển, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[x-test]=xxLingmo (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})xx
Name[zh_CN]=Lingmo (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[zh_TW]=Lingmo (開發版本，X11 ${CMAKE_INSTALL_FULL_BINDIR})
Comment=Lingmo by KDE
Comment[ar]=بلازما كِيدِي
Comment[az]=KDE Lingmo
Comment[be]=Lingmo KDE
Comment[bg]=Lingmo от KDE
Comment[bs]=Plazma od strane KDe
Comment[ca]=Lingmo, creat per la comunitat KDE
Comment[ca@valencia]=Lingmo, creat per la comunitat KDE
Comment[cs]=Lingmo z KDE
Comment[da]=Lingmo fra KDE
Comment[de]=Lingmo von KDE
Comment[el]=Lingmo από το KDE
Comment[en_GB]=Lingmo by KDE
Comment[eo]=Lingmo de KDE
Comment[es]=Lingmo, por KDE
Comment[et]=KDE Lingmo
Comment[eu]=KDEren Lingmo
Comment[fi]=Lingmo KDE:ltä
Comment[fr]=Lingmo, par KDE
Comment[gl]=Lingmo, fornecido por KDE.
Comment[he]=פלזמה מבית KDE
Comment[hi]=केडीइ द्वारा प्लाज़्मा
Comment[hsb]=Lingmo wot KDE
Comment[hu]=Lingmo a KDE-től
Comment[ia]=Lingmo per KDE
Comment[id]=Lingmo oleh KDE
Comment[is]=Lingmo frá KDE
Comment[it]=Lingmo di KDE
Comment[ja]=Lingmo by KDE
Comment[ka]=Lingmo, KDE-სგან
Comment[ko]=KDE Lingmo
Comment[lt]=Lingmo pagal KDE
Comment[lv]=„Lingmo“ no KDE
Comment[ml]=കെഡിഇയുടെ പ്ലാസ്മ
Comment[nb]=Lingmo av KDE
Comment[nds]=Lingmo vun KDE
Comment[nl]=Lingmo door KDE
Comment[nn]=Lingmo frå KDE
Comment[pa]=KDE ਵਲੋਂ ਪਲਾਜ਼ਮਾ
Comment[pl]=Plazma dzięki KDE
Comment[pt]=Lingmo do KDE
Comment[pt_BR]=Lingmo do KDE
Comment[ro]=Lingmo, de către KDE
Comment[ru]=KDE Lingmo
Comment[sa]=KDE इत्यस्मात् प्लाज्मा
Comment[sk]=Lingmo od KDE
Comment[sl]=KDE Lingmo
Comment[sr]=Плазма од КДЕ‑а
Comment[sr@ijekavian]=Плазма од КДЕ‑а
Comment[sr@ijekavianlatin]=Lingmo od KDE‑a
Comment[sr@latin]=Lingmo od KDE‑a
Comment[sv]=Lingmo av KDE
Comment[ta]=கே.டீ.யீ. வழங்கும் பிளாஸ்மா
Comment[tg]=Lingmo аз ҷониби KDE
Comment[tr]=KDE Lingmo
Comment[uk]=Плазма KDE
Comment[vi]=Lingmo, do KDE
Comment[x-test]=xxLingmo by KDExx
Comment[zh_CN]=KDE Lingmo
Comment[zh_TW]=Lingmo by KDE
X-KDE-PluginInfo-Version=${PROJECT_VERSION}
