usr/include/qt5xdgiconloader
usr/lib/*/libQt5XdgIconLoader.so
usr/lib/*/pkgconfig/Qt5XdgIconLoader.pc
usr/lib/*/qt5/plugins/iconengines/libQt5XdgIconPlugin.so
usr/share/cmake/qt5xdgiconloader/qt5xdgiconloader-config-version.cmake
usr/share/cmake/qt5xdgiconloader/qt5xdgiconloader-config.cmake
usr/share/cmake/qt5xdgiconloader/qt5xdgiconloader-targets-relwithdebinfo.cmake
usr/share/cmake/qt5xdgiconloader/qt5xdgiconloader-targets.cmake
