.TH "KySdkNet" 3 "Wed Sep 20 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KySdkNet \- 生成网络信息dbus信号类 主要用来生成指定网络端口的状态、区间端口状态、网关信息、防火墙信息dbus信号  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lingmosdkdbus\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "int \fBgetPortState\fP (int port) const"
.br
.RI "获取指定网络端口的状态 "
.ti -1c
.RI "QStringList \fBgetMultiplePortStat\fP (int start, int end) const"
.br
.RI "获取区间端口状态 "
.ti -1c
.RI "QStringList \fBgetGatewayInfo\fP () const"
.br
.RI "获取网关信息 "
.ti -1c
.RI "QStringList \fBgetFirewallState\fP () const"
.br
.RI "获取防火墙信息 "
.in -1c
.SH "Detailed Description"
.PP 
生成网络信息dbus信号类 主要用来生成指定网络端口的状态、区间端口状态、网关信息、防火墙信息dbus信号 
.PP 

.SH "Public Slots"
.PP 
.SS "QStringList KySdkNet::getFirewallState () const\fC [slot]\fP"

.PP
获取防火墙信息 
.PP
\fBReturns\fP
.RS 4
QStringList 防火墙信息列表 
.RE
.PP

.SS "QStringList KySdkNet::getGatewayInfo () const\fC [slot]\fP"

.PP
获取网关信息 
.PP
\fBReturns\fP
.RS 4
QStringList 网关信息网卡名和地址列表 
.RE
.PP

.SS "QStringList KySdkNet::getMultiplePortStat (int start, int end) const\fC [slot]\fP"

.PP
获取区间端口状态 
.PP
\fBParameters\fP
.RS 4
\fIstart\fP 开始端口 
.br
\fIend\fP 结束端口 
.RE
.PP
\fBReturns\fP
.RS 4
QStringList 区间端口状态列表 
.RE
.PP

.SS "int KySdkNet::getPortState (int port) const\fC [slot]\fP"

.PP
获取指定网络端口的状态 
.PP
\fBParameters\fP
.RS 4
\fIport\fP 端口号 
.RE
.PP
\fBReturns\fP
.RS 4
int 端口状态 TCP_ESTABLISHED:0x1 TCP_SYN_SENT:0x2 TCP_SYN_RECV:0x3 TCP_FIN_WAIT1:0x4 TCP_FIN_WAIT2:0x5 TCP_TIME_WAIT:0x6 TCP_CLOSE:0x7 TCP_CLOSE_WAIT:0x8 TCP_LAST_ACL:0x9 TCP_LISTEN:0xa TCP_CLOSING:0xb 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for lingmosdkdbus.h from the source code\&.
