.TH "KySdkCpuInfo" 3 "Wed Sep 20 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KySdkCpuInfo \- 生成cpu信息dbus信号类 主要用来生成cpu的架构、制造厂商、型号、额定主频、核心数量、虚拟化支持和线程数信息dbus信号  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lingmosdkdbus\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "QString \fBgetCpuArch\fP () const"
.br
.RI "获取cpu架构 "
.ti -1c
.RI "QString \fBgetCpuVendor\fP () const"
.br
.RI "获取cpu制造厂商 "
.ti -1c
.RI "QString \fBgetCpuModel\fP () const"
.br
.RI "获取cpu型号 "
.ti -1c
.RI "QString \fBgetCpuFreqMHz\fP () const"
.br
.RI "获取cpu额定主频 "
.ti -1c
.RI "unsigned int \fBgetCpuCorenums\fP () const"
.br
.RI "获取cpu核心数量 "
.ti -1c
.RI "QString \fBgetCpuVirt\fP () const"
.br
.RI "获取cpu对虚拟化的支持 "
.ti -1c
.RI "unsigned int \fBgetCpuProcess\fP () const"
.br
.RI "获取cpu线程数 "
.in -1c
.SH "Detailed Description"
.PP 
生成cpu信息dbus信号类 主要用来生成cpu的架构、制造厂商、型号、额定主频、核心数量、虚拟化支持和线程数信息dbus信号 
.PP 

.SH "Public Slots"
.PP 
.SS "QString KySdkCpuInfo::getCpuArch () const\fC [slot]\fP"

.PP
获取cpu架构 
.PP
\fBReturns\fP
.RS 4
QString 架构信息，如'x86_64' 
.RE
.PP

.SS "unsigned int KySdkCpuInfo::getCpuCorenums () const\fC [slot]\fP"

.PP
获取cpu核心数量 
.PP
\fBReturns\fP
.RS 4
unsigned int 所有可用的CPU核心数量 
.RE
.PP

.SS "QString KySdkCpuInfo::getCpuFreqMHz () const\fC [slot]\fP"

.PP
获取cpu额定主频 
.PP
\fBReturns\fP
.RS 4
QString 额定主频赫兹数，如“1794\&.742” 
.RE
.PP

.SS "QString KySdkCpuInfo::getCpuModel () const\fC [slot]\fP"

.PP
获取cpu型号 
.PP
\fBReturns\fP
.RS 4
QString CPU型号名称，如“Intel(R) Core(TM) i7-4790K CPU @ 4\&.00GHz” 
.RE
.PP

.SS "unsigned int KySdkCpuInfo::getCpuProcess () const\fC [slot]\fP"

.PP
获取cpu线程数 
.PP
\fBReturns\fP
.RS 4
unsigned int cpu支持的线程数 
.RE
.PP

.SS "QString KySdkCpuInfo::getCpuVendor () const\fC [slot]\fP"

.PP
获取cpu制造厂商 
.PP
\fBReturns\fP
.RS 4
QString 制造厂商，如“GenuineIntel” 
.RE
.PP

.SS "QString KySdkCpuInfo::getCpuVirt () const\fC [slot]\fP"

.PP
获取cpu对虚拟化的支持 
.PP
\fBReturns\fP
.RS 4
QString 若CPU支持虚拟化，则返回虚拟化技术，如“vmx”；若不支持，返回NULL 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for lingmosdkdbus.h from the source code\&.
