.TH "KySdkRunInfo" 3 "Wed Sep 20 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KySdkRunInfo \- 生成瞬时信息dbus信号类 主要用来生成瞬时网速，cpu温度、磁盘温度、磁盘转速dbus信号  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lingmosdkdbus\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "double \fBgetNetSpeed\fP (const QString nc) const"
.br
.RI "获取瞬时网速信息 "
.ti -1c
.RI "int \fBgetDiskRate\fP (const QString diskpath) const"
.br
.RI "获取磁盘转速 "
.ti -1c
.RI "double \fBgetCpuTemperature\fP () const"
.br
.RI "获取CPU温度 "
.ti -1c
.RI "double \fBgetDiskTemperature\fP (const QString diskpath) const"
.br
.RI "获取磁盘温度 "
.in -1c
.SH "Detailed Description"
.PP 
生成瞬时信息dbus信号类 主要用来生成瞬时网速，cpu温度、磁盘温度、磁盘转速dbus信号 
.PP 

.SH "Public Slots"
.PP 
.SS "double KySdkRunInfo::getCpuTemperature () const\fC [slot]\fP"

.PP
获取CPU温度 
.PP
\fBReturns\fP
.RS 4
double CPU温度 
.RE
.PP

.SS "int KySdkRunInfo::getDiskRate (const QString diskpath) const\fC [slot]\fP"

.PP
获取磁盘转速 
.PP
\fBParameters\fP
.RS 4
\fIdiskpath\fP 磁盘名称，应当是例如/dev/sda这种绝对路径 
.RE
.PP
\fBReturns\fP
.RS 4
int 磁盘转速 
.RE
.PP

.SS "double KySdkRunInfo::getDiskTemperature (const QString diskpath) const\fC [slot]\fP"

.PP
获取磁盘温度 
.PP
\fBParameters\fP
.RS 4
\fIdiskpath\fP 磁盘名称，应当是例如/dev/sda这种绝对路径 
.RE
.PP
\fBReturns\fP
.RS 4
double 磁盘温度 
.RE
.PP

.SS "double KySdkRunInfo::getNetSpeed (const QString nc) const\fC [slot]\fP"

.PP
获取瞬时网速信息 
.PP
\fBParameters\fP
.RS 4
\fInc\fP 网卡名称，如eno1 
.RE
.PP
\fBReturns\fP
.RS 4
double 瞬时网速 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for lingmosdkdbus.h from the source code\&.
