.TH "KySdkPackageInfo" 3 "Wed Sep 20 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KySdkPackageInfo \- 获取包列表信息类 主要用来获取系统中所有包列表、获取系统中指定包的版本号、检测指定包名的软件包是否正确安装  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lingmosdkdbus\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "QStringList \fBgetPackageList\fP () const"
.br
.RI "获取系统中所有包列表 "
.ti -1c
.RI "QString \fBgetPackageVersion\fP (const QString packageName) const"
.br
.RI "获取系统中指定包的版本号 "
.ti -1c
.RI "int \fBgetPackageInstalled\fP (const QString packageName, const QString version) const"
.br
.RI "检测指定包名的软件包是否正确安装 "
.in -1c
.SH "Detailed Description"
.PP 
获取包列表信息类 主要用来获取系统中所有包列表、获取系统中指定包的版本号、检测指定包名的软件包是否正确安装 
.PP 

.SH "Public Slots"
.PP 
.SS "int KySdkPackageInfo::getPackageInstalled (const QString packageName, const QString version) const\fC [slot]\fP"

.PP
检测指定包名的软件包是否正确安装 
.PP
\fBParameters\fP
.RS 4
\fIpackageName\fP 包名 
.br
\fIversion\fP 版本号，大部分情况下为NULL，预留为snap做准备 
.RE
.PP
\fBReturns\fP
.RS 4
int 成功返回0，失败返回错误码 
.RE
.PP

.SS "QStringList KySdkPackageInfo::getPackageList () const\fC [slot]\fP"

.PP
获取系统中所有包列表 
.PP
\fBReturns\fP
.RS 4
QStringList 系统中所有包列表 
.RE
.PP

.SS "QString KySdkPackageInfo::getPackageVersion (const QString packageName) const\fC [slot]\fP"

.PP
获取系统中指定包的版本号 
.PP
\fBParameters\fP
.RS 4
\fIpackageName\fP 软件包名 
.RE
.PP
\fBReturns\fP
.RS 4
QString 版本号 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for lingmosdkdbus.h from the source code\&.
