.TH "KySdkPeripheralsEnum" 3 "Wed Sep 20 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KySdkPeripheralsEnum \- 生成usb设备信息dbus信号类 主要用来生成usb设备的名称、类型、pid、vid、序列号、路径信息dbus信号  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lingmosdkdbus\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "QStringList \fBgetAllUsbInfo\fP () const"
.br
.RI "获取外接usb设备信息 "
.in -1c
.SH "Detailed Description"
.PP 
生成usb设备信息dbus信号类 主要用来生成usb设备的名称、类型、pid、vid、序列号、路径信息dbus信号 
.PP 

.SH "Public Slots"
.PP 
.SS "QStringList KySdkPeripheralsEnum::getAllUsbInfo () const\fC [slot]\fP"

.PP
获取外接usb设备信息 
.PP
\fBReturns\fP
.RS 4
QStringList usb设备名称、类型、pid、vid、序列号、路径信息列表 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for lingmosdkdbus.h from the source code\&.
