# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/kwin/src/shortcutdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShortcutDialog(object):
    def setupUi(self, ShortcutDialog):
        ShortcutDialog.setObjectName("ShortcutDialog")
        ShortcutDialog.resize(200, 100)
        self.verticalLayout = QtWidgets.QVBoxLayout(ShortcutDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.keySequenceEdit = QtWidgets.QKeySequenceEdit(ShortcutDialog)
        self.keySequenceEdit.setObjectName("keySequenceEdit")
        self.horizontalLayout.addWidget(self.keySequenceEdit)
        self.clearButton = QtWidgets.QToolButton(ShortcutDialog)
        icon = QtGui.QIcon.fromTheme("edit-clear-locationbar-rtl")
        self.clearButton.setIcon(icon)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.warning = QtWidgets.QLabel(ShortcutDialog)
        self.warning.setText("")
        self.warning.setObjectName("warning")
        self.verticalLayout.addWidget(self.warning)
        self.buttonBox = QtWidgets.QDialogButtonBox(ShortcutDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ShortcutDialog)
        self.buttonBox.accepted.connect(ShortcutDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ShortcutDialog.reject) # type: ignore
        self.clearButton.clicked.connect(self.keySequenceEdit.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ShortcutDialog)

    def retranslateUi(self, ShortcutDialog):
        _translate = QtCore.QCoreApplication.translate
        ShortcutDialog.setWindowTitle(_translate("ShortcutDialog", "Dialog"))
        self.clearButton.setText(_translate("ShortcutDialog", "..."))
