// SPDX-FileCopyrightText: 2024 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef DDPLUGIN_VIDEOWALLPAPER_GLOBAL_H
#define DDPLUGIN_VIDEOWALLPAPER_GLOBAL_H

#include <dfm-base/dfm_log_defines.h>

#define DDP_VIDEOWALLPAPER_NAMESPACE ddplugin_videowallpaper

#define DDP_VIDEOWALLPAPER_BEGIN_NAMESPACE namespace DDP_VIDEOWALLPAPER_NAMESPACE{
#define DDP_VIDEOWALLPAPER_END_NAMESPACE }
#define DDP_VIDEOWALLPAPER_USE_NAMESPACE using namespace DDP_VIDEOWALLPAPER_NAMESPACE;

DDP_VIDEOWALLPAPER_BEGIN_NAMESPACE

DFM_LOG_USE_CATEGORY(DDP_VIDEOWALLPAPER_NAMESPACE)

DDP_VIDEOWALLPAPER_END_NAMESPACE

#endif // DDPLUGIN_BACKGROUND_GLOBAL_H
