# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/LingmoOS/shell/bc/Notepad/addons/backtracebrowser/btconfigwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BtConfigWidget(object):
    def setupUi(self, BtConfigWidget):
        BtConfigWidget.setObjectName("BtConfigWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(BtConfigWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gFolderList = QtWidgets.QGroupBox(BtConfigWidget)
        self.gFolderList.setObjectName("gFolderList")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gFolderList)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.gFolderList)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.edtUrl = KUrlRequester(self.gFolderList)
        self.edtUrl.setObjectName("edtUrl")
        self.verticalLayout.addWidget(self.edtUrl)
        self.lstFolders = QtWidgets.QListWidget(self.gFolderList)
        self.lstFolders.setObjectName("lstFolders")
        self.verticalLayout.addWidget(self.lstFolders)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnRemove = QtWidgets.QPushButton(self.gFolderList)
        self.btnRemove.setObjectName("btnRemove")
        self.horizontalLayout_2.addWidget(self.btnRemove)
        self.btnAdd = QtWidgets.QPushButton(self.gFolderList)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.gFolderList)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.edtExtensions = QtWidgets.QLineEdit(self.gFolderList)
        self.edtExtensions.setObjectName("edtExtensions")
        self.horizontalLayout.addWidget(self.edtExtensions)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.gFolderList)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)

        self.retranslateUi(BtConfigWidget)
        QtCore.QMetaObject.connectSlotsByName(BtConfigWidget)

    def retranslateUi(self, BtConfigWidget):
        _translate = QtCore.QCoreApplication.translate
        self.gFolderList.setTitle(_translate("BtConfigWidget", "Search Folders"))
        self.label.setText(_translate("BtConfigWidget", "Please add the source folders in which to search for the files in the backtrace:"))
        self.lstFolders.setWhatsThis(_translate("BtConfigWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Insert the source folders here. As example, for KDE development you have to add the Qt and Frameworks source folders:</p>\n"
"<ul style=\"-qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">/path/to/kdelibs</li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">/path/to/qt/src</li></ul></body></html>"))
        self.btnRemove.setText(_translate("BtConfigWidget", "&Remove"))
        self.btnAdd.setText(_translate("BtConfigWidget", "&Add"))
        self.label_2.setText(_translate("BtConfigWidget", "File types:"))
        self.edtExtensions.setWhatsThis(_translate("BtConfigWidget", "List of file extensions. Example: *.cpp, *.h, *.c, etc..."))
from kurlrequester import KUrlRequester
