.TH "kdk::KSoundEffects" 3 "Fri Sep 8 2023" "Version version:2.3" "LIBLINGMOSDK-DESKTOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdk::KSoundEffects \- 音效通知，可以根据输入的类型触发不同的音效提示用户  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksoundeffects\&.h>\fP
.PP
Inherits QObject\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBplaySound\fP (SoundType type)"
.br
.RI "播放系统音效 "
.in -1c
.SH "Detailed Description"
.PP 
音效通知，可以根据输入的类型触发不同的音效提示用户 
.SH "Member Function Documentation"
.PP 
.SS "static void kdk::KSoundEffects::playSound (SoundType type)\fC [static]\fP"

.PP
播放系统音效 
.PP
\fBParameters\fP
.RS 4
\fIsoundEvent\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-DESKTOP from the source code\&.
