.TH "NotificationModule" 3 "Fri Sep 8 2023" "Version version:2.3" "LIBLINGMOSDK-DESKTOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NotificationModule
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-DESKTOP from the source code\&.
