#!/bin/sh

# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2021 Anupam Basak <anupam.basak27@gmail.com>


###
# Arg 1 : .env file
# Arg 2 : Path to script
###
source "$1"
exec "$2"
