.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 shicetu <shicetu@uniontech.com>,
.\"
.TH "deepin-camera" "1" "2021-1-28" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
deepin-camera \- package manager for deepin.
.SH DESCRIPTION
Package deepin-camera.deb is a tool to view camera, and also a smart take photo and video in life
.PP
Package Installer is an easy-to-use .deb package is an image and video capture utility using your PC camera or webcam tool.
.SH AUTHOR
.PP
.B deepin-camera
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT shicetu@\:uniontech.com
.ME
for the Debian Project (but may be used by others)
