# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/discover/libdiscover/backends/SnapBackend/libsnapclient/SnapMacaroonDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SnapMacaroonDialog(object):
    def setupUi(self, SnapMacaroonDialog):
        SnapMacaroonDialog.setObjectName("SnapMacaroonDialog")
        SnapMacaroonDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(SnapMacaroonDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(SnapMacaroonDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.label = QtWidgets.QLabel(SnapMacaroonDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.username = QtWidgets.QLineEdit(SnapMacaroonDialog)
        self.username.setObjectName("username")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.username)
        self.label_2 = QtWidgets.QLabel(SnapMacaroonDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.password = QtWidgets.QLineEdit(SnapMacaroonDialog)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.password)
        self.otpLabel = QtWidgets.QLabel(SnapMacaroonDialog)
        self.otpLabel.setTextFormat(QtCore.Qt.PlainText)
        self.otpLabel.setObjectName("otpLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.otpLabel)
        self.otp = QtWidgets.QLineEdit(SnapMacaroonDialog)
        self.otp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.otp.setObjectName("otp")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.otp)
        self.errorMessage = QtWidgets.QLabel(SnapMacaroonDialog)
        self.errorMessage.setText("")
        self.errorMessage.setWordWrap(True)
        self.errorMessage.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.errorMessage.setObjectName("errorMessage")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.errorMessage)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 119, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(SnapMacaroonDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SnapMacaroonDialog)
        self.buttonBox.accepted.connect(SnapMacaroonDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SnapMacaroonDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SnapMacaroonDialog)

    def retranslateUi(self, SnapMacaroonDialog):
        _translate = QtCore.QCoreApplication.translate
        SnapMacaroonDialog.setWindowTitle(_translate("SnapMacaroonDialog", "Dialog"))
        self.label_3.setText(_translate("SnapMacaroonDialog", "Log in to the <a href=\"https://login.ubuntu.com/\">Snap store</a>:"))
        self.label.setText(_translate("SnapMacaroonDialog", "Username:"))
        self.username.setPlaceholderText(_translate("SnapMacaroonDialog", "Username"))
        self.label_2.setText(_translate("SnapMacaroonDialog", "Password:"))
        self.password.setPlaceholderText(_translate("SnapMacaroonDialog", "Password"))
        self.otpLabel.setText(_translate("SnapMacaroonDialog", "Two-Factor:"))
