git clone https://github.com/linuxdeepin/dareader
git clone https://github.com/linuxdeepin/dcc-insider-plugin
git clone https://github.com/linuxdeepin/dde
git clone https://github.com/linuxdeepin/dde-account-faces
git clone https://github.com/linuxdeepin/dde-api-proxy
git clone https://github.com/linuxdeepin/dde-appearance
git clone https://github.com/linuxdeepin/dde-application-manager
git clone https://github.com/linuxdeepin/dde-application-wizard
git clone https://github.com/linuxdeepin/dde-app-services
git clone https://github.com/linuxdeepin/dde-calendar
git clone https://github.com/linuxdeepin/dde-clipboard
git clone https://github.com/linuxdeepin/dde-control-center
git clone https://github.com/linuxdeepin/dde-cooperation
git clone https://github.com/linuxdeepin/dde-daemon
git clone https://github.com/linuxdeepin/dde-device-formatter
git clone https://github.com/linuxdeepin/dde-display
git clone https://github.com/linuxdeepin/dde-dock
git clone https://github.com/linuxdeepin/dde-file-manager
git clone https://github.com/linuxdeepin/dde-file-manager-extensions
git clone https://github.com/linuxdeepin/dde-file-manager-external
git clone https://github.com/linuxdeepin/dde-grand-search
git clone https://github.com/linuxdeepin/dde-introduction
git clone https://github.com/linuxdeepin/dde-launcher
git clone https://github.com/linuxdeepin/dde-network-core
git clone https://github.com/linuxdeepin/dde-permission-manager
git clone https://github.com/linuxdeepin/dde-polkit-agent
git clone https://github.com/linuxdeepin/dde-printer
git clone https://github.com/linuxdeepin/dde-qt-dbus-factory
git clone https://github.com/linuxdeepin/dde-session
git clone https://github.com/linuxdeepin/dde-session-shell
git clone https://github.com/linuxdeepin/dde-session-ui
git clone https://github.com/linuxdeepin/dde-shell
git clone https://github.com/linuxdeepin/dde-tray-loader
git clone https://github.com/linuxdeepin/dde-wallpapers
git clone https://github.com/linuxdeepin/dde-wayland-config
git clone https://github.com/linuxdeepin/dde-widgets
git clone https://github.com/linuxdeepin/dde-wldpms
git clone https://github.com/linuxdeepin/dde-wloutput
git clone https://github.com/linuxdeepin/dde-wloutput-daemon
git clone https://github.com/linuxdeepin/ddm
git clone https://github.com/linuxdeepin/deepin-album
git clone https://github.com/linuxdeepin/deepin-boot-maker
git clone https://github.com/linuxdeepin/deepin-calculator
git clone https://github.com/linuxdeepin/deepin-camera
git clone https://github.com/linuxdeepin/deepin-clone
git clone https://github.com/linuxdeepin/deepin-compressor
git clone https://github.com/linuxdeepin/deepin-deb-installer
git clone https://github.com/linuxdeepin/deepin-deepinid-client
git clone https://github.com/linuxdeepin/deepin-deepinid-plugin
git clone https://github.com/linuxdeepin/deepin-defender
git clone https://github.com/linuxdeepin/deepin-desktop-base
git clone https://github.com/linuxdeepin/deepin-desktop-schemas
git clone https://github.com/linuxdeepin/deepin-desktop-theme
git clone https://github.com/linuxdeepin/deepin-devicemanager
git clone https://github.com/linuxdeepin/deepin-diskmanager
git clone https://github.com/linuxdeepin/deepin-downloader
git clone https://github.com/linuxdeepin/deepin-draw
git clone https://github.com/linuxdeepin/deepin-editor
git clone https://github.com/linuxdeepin/deepin-fcitx5configtool-plugin
git clone https://github.com/linuxdeepin/deepin-fcitxconfigtool-plugin
git clone https://github.com/linuxdeepin/deepin-feedback
git clone https://github.com/linuxdeepin/deepin-font-manager
git clone https://github.com/linuxdeepin/deepin-gettext-tools
git clone https://github.com/linuxdeepin/deepin-gomoku
git clone https://github.com/linuxdeepin/deepin-graphics-driver-manager
git clone https://github.com/linuxdeepin/deepin-gtk-theme
git clone https://github.com/linuxdeepin/deepin-icon-theme
git clone https://github.com/linuxdeepin/deepin-im
git clone https://github.com/linuxdeepin/deepin-image-viewer
git clone https://github.com/linuxdeepin/deepin-kglobalaccel
git clone https://github.com/linuxdeepin/deepin-kwin
git clone https://github.com/linuxdeepin/deepin-kwindowsystem
git clone https://github.com/linuxdeepin/deepin-log-viewer
git clone https://github.com/linuxdeepin/deepin-movie-reborn
git clone https://github.com/linuxdeepin/deepin-music
git clone https://github.com/linuxdeepin/deepin-ocr
git clone https://github.com/linuxdeepin/deepin-ocr-plugin-manager
git clone https://github.com/linuxdeepin/deepin-osconfig
git clone https://github.com/linuxdeepin/deepin-pc-manager
git clone https://github.com/linuxdeepin/deepin-pdfium
git clone https://github.com/linuxdeepin/deepin-picker
git clone https://github.com/linuxdeepin/deepin-reader
git clone https://github.com/linuxdeepin/deepin-screen-recorder
git clone https://github.com/linuxdeepin/deepin-screensaver
git clone https://github.com/linuxdeepin/deepin-service-manager
git clone https://github.com/linuxdeepin/deepin-shortcut-viewer
git clone https://github.com/linuxdeepin/deepin-sound-theme
git clone https://github.com/linuxdeepin/deepin-system-monitor
git clone https://github.com/linuxdeepin/deepin-system-upgrade
git clone https://github.com/linuxdeepin/deepin-terminal
git clone https://github.com/linuxdeepin/deepin-turbo
git clone https://github.com/linuxdeepin/deepin-tweak
git clone https://github.com/linuxdeepin/deepin-unioncode
git clone https://github.com/linuxdeepin/deepin-upgrade-manager
git clone https://github.com/linuxdeepin/deepin-voice-note
git clone https://github.com/linuxdeepin/deepin-wayland-protocols
git clone https://github.com/linuxdeepin/disomaster
git clone https://github.com/linuxdeepin/docparser
git clone https://github.com/linuxdeepin/dpa-ext-gnomekeyring
git clone https://github.com/linuxdeepin/dtk6core
git clone https://github.com/linuxdeepin/dtk6gui
git clone https://github.com/linuxdeepin/dtk6log
git clone https://github.com/linuxdeepin/dtk6systemsettings
git clone https://github.com/linuxdeepin/dtk6widget
git clone https://github.com/linuxdeepin/dtkaudiomanager
git clone https://github.com/linuxdeepin/dtkbluetooth
git clone https://github.com/linuxdeepin/dtkcore
git clone https://github.com/linuxdeepin/dtkdeclarative
git clone https://github.com/linuxdeepin/dtkdevice
git clone https://github.com/linuxdeepin/dtkgui
git clone https://github.com/linuxdeepin/dtkio
git clone https://github.com/linuxdeepin/dtklog
git clone https://github.com/linuxdeepin/dtknetworkmanager
git clone https://github.com/linuxdeepin/dtknotifications
git clone https://github.com/linuxdeepin/dtksystemsettings
git clone https://github.com/linuxdeepin/dtk-template
git clone https://github.com/linuxdeepin/dtkwidget
git clone https://github.com/linuxdeepin/dwayland
git clone https://github.com/linuxdeepin/gio-qt
git clone https://github.com/linuxdeepin/image-editor
git clone https://github.com/linuxdeepin/qt5integration
git clone https://github.com/linuxdeepin/qt5platform-plugins
git clone https://github.com/linuxdeepin/qt6integration
git clone https://github.com/linuxdeepin/qt6platform-plugins
git clone https://github.com/linuxdeepin/udisks2-qt5
git clone https://github.com/linuxdeepin/xdg-desktop-portal-dde
