#!/usr/bin/env bash

namcapdir=$(cd "$(dirname "$0")" && pwd)
PATH=$namcapdir:$PATH
export PARSE_PKGBUILD_PATH=$namcapdir
export PYTHONPATH=$namcapdir

"$namcapdir"/scripts/namcap -t "$namcapdir"/namcap-tags "$@"
