usr/share/dde-file-manager/translations/disk-encrypt*.qm

usr/lib/*/dde-file-manager/plugins/filemanager-edge/libdfmplugin_disk_encrypt.so*
usr/lib/*/dde-file-manager/plugins/filemanager-edge/libdfmplugin_encrypt_manager.so
usr/bin/deepin-diskencrypt-service

usr/share/dsg/configs/org.deepin.dde.file-manager/org.deepin.dde.file-manager.diskencrypt.json

usr/share/deepin-service-manager/other/deepin-diskencrypt-service.json
usr/share/dbus-1/system.d/org.deepin.filemanager.diskencrypt.conf
usr/share/dbus-1/system-services/org.deepin.Filemanager.DiskEncrypt.service
usr/share/polkit-1/actions/org.deepin.filemanager.diskencrypt.policy
etc/polkit-1/localauthority/10-vendor.d/99-dde-file-manager-encrypt.pkla
