#!/bin/bash

SRCDIR=`pwd`
SYSTEM=lingmo
mksquashfs ${SRCDIR}/rootfs ${SRCDIR}/iso/${SYSTEM}/x86_64/lingmosys.sfs -comp xz
grub-mkrescue  -iso-level 3 -full-iso9660-filenames -o ${SRCDIR}/iso/test.iso ${SRCDIR}/iso
