# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/plasma-nm/vpn/ssh/sshadvanced.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SshAdvanced(object):
    def setupUi(self, SshAdvanced):
        SshAdvanced.setObjectName("SshAdvanced")
        SshAdvanced.resize(597, 290)
        self.verticalLayout = QtWidgets.QVBoxLayout(SshAdvanced)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chk_useCustomGatewayPort = QtWidgets.QCheckBox(SshAdvanced)
        self.chk_useCustomGatewayPort.setObjectName("chk_useCustomGatewayPort")
        self.horizontalLayout.addWidget(self.chk_useCustomGatewayPort)
        self.sb_useCustomGatewayPort = QtWidgets.QSpinBox(SshAdvanced)
        self.sb_useCustomGatewayPort.setEnabled(False)
        self.sb_useCustomGatewayPort.setMinimum(0)
        self.sb_useCustomGatewayPort.setMaximum(65535)
        self.sb_useCustomGatewayPort.setProperty("value", 0)
        self.sb_useCustomGatewayPort.setObjectName("sb_useCustomGatewayPort")
        self.horizontalLayout.addWidget(self.sb_useCustomGatewayPort)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chk_useCustomTunnelMtu = QtWidgets.QCheckBox(SshAdvanced)
        self.chk_useCustomTunnelMtu.setObjectName("chk_useCustomTunnelMtu")
        self.horizontalLayout_2.addWidget(self.chk_useCustomTunnelMtu)
        self.sb_useCustomTunnelMtu = QtWidgets.QSpinBox(SshAdvanced)
        self.sb_useCustomTunnelMtu.setEnabled(False)
        self.sb_useCustomTunnelMtu.setMinimum(0)
        self.sb_useCustomTunnelMtu.setMaximum(999999999)
        self.sb_useCustomTunnelMtu.setObjectName("sb_useCustomTunnelMtu")
        self.horizontalLayout_2.addWidget(self.sb_useCustomTunnelMtu)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chk_extraSshOptions = QtWidgets.QCheckBox(SshAdvanced)
        self.chk_extraSshOptions.setObjectName("chk_extraSshOptions")
        self.horizontalLayout_3.addWidget(self.chk_extraSshOptions)
        self.le_extraSshOptions = QtWidgets.QLineEdit(SshAdvanced)
        self.le_extraSshOptions.setEnabled(False)
        self.le_extraSshOptions.setObjectName("le_extraSshOptions")
        self.horizontalLayout_3.addWidget(self.le_extraSshOptions)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.chk_remoteDeviceNumber = QtWidgets.QCheckBox(SshAdvanced)
        self.chk_remoteDeviceNumber.setObjectName("chk_remoteDeviceNumber")
        self.horizontalLayout_4.addWidget(self.chk_remoteDeviceNumber)
        self.sb_remoteDeviceNumber = QtWidgets.QSpinBox(SshAdvanced)
        self.sb_remoteDeviceNumber.setEnabled(False)
        self.sb_remoteDeviceNumber.setMaximum(999999999)
        self.sb_remoteDeviceNumber.setObjectName("sb_remoteDeviceNumber")
        self.horizontalLayout_4.addWidget(self.sb_remoteDeviceNumber)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.chk_useTapDevice = QtWidgets.QCheckBox(SshAdvanced)
        self.chk_useTapDevice.setObjectName("chk_useTapDevice")
        self.verticalLayout.addWidget(self.chk_useTapDevice)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.chk_remoteUsername = QtWidgets.QCheckBox(SshAdvanced)
        self.chk_remoteUsername.setObjectName("chk_remoteUsername")
        self.horizontalLayout_5.addWidget(self.chk_remoteUsername)
        self.le_remoteUsername = QtWidgets.QLineEdit(SshAdvanced)
        self.le_remoteUsername.setEnabled(False)
        self.le_remoteUsername.setObjectName("le_remoteUsername")
        self.horizontalLayout_5.addWidget(self.le_remoteUsername)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.chk_doNotReplaceDefaultRoute = QtWidgets.QCheckBox(SshAdvanced)
        self.chk_doNotReplaceDefaultRoute.setObjectName("chk_doNotReplaceDefaultRoute")
        self.verticalLayout.addWidget(self.chk_doNotReplaceDefaultRoute)

        self.retranslateUi(SshAdvanced)
        self.chk_useCustomGatewayPort.toggled['bool'].connect(self.sb_useCustomGatewayPort.setEnabled) # type: ignore
        self.chk_useCustomTunnelMtu.toggled['bool'].connect(self.sb_useCustomTunnelMtu.setEnabled) # type: ignore
        self.chk_extraSshOptions.toggled['bool'].connect(self.le_extraSshOptions.setEnabled) # type: ignore
        self.chk_remoteDeviceNumber.toggled['bool'].connect(self.sb_remoteDeviceNumber.setEnabled) # type: ignore
        self.chk_remoteUsername.toggled['bool'].connect(self.le_remoteUsername.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SshAdvanced)

    def retranslateUi(self, SshAdvanced):
        _translate = QtCore.QCoreApplication.translate
        self.chk_useCustomGatewayPort.setText(_translate("SshAdvanced", "Use custom gateway port:"))
        self.chk_useCustomTunnelMtu.setText(_translate("SshAdvanced", "Use custom tunnel Maximum Transmission Unit (MTU):"))
        self.chk_extraSshOptions.setText(_translate("SshAdvanced", "Extra SSH options:"))
        self.chk_remoteDeviceNumber.setText(_translate("SshAdvanced", "Remote device number:"))
        self.chk_useTapDevice.setText(_translate("SshAdvanced", "Use a TAP device"))
        self.chk_remoteUsername.setText(_translate("SshAdvanced", "Remote username"))
        self.chk_doNotReplaceDefaultRoute.setText(_translate("SshAdvanced", "Do not replace default route"))
