[Desktop Entry]
Name=PolicyKit Authentication Agent
Name[ar]=عميل استيثاق Policykit
Name[ast]=Axente d'autenticación de PolicyKit
Name[be]=Агент аўтэнтыфікацыі PolicyKit
Name[bg]=Агент за удостоверяване на PolicyKit
Name[ca]=Agent d'autenticació del PolicyKit
Name[ca@valencia]=Agent d'autenticació de PolicyKit
Name[cs]=Ověřovací agent PolicyKitu
Name[da]=PolicyKit autentificeringsagent
Name[de]=PolicyKit-Authentifizierungs-Agent
Name[el]=Πράκτορας ταυτοποίησης PolicyKit
Name[en_GB]=PolicyKit Authentication Agent
Name[eo]=PolicyKit Aŭtentiga Agento
Name[es]=Agente de autenticación de PolicyKit
Name[et]=PolicyKiti autentimisagent
Name[eu]=PolicyKit autentifikazio agentea
Name[fi]=PolicyKit-tunnistautumisagentti
Name[fr]=Agent d'authentification de « PolicyKit »
Name[gl]=Axente de autenticación de PolicyKit
Name[he]=סוכן אימות PolicyKit
Name[hsb]=PolicyKit Agent za awtentifikaciju
Name[hu]=PolicyKit hitelesítési ügynök
Name[ia]=Agente de Authentication PolicyKit
Name[id]=PolicyKit Authentication Agent
Name[ie]=Agente de autentication PolicyKit
Name[is]=PolicyKit auðkennisþjónn
Name[it]=Agente di autenticazione di PolicyKit
Name[ka]=PolicyKit -ის ავთენტიკაციის აგენტი
Name[ko]=PolicyKit 인증 에이전트
Name[lt]=PolicyKit tapatybės nustatymo agentas
Name[nl]=Authenticatieagent van PolicyKit
Name[nn]=PolicyKit-autentiseringsagent
Name[pa]=ਪਾਲਸੀਕਿਟ ਪਰਮਾਣਕਿਤਾ ਏਜੰਟ
Name[pl]=Usługa uwierzytelnienia PolicyKit
Name[pt]=Agente de Autenticação do PolicyKit
Name[pt_BR]=Agente de Autenticação do PolicyKit
Name[ro]=Agent de autentificare PolicyKit
Name[ru]=Агент аутентификации PolicyKit
Name[sa]=PolicyKit प्रमाणीकरण दूतः
Name[sk]=Agent overenia totožnosti PolicyKit
Name[sl]=Overitveni posrednik PolicyKit
Name[sr]=Полисикитов агент за аутентификовање
Name[sr@ijekavian]=Полисикитов агент за аутентификовање
Name[sr@ijekavianlatin]=PolicyKitov agent za autentifikovanje
Name[sr@latin]=PolicyKitov agent za autentifikovanje
Name[sv]=Policykit behörighetsmodul
Name[tg]=Омили санҷиши ҳаққонияти PolicyKit
Name[tr]=PolicyKit Kimlik Doğrulaması Aracı
Name[uk]=Агент розпізнавання PolicyKit
Name[vi]=Đại diện xác thực PolicyKit
Name[x-test]=xxPolicyKit Authentication Agentxx
Name[zh_CN]=PolicyKit 身份验证代理程序
Name[zh_TW]=PolicyKit 認證代理程式
Comment=PolicyKit Authentication Agent
Comment[ar]=عميل استيثاق Policykit
Comment[ast]=L'axente d'autenticación de PolicyKit
Comment[be]=Агент аўтэнтыфікацыі PolicyKit
Comment[bg]=Агент за удостоверяване на PolicyKit
Comment[ca]=Agent d'autenticació del PolicyKit
Comment[ca@valencia]=Agent d'autenticació de PolicyKit
Comment[cs]=Ověřovací agent PolicyKitu
Comment[da]=PolicyKit autentificeringsagent
Comment[de]=PolicyKit-Authentifizierungs-Agent
Comment[el]=Πράκτορας ταυτοποίησης PolicyKit
Comment[en_GB]=PolicyKit Authentication Agent
Comment[eo]=PolicyKit Aŭtentiga Agento
Comment[es]=Agente de autenticación de PolicyKit
Comment[et]=PolicyKiti autentimisagent
Comment[eu]=PolicyKit autentifikazio agentea
Comment[fi]=PolicyKit-tunnistautumisagentti
Comment[fr]=Agent d'authentification de « PolicyKit »
Comment[gl]=Axente de autenticación de PolicyKit.
Comment[he]=סוכן אימות PolicyKit
Comment[hsb]=PolicyKit dialog za awtentifikaciju
Comment[hu]=PolicyKit hitelesítési ügynök
Comment[ia]=PolicyKit Authentication Agent
Comment[id]=Agen Kewenangan PolicyKit
Comment[ie]=Agente de autentication PolicyKit
Comment[is]=PolicyKit auðkennisþjónn
Comment[it]=Agente di autenticazione di PolicyKit
Comment[ka]=PolicyKit -ის ავთენტიკაციის აგენტი
Comment[ko]=PolicyKit 인증 에이전트
Comment[lt]=PolicyKit tapatybės nustatymo agentas
Comment[nl]=Authenticatieagent van PolicyKit
Comment[nn]=PolicyKit-autentiseringsagent
Comment[pa]=ਪਾਲਸੀਕਿਟ ਪਰਮਾਣਕਿਤਾ ਏਜੰਟ
Comment[pl]=Usługa uwierzytelnienia PolicyKit
Comment[pt]=Agente de Autenticação do PolicyKit
Comment[pt_BR]=Agente de Autenticação do PolicyKit
Comment[ro]=Agent de autentificare PolicyKit
Comment[ru]=Агент аутентификации PolicyKit
Comment[sa]=PolicyKit प्रमाणीकरण दूतः
Comment[sk]=Agent overenia totožnosti PolicyKit
Comment[sl]=Overitveni posrednik PolicyKit
Comment[sr]=Полисикитов агент за аутентификовање
Comment[sr@ijekavian]=Полисикитов агент за аутентификовање
Comment[sr@ijekavianlatin]=PolicyKitov agent za autentifikovanje
Comment[sr@latin]=PolicyKitov agent za autentifikovanje
Comment[sv]=Policykit behörighetsmodul
Comment[tg]=Омили санҷиши ҳаққонияти PolicyKit
Comment[tr]=PolicyKit Kimlik Doğrulaması Aracı
Comment[uk]=Агент розпізнавання PolicyKit
Comment[vi]=Đại diện xác thực PolicyKit
Comment[x-test]=xxPolicyKit Authentication Agentxx
Comment[zh_CN]=PolicyKit 身份验证代理程序
Comment[zh_TW]=PolicyKit 認證代理程式
Exec=${KDE_INSTALL_FULL_LIBEXECDIR}/polkit-kde-authentication-agent-1
Icon=dialog-password
Terminal=false
Type=Application
OnlyShowIn=KDE;
X-KDE-StartupNotify=false
X-KDE-autostart-phase=0
NoDisplay=true
X-DBUS-StartupType=Unique
X-systemd-skip=true
