SOURCES += \
        $$PWD/homepagecheck/homepagemodule.cpp \
        $$PWD/homepagecheck/homepagecheckwidget.cpp \
        $$PWD/homepagecheck/homepagemodel.cpp \
        $$PWD/homepagecheck/sysupdatermodel.cpp \
        $$PWD/homepagecheck/homepage.cpp \
        $$PWD/homepagecheck/checkitem.cpp \
        $$PWD/safetyprotection/safetyprotectionmodule.cpp \
        $$PWD/safetyprotection/safetyprotectionwidget.cpp \
        $$PWD/cleaner/widgets/cleanerresultitemwidget.cpp \
        $$PWD/cleaner/cleanermodule.cpp \
        $$PWD/cleaner/trashcleanwidget.cpp \
        $$PWD/cleaner/trashcleanitem.cpp \
        $$PWD/cleaner/cleanerdbusadaptorimpl.cpp \
        $$PWD/securitytools/securitytoolswidget.cpp \
        $$PWD/securitytools/securitytoolsmodule.cpp \
        $$PWD/securitytools/startup/startupwidget.cpp \
        $$PWD/securitytools/internetcontrol/netcontrolwidget.cpp \
        $$PWD/securitytools/datausage/appdatadetaildialog.cpp \
        $$PWD/securitytools/datausage/datausagemodel.cpp \
        $$PWD/securitytools/datausage/datausagewidget.cpp \
        $$PWD/securitytools/datausage/flowwidget.cpp \
        $$PWD/securitytools/datausage/speedwidget.cpp \
        $$PWD/securitytools/datausage/dateusagewidgets/appdatachart.cpp \
        $$PWD/securitylog/securitylogdialog.cpp \
        $$PWD/securitylog/securitylogadaptorimpl.cpp \
        $$PWD/common/common.cpp \
        $$PWD/securitytools/usbconnection/usbconnectionwidget.cpp \
        $$PWD/securitytools/usbconnection/policykithelper.cpp \
        $$PWD/securitytools/usbconnection/usbconnectionwork.cpp \
        $$PWD/securitytools/usbconnection/widgets/usbinfolabel.cpp \
        $$PWD/securitytools/usbconnection/widgets/usbinfodialog.cpp \
        $$PWD/securitytools/loginsafety/loginsafetymodel.cpp \
        $$PWD/securitytools/loginsafety/loginsafetywidget.cpp \
        $$PWD/securitytools/loginsafety/pwdlimitlevelitem.cpp \
        $$PWD/securitytools/loginsafety/pwdlevelchangeddlg.cpp \
        $$PWD/common/invokers/dbusinvoker.cpp \
        $$PWD/common/invokers/deepindefendersettingsInvoker.cpp \
        $$PWD/common/invokers/invokerfactory.cpp

HEADERS += \
        $$PWD/homepagecheck/homepagemodule.h \
        $$PWD/homepagecheck/homepagecheckwidget.h \
        $$PWD/homepagecheck/homepagemodel.h \
        $$PWD/homepagecheck/sysupdatermodel.h \
        $$PWD/homepagecheck/homepage.h \
        $$PWD/homepagecheck/checkitem.h \
        $$PWD/safetyprotection/safetyprotectionmodule.h \
        $$PWD/safetyprotection/safetyprotectionwidget.h \
        $$PWD/cleaner/widgets/cleanerresultitemwidget.h\
        $$PWD/cleaner/cleanermodule.h \
        $$PWD/cleaner/trashcleanwidget.h \
        $$PWD/cleaner/trashcleanitem.h \
        $$PWD/cleaner/cleanerdbusadaptorinterface.h \
        $$PWD/cleaner/cleanerdbusadaptorimpl.h  \
        $$PWD/securitytools/securitytoolswidget.h \
        $$PWD/securitytools/securitytoolsmodule.h \
        $$PWD/securitytools/startup/startupwidget.h \
        $$PWD/securitytools/internetcontrol/netcontrolwidget.h \
        $$PWD/securitytools/datausage/appdatadetaildialog.h \
        $$PWD/securitytools/datausage/datausagemodel.h \
        $$PWD/securitytools/datausage/datausagewidget.h \
        $$PWD/securitytools/datausage/flowwidget.h \
        $$PWD/securitytools/datausage/speedwidget.h \
        $$PWD/securitytools/datausage/dateusagewidgets/appdatachart.h \
        $$PWD/securitylog/securitylogdialog.h \
        $$PWD/securitylog/securitylogadaptorinterface.h \
        $$PWD/securitylog/securitylogadaptorimpl.h \
        $$PWD/common/common.h \
        $$PWD/common/gsettingkey.h \
        $$PWD/common/compixmap.h \
        $$PWD/common/comdata.h \
        $$PWD/securitytools/usbconnection/usbconnectionwidget.h \
        $$PWD/securitytools/usbconnection/policykithelper.h \
        $$PWD/securitytools/usbconnection/usbconnectionwork.h \
        $$PWD/securitytools/usbconnection/widgets/usbinfolabel.h \
        $$PWD/securitytools/usbconnection/widgets/usbinfodialog.h \
        $$PWD/securitytools/loginsafety/loginsafetymodel.h \
        $$PWD/securitytools/loginsafety/loginsafetywidget.h \
        $$PWD/securitytools/loginsafety/pwdlimitlevelitem.h \
        $$PWD/securitytools/loginsafety/pwdlevelchangeddlg.h  \
        $$PWD/common/invokers/dbusinvoker.h \
        $$PWD/common/invokers/invokerinterface.h \
        $$PWD/common/invokers/deepindefendersettingsInvoker.h \
        $$PWD/common/invokers/invokerfactory.h
