# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/lingmo-vault/kded/ui/cryfscypherchooserwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CryfsCypherChooserWidget(object):
    def setupUi(self, CryfsCypherChooserWidget):
        CryfsCypherChooserWidget.setObjectName("CryfsCypherChooserWidget")
        CryfsCypherChooserWidget.resize(652, 62)
        self.verticalLayout = QtWidgets.QVBoxLayout(CryfsCypherChooserWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelCypher = QtWidgets.QLabel(CryfsCypherChooserWidget)
        self.labelCypher.setObjectName("labelCypher")
        self.verticalLayout.addWidget(self.labelCypher)
        self.comboCypher = QtWidgets.QComboBox(CryfsCypherChooserWidget)
        self.comboCypher.setObjectName("comboCypher")
        self.verticalLayout.addWidget(self.comboCypher)

        self.retranslateUi(CryfsCypherChooserWidget)
        QtCore.QMetaObject.connectSlotsByName(CryfsCypherChooserWidget)

    def retranslateUi(self, CryfsCypherChooserWidget):
        _translate = QtCore.QCoreApplication.translate
        self.labelCypher.setText(_translate("CryfsCypherChooserWidget", "Choose the used cipher:"))
