# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/lingmo-vault/kded/ui/directorychooserwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DirectoryChooserWidget(object):
    def setupUi(self, DirectoryChooserWidget):
        DirectoryChooserWidget.setObjectName("DirectoryChooserWidget")
        DirectoryChooserWidget.resize(653, 65)
        self.verticalLayout = QtWidgets.QVBoxLayout(DirectoryChooserWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelDevice = QtWidgets.QLabel(DirectoryChooserWidget)
        self.labelDevice.setObjectName("labelDevice")
        self.verticalLayout.addWidget(self.labelDevice)
        self.editMountPoint = KUrlRequester(DirectoryChooserWidget)
