# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/lingmo-vault/kded/ui/namechooserwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NameChooserWidget(object):
    def setupUi(self, NameChooserWidget):
        NameChooserWidget.setObjectName("NameChooserWidget")
        NameChooserWidget.resize(653, 64)
        self.verticalLayout = QtWidgets.QVBoxLayout(NameChooserWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelVaultName = QtWidgets.QLabel(NameChooserWidget)
        self.labelVaultName.setObjectName("labelVaultName")
        self.verticalLayout.addWidget(self.labelVaultName)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editVaultName = QtWidgets.QLineEdit(NameChooserWidget)
        self.editVaultName.setObjectName("editVaultName")
        self.horizontalLayout.addWidget(self.editVaultName)
        spacerItem = QtWidgets.QSpacerItem(313, 26, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelVaultName.setBuddy(self.editVaultName)

        self.retranslateUi(NameChooserWidget)
        QtCore.QMetaObject.connectSlotsByName(NameChooserWidget)

    def retranslateUi(self, NameChooserWidget):
        _translate = QtCore.QCoreApplication.translate
        self.labelVaultName.setText(_translate("NameChooserWidget", "Vaul&t name:"))
