# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/lingmo-vault/kded/ui/vaultimportingwizard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VaultImportingWizard(object):
    def setupUi(self, VaultImportingWizard):
        VaultImportingWizard.setObjectName("VaultImportingWizard")
        VaultImportingWizard.resize(646, 529)
        icon = QtGui.QIcon.fromTheme("lingmovault")
        VaultImportingWizard.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(VaultImportingWizard)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container = QtWidgets.QWidget(VaultImportingWizard)
        self.container.setObjectName("container")
        self.verticalLayout.addWidget(self.container)
        self.message = KMessageWidget(VaultImportingWizard)
        self.message.setCloseButtonVisible(False)
        self.message.setObjectName("message")
        self.verticalLayout.addWidget(self.message)
        self.buttons = QtWidgets.QDialogButtonBox(VaultImportingWizard)
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttons.setObjectName("buttons")
        self.verticalLayout.addWidget(self.buttons)

        self.retranslateUi(VaultImportingWizard)
        self.buttons.accepted.connect(VaultImportingWizard.accept) # type: ignore
        self.buttons.rejected.connect(VaultImportingWizard.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(VaultImportingWizard)

    def retranslateUi(self, VaultImportingWizard):
        _translate = QtCore.QCoreApplication.translate
        VaultImportingWizard.setWindowTitle(_translate("VaultImportingWizard", "Dialog"))
from kmessagewidget import KMessageWidget
