# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/wacomtablet/src/kcmodule/kcmwacomtabletwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KCMWacomTabletWidget(object):
    def setupUi(self, KCMWacomTabletWidget):
        KCMWacomTabletWidget.setObjectName("KCMWacomTabletWidget")
        KCMWacomTabletWidget.resize(646, 522)
        KCMWacomTabletWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.verticalLayout = QtWidgets.QVBoxLayout(KCMWacomTabletWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.tabletListLabel = QtWidgets.QLabel(KCMWacomTabletWidget)
        self.tabletListLabel.setObjectName("tabletListLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tabletListLabel)
        self.tabletListSelector = QtWidgets.QComboBox(KCMWacomTabletWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabletListSelector.sizePolicy().hasHeightForWidth())
        self.tabletListSelector.setSizePolicy(sizePolicy)
        self.tabletListSelector.setObjectName("tabletListSelector")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tabletListSelector)
        self.profileLabel = QtWidgets.QLabel(KCMWacomTabletWidget)
        self.profileLabel.setObjectName("profileLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.profileLabel)
        self.profileLayout = QtWidgets.QHBoxLayout()
        self.profileLayout.setObjectName("profileLayout")
        self.profileSelector = QtWidgets.QComboBox(KCMWacomTabletWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileSelector.sizePolicy().hasHeightForWidth())
        self.profileSelector.setSizePolicy(sizePolicy)
        self.profileSelector.setObjectName("profileSelector")
        self.profileLayout.addWidget(self.profileSelector)
        self.addProfileButton = KAnimatedButton(KCMWacomTabletWidget)
        self.addProfileButton.setText("")
        self.addProfileButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.addProfileButton.setProperty("animationPath", "document-new")
        self.addProfileButton.setObjectName("addProfileButton")
        self.profileLayout.addWidget(self.addProfileButton)
        self.delProfileButton = KAnimatedButton(KCMWacomTabletWidget)
        self.delProfileButton.setProperty("animationPath", "edit-delete-page")
        self.delProfileButton.setObjectName("delProfileButton")
        self.profileLayout.addWidget(self.delProfileButton)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.profileLayout)
        self.verticalLayout.addLayout(self.formLayout)
        self.deviceTabWidget = QtWidgets.QTabWidget(KCMWacomTabletWidget)
        self.deviceTabWidget.setDocumentMode(True)
        self.deviceTabWidget.setObjectName("deviceTabWidget")
        self.verticalLayout.addWidget(self.deviceTabWidget)
        self.tabletListLabel.setBuddy(self.tabletListSelector)
        self.profileLabel.setBuddy(self.profileSelector)

        self.retranslateUi(KCMWacomTabletWidget)
        QtCore.QMetaObject.connectSlotsByName(KCMWacomTabletWidget)
        KCMWacomTabletWidget.setTabOrder(self.profileSelector, self.addProfileButton)
        KCMWacomTabletWidget.setTabOrder(self.addProfileButton, self.delProfileButton)
        KCMWacomTabletWidget.setTabOrder(self.delProfileButton, self.deviceTabWidget)

    def retranslateUi(self, KCMWacomTabletWidget):
        _translate = QtCore.QCoreApplication.translate
        KCMWacomTabletWidget.setWindowTitle(_translate("KCMWacomTabletWidget", "Graphic Tablet Settings"))
        self.tabletListLabel.setText(_translate("KCMWacomTabletWidget", "&Select Tablet:"))
        self.profileLabel.setText(_translate("KCMWacomTabletWidget", "Select &Profile:"))
        self.addProfileButton.setToolTip(_translate("KCMWacomTabletWidget", "Creates a new default profile"))
        self.delProfileButton.setToolTip(_translate("KCMWacomTabletWidget", "Deletes the current profile"))
from kanimatedbutton import KAnimatedButton
