/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.lingmo.weather.xml -a dbusadaptor -c DbusAdaptor -l MainWindow
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef VPNDBUSADAPTOR_H
#define VPNDBUSADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include <QtDBus/QDBusMetaType>

#include "singlepage.h"
#include "../dbus-interface/lingmonetworkdeviceresource.h"
QT_BEGIN_NAMESPACE
class QByteArray;
//template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
template<class T> class QVector;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.lingmo.weather
 */

#include "vpnobject.h"

class VpnDbusAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.lingmo.vpnTool")
public:
    VpnDbusAdaptor(vpnObject *parent);
    virtual ~VpnDbusAdaptor();

    inline vpnObject *parent() const
    { return static_cast<vpnObject *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    //虚拟连接列表
    QVector<QStringList> getVirtualList();
    //刪除 根据网络名称 参数1 0:lan 1:wlan 参数2 为ssid/uuid
    Q_NOREPLY void deleteVpn(QString uuid);
    //连接 根据网卡类型 参数1 0:lan 1:wlan 参数3 为ssid/uuid
    Q_NOREPLY void activateVpn(const QString& connUuid);
    //断开连接 根据网卡类型 参数1 0:lan 1:wlan 参数3 为ssid/uuid
    Q_NOREPLY void deactivateVpn(const QString& connUuid);
    //just show
    void showLingmoVpn();

Q_SIGNALS: // SIGNALS
    void vpnAdd(QStringList info);
    void vpnRemove(QString dbusPath);
    void vpnUpdate(QStringList info);
    void vpnActiveConnectionStateChanged(QString uuid, int status);

    void activateFailed(QString errorMessage);
    void deactivateFailed(QString errorMessage);
};

#endif
