/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.lingmo.weather.xml -a VpnDbusAdaptor -c VpnDbusAdaptor -l MainWindow
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "vpndbusadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class VpnDbusAdaptor
 */

VpnDbusAdaptor::VpnDbusAdaptor(vpnObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    qDBusRegisterMetaType<QMap<QString, bool> >();
    qDBusRegisterMetaType<QMap<QString, int> >();
    qDBusRegisterMetaType<QVector<QStringList> >();
    //setAutoRelaySignals(true)后会自动转发mainwindow发出的同名信号，因此不必再额外写一个转发
    setAutoRelaySignals(true);
}

VpnDbusAdaptor::~VpnDbusAdaptor()
{
    // destructor
}

//虚拟连接列表
QVector<QStringList> VpnDbusAdaptor::getVirtualList()
{
    QVector<QStringList> vector;
    parent()->getVirtualList(vector);
    return vector;
}

//删除
void VpnDbusAdaptor::deleteVpn(QString uuid)
{
    qDebug()  << "delete vpn" << uuid;
    parent()->deleteVpn(uuid);
}

//连接 根据网卡类型 参数1 0:lan 1:wlan 参数3 为ssid/uuid
void VpnDbusAdaptor::activateVpn(const QString& connUuid)
{
    qDebug()  << "activate vpn" << connUuid;
    parent()->activateVpn(connUuid);
}

//断开连接 根据网卡类型 参数1 0:lan 1:wlan 参数3 为ssid/uuid
void VpnDbusAdaptor::deactivateVpn(const QString& connUuid)
{
    qDebug()  << "deactivate vpn" << connUuid;
    parent()->deactivateVpn(connUuid);
}

void VpnDbusAdaptor::showLingmoVpn()
{
    parent()->onShowMainWindow();
}
