# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/lingmo-nm/libs/editor/widgets/ui/ipv6routes.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RoutesIp6Config(object):
    def setupUi(self, RoutesIp6Config):
        RoutesIp6Config.setObjectName("RoutesIp6Config")
        RoutesIp6Config.resize(470, 356)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RoutesIp6Config.sizePolicy().hasHeightForWidth())
        RoutesIp6Config.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(RoutesIp6Config)
        self.gridLayout.setObjectName("gridLayout")
        self.tableViewAddresses = QtWidgets.QTableView(RoutesIp6Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewAddresses.sizePolicy().hasHeightForWidth())
        self.tableViewAddresses.setSizePolicy(sizePolicy)
        self.tableViewAddresses.setMinimumSize(QtCore.QSize(150, 50))
        self.tableViewAddresses.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableViewAddresses.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableViewAddresses.setShowGrid(True)
        self.tableViewAddresses.setGridStyle(QtCore.Qt.SolidLine)
        self.tableViewAddresses.setObjectName("tableViewAddresses")
        self.tableViewAddresses.horizontalHeader().setStretchLastSection(True)
        self.tableViewAddresses.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableViewAddresses, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(119, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButtonAdd = QtWidgets.QPushButton(RoutesIp6Config)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pushButtonAdd.setIcon(icon)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.gridLayout.addWidget(self.pushButtonAdd, 1, 1, 1, 1)
        self.pushButtonRemove = QtWidgets.QPushButton(RoutesIp6Config)
        self.pushButtonRemove.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.pushButtonRemove.setIcon(icon)
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.gridLayout.addWidget(self.pushButtonRemove, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.cbIgnoreAutoRoutes = QtWidgets.QCheckBox(RoutesIp6Config)
        self.cbIgnoreAutoRoutes.setObjectName("cbIgnoreAutoRoutes")
        self.gridLayout.addWidget(self.cbIgnoreAutoRoutes, 3, 0, 1, 1)
        self.cbNeverDefault = QtWidgets.QCheckBox(RoutesIp6Config)
        self.cbNeverDefault.setObjectName("cbNeverDefault")
        self.gridLayout.addWidget(self.cbNeverDefault, 4, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(RoutesIp6Config)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 1, 1, 2)

        self.retranslateUi(RoutesIp6Config)
        QtCore.QMetaObject.connectSlotsByName(RoutesIp6Config)

    def retranslateUi(self, RoutesIp6Config):
        _translate = QtCore.QCoreApplication.translate
        RoutesIp6Config.setWindowTitle(_translate("RoutesIp6Config", "Edit IPv6 Routes"))
        self.tableViewAddresses.setToolTip(_translate("RoutesIp6Config", "IP addresses identify your computer on the network. Click the \"Add\" button to add\n"
"an IP address"))
        self.pushButtonAdd.setText(_translate("RoutesIp6Config", "Add", "Insert a row"))
        self.pushButtonRemove.setText(_translate("RoutesIp6Config", "R&emove", "Remove a selected row"))
        self.cbIgnoreAutoRoutes.setToolTip(_translate("RoutesIp6Config", "If enabled, automatically configured routes are ignored and only routes specified above are used"))
        self.cbIgnoreAutoRoutes.setText(_translate("RoutesIp6Config", "Ignore automatically obtained routes"))
        self.cbNeverDefault.setToolTip(_translate("RoutesIp6Config", "If enabled, this connection will never be used as the default network connection"))
        self.cbNeverDefault.setText(_translate("RoutesIp6Config", "Use only for resources on this connection"))
