# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/lingmo-sdk/engineexplorer/serviceviewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServiceViewer(object):
    def setupUi(self, ServiceViewer):
        ServiceViewer.setObjectName("ServiceViewer")
        ServiceViewer.resize(405, 275)
        self.gridLayout = QtWidgets.QGridLayout(ServiceViewer)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.m_operations = KComboBox(ServiceViewer)
        self.m_operations.setEnabled(False)
        self.m_operations.setObjectName("m_operations")
        self.gridLayout.addWidget(self.m_operations, 4, 3, 2, 1)
        self.m_operationsLabel = QtWidgets.QLabel(ServiceViewer)
        self.m_operationsLabel.setEnabled(False)
        self.m_operationsLabel.setObjectName("m_operationsLabel")
        self.gridLayout.addWidget(self.m_operationsLabel, 4, 2, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(217, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 4, 1, 1)
        self.line = QtWidgets.QFrame(ServiceViewer)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 1, 4, 4)
        self.m_operationDescription = QtWidgets.QTableWidget(ServiceViewer)
        self.m_operationDescription.setEnabled(False)
        self.m_operationDescription.setObjectName("m_operationDescription")
        self.m_operationDescription.setColumnCount(2)
        self.m_operationDescription.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.m_operationDescription.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.m_operationDescription.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.m_operationDescription, 6, 0, 1, 5)
        self.m_operationStatus = QtWidgets.QLabel(ServiceViewer)
        self.m_operationStatus.setObjectName("m_operationStatus")
        self.gridLayout.addWidget(self.m_operationStatus, 7, 0, 1, 5)
        self.m_title = QtWidgets.QLabel(ServiceViewer)
        self.m_title.setText("Engine; Source; Service")
        self.m_title.setObjectName("m_title")
        self.gridLayout.addWidget(self.m_title, 0, 0, 2, 5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.m_operationsLabel.setBuddy(self.m_operations)

        self.retranslateUi(ServiceViewer)
        QtCore.QMetaObject.connectSlotsByName(ServiceViewer)

    def retranslateUi(self, ServiceViewer):
        _translate = QtCore.QCoreApplication.translate
        self.m_operationsLabel.setText(_translate("ServiceViewer", "Opera&tion:"))
        item = self.m_operationDescription.horizontalHeaderItem(0)
        item.setText(_translate("ServiceViewer", "Key"))
        item = self.m_operationDescription.horizontalHeaderItem(1)
        item.setText(_translate("ServiceViewer", "Value"))
        self.m_operationStatus.setText(_translate("ServiceViewer", "Operation count"))
from kcombobox import KComboBox
