.TH "KCustomProperty" 3 "Mon Sep 25 2023" "Version version:2.3" "LIBLINGMOSDK-DIAGNOSETEST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KCustomProperty \- 扩展属性，可为事件添加额外属性  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libkydatacollect\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBkey\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
扩展属性，可为事件添加额外属性 



.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-DIAGNOSETEST from the source code\&.
