.TH "KGlobalProperty" 3 "Mon Sep 25 2023" "Version version:2.3" "LIBLINGMOSDK-DIAGNOSETEST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KGlobalProperty \- 全局属性，由接口自动填充  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libkydatacollect\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBumid\fP"
.br
.ti -1c
.RI "char * \fBuserId\fP"
.br
.ti -1c
.RI "char * \fBsourceIp\fP"
.br
.ti -1c
.RI "char * \fBsourceMac\fP"
.br
.ti -1c
.RI "char * \fBserviceKey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
全局属性，由接口自动填充 



.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-DIAGNOSETEST from the source code\&.
