.TH "KTrackData" 3 "Mon Sep 25 2023" "Version version:2.3" "LIBLINGMOSDK-DIAGNOSETEST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KTrackData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBeventCode\fP"
.br
.ti -1c
.RI "KEventType \fBeventType\fP"
.br
.ti -1c
.RI "KEventSourceType \fBeventSourceType\fP"
.br
.ti -1c
.RI "long \fBtimeStamp\fP"
.br
.ti -1c
.RI "char * \fBpageName\fP"
.br
.ti -1c
.RI "char * \fBpageUrl\fP"
.br
.ti -1c
.RI "char * \fBpagePath\fP"
.br
.ti -1c
.RI "int \fBduration\fP"
.br
.ti -1c
.RI "char * \fBappName\fP"
.br
.ti -1c
.RI "char * \fBappVersion\fP"
.br
.ti -1c
.RI "char * \fBsearchWord\fP"
.br
.ti -1c
.RI "char * \fBentrancePageFlag\fP"
.br
.ti -1c
.RI "char * \fBexitPageFlag\fP"
.br
.ti -1c
.RI "char * \fBnewUserFlag\fP"
.br
.ti -1c
.RI "\fBKCustomProperty\fP * \fBcustomProperty\fP"
.br
.ti -1c
.RI "\fBKGlobalProperty\fP * \fBglobalProperty\fP"
.br
.ti -1c
.RI "int \fBcustomPropertyLength\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for LIBLINGMOSDK-DIAGNOSETEST from the source code\&.
