# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/plasma-nm/vpn/sstp/sstpwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SstpWidget(object):
    def setupUi(self, SstpWidget):
        SstpWidget.setObjectName("SstpWidget")
        SstpWidget.resize(469, 441)
        self.gridLayout_8 = QtWidgets.QGridLayout(SstpWidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox = QtWidgets.QGroupBox(SstpWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_gateway = QtWidgets.QLabel(self.groupBox)
        self.lbl_gateway.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_gateway.setObjectName("lbl_gateway")
        self.horizontalLayout_2.addWidget(self.lbl_gateway)
        self.le_gateway = QtWidgets.QLineEdit(self.groupBox)
        self.le_gateway.setObjectName("le_gateway")
        self.horizontalLayout_2.addWidget(self.le_gateway)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_advancedOption = QtWidgets.QPushButton(SstpWidget)
        self.btn_advancedOption.setObjectName("btn_advancedOption")
        self.horizontalLayout.addWidget(self.btn_advancedOption)
        self.gridLayout_8.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(SstpWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.lbl_username = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_username.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_username.setObjectName("lbl_username")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_username)
        self.le_username = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_username.setObjectName("le_username")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_username)
        self.lbl_password = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_password.setObjectName("lbl_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_password)
        self.le_password = PasswordField(self.groupBox_2)
        self.le_password.setProperty("passwordModeEnabled", True)
        self.le_password.setObjectName("le_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_password)
        self.lbl_ntDomain = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_ntDomain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_ntDomain.setObjectName("lbl_ntDomain")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_ntDomain)
        self.le_ntDomain = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_ntDomain.setObjectName("le_ntDomain")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_ntDomain)
        self.lbl_caCert = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_caCert.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_caCert.setObjectName("lbl_caCert")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_caCert)
        self.kurl_caCert = KUrlRequester(self.groupBox_2)
        self.kurl_caCert.setObjectName("kurl_caCert")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.kurl_caCert)
        self.chk_ignoreCertWarnings = QtWidgets.QCheckBox(self.groupBox_2)
        self.chk_ignoreCertWarnings.setObjectName("chk_ignoreCertWarnings")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.chk_ignoreCertWarnings)
        self.gridLayout_8.addWidget(self.groupBox_2, 1, 0, 1, 1)

        self.retranslateUi(SstpWidget)
        QtCore.QMetaObject.connectSlotsByName(SstpWidget)
        SstpWidget.setTabOrder(self.le_gateway, self.le_username)
        SstpWidget.setTabOrder(self.le_username, self.le_password)
        SstpWidget.setTabOrder(self.le_password, self.le_ntDomain)
        SstpWidget.setTabOrder(self.le_ntDomain, self.kurl_caCert)
        SstpWidget.setTabOrder(self.kurl_caCert, self.chk_ignoreCertWarnings)
        SstpWidget.setTabOrder(self.chk_ignoreCertWarnings, self.btn_advancedOption)

    def retranslateUi(self, SstpWidget):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("SstpWidget", "General"))
        self.lbl_gateway.setText(_translate("SstpWidget", "Gateway:"))
        self.btn_advancedOption.setText(_translate("SstpWidget", "Advanced…"))
        self.groupBox_2.setTitle(_translate("SstpWidget", "Optional"))
        self.lbl_username.setText(_translate("SstpWidget", "Username:"))
        self.lbl_password.setText(_translate("SstpWidget", "Password:"))
        self.lbl_ntDomain.setText(_translate("SstpWidget", "NT Domain:"))
        self.lbl_caCert.setText(_translate("SstpWidget", "CA Certificate:"))
        self.chk_ignoreCertWarnings.setText(_translate("SstpWidget", "Ignore certificate warnings"))
from kurlrequester import KUrlRequester
from passwordfield import PasswordField
