---
dontChroot: true
packagechooser_packagechooser:
    normal:
        - "ln -sf /run/live/medium/live/desktop.squashfs /run/live/medium/live/filesystem.squashfs"
    full:
        - "ln -sf /run/live/medium/live/desktop.squashfs /run/live/medium/live/filesystem.squashfs && touch /tmp/.full-install"
