---
mode: required
method: legacy

labels:
    step: "Installation Type"

items:
    - id: normal
      name: "Normal"
      name[zh_CN]: "常规安装"
      description: "Default Lingmo desktop experience."
      description[zh_CN]: "默认 Lingmo 桌面体验。"
      screenshot: ""
      packages: []
    - id: full
      name: "Full"
      name[zh_CN]: "增强版安装"
      description: "Lingmo desktop with extra applications and tools."
      description[zh_CN]: "Lingmo 桌面 + 额外应用和工具。"
      screenshot: ""
      packages: []
