# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/lingmo-workspace/containmentactions/applauncher/config.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName("Config")
        Config.resize(397, 123)
        self.verticalLayout = QtWidgets.QVBoxLayout(Config)
        self.verticalLayout.setObjectName("verticalLayout")
        self.showAppsByName = QtWidgets.QCheckBox(Config)
        self.showAppsByName.setObjectName("showAppsByName")
        self.verticalLayout.addWidget(self.showAppsByName)

        self.retranslateUi(Config)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        _translate = QtCore.QCoreApplication.translate
        self.showAppsByName.setText(_translate("Config", "Show applications by name"))
