#!/bin/sh
#    --mode debian \
# --archive-area "main contrib non-free non-free-firmware" \
set -e

lingmo-sys-build config noauto \
    --color \
    --mode debian \
    --architectures "$ARCH" \
    --binary-filesystem ext4 \
    --architecture amd64 \
    --archive-area "main contrib non-free non-free-firmware" \
    --bootappend-live "boot=live username=lingmo noautologin quiet splash" \
    --memtest memtest86+ \
    --distribution hydrogen \
    --parent-distribution hydrogen \
    --win32-loader true \
    --apt-recommends true \
    --cache-packages false \
    --firmware-binary true \
    --firmware-chroot true \
    --uefi-secure-boot enable \
    --initramfs live-boot \
    --linux-packages "linux-image linux-headers" \
    --linux-flavours "6.9.7-amd64" \
    --binary-images iso-hybrid \
    --debian-installer live \
    --debian-installer-gui true \
    --checksums md5 \
    --security false \
    --iso-application "LingmoOS" \
    --iso-publisher "LingmoOS Project" \
    --iso-volume "Lingmo OS Live" \
    --mirror-binary https://packages.lingmo.org/packages \
    --mirror-binary-security https://deb.debian.org/debian-security \
    --mirror-bootstrap https://packages.lingmo.org/packages \
    --mirror-chroot https://packages.lingmo.org/packages \
    --mirror-chroot-security https://deb.debian.org/debian-security \
    --mirror-debian-installer https://packages.lingmo.org/packages \
    --keyring-packages debian-keyring \
    --updates false \
    --security false \
    --clean
    "${@}"
# --debootstrap-options "--include=apt-transport-https,ca-certificates,openssl,gnupg,vim" \
#    --linux-packages "linux-image-6.7.4-amd64-unsigned linux-headers-6.7.4-amd64" \
#        --linux-flavours "6.7.4-amd64-unsigned" \
