#! /bin/sh
set -e

ICONDIR=/etc/X11/cursors

case "$1" in
    remove|deconfigure|failed-upgrade)
       update-alternatives --remove x-cursor-theme \
           $ICONDIR/lingmo-light-cursor.theme
       update-alternatives --remove x-cursor-theme \
           $ICONDIR/lingmo-dark-cursor.theme
    ;;
esac

#DEBHELPER#
