# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/plasma-nm/vpn/iodine/iodineauth.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IodineAuth(object):
    def setupUi(self, IodineAuth):
        IodineAuth.setObjectName("IodineAuth")
        IodineAuth.resize(408, 136)
        self.formLayout = QtWidgets.QFormLayout(IodineAuth)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.lbl_password = QtWidgets.QLabel(IodineAuth)
        self.lbl_password.setWordWrap(False)
        self.lbl_password.setObjectName("lbl_password")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_password)
        self.le_password = PasswordField(IodineAuth)
        self.le_password.setProperty("passwordModeEnabled", True)
        self.le_password.setObjectName("le_password")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_password)
        self.lbl_password.setBuddy(self.le_password)

        self.retranslateUi(IodineAuth)
        QtCore.QMetaObject.connectSlotsByName(IodineAuth)

    def retranslateUi(self, IodineAuth):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_password.setText(_translate("IodineAuth", "Password:"))
from passwordfield import PasswordField
