.TH "KDK_BIOS_GET_VENDOR" 3 "Thu Aug 14 2023" "Linux Programmer's Manual" \"
.SH NAME
kdk_bios_get_vendor - 获取bios厂商
.SH SYNOPSIS
.nf
.B #include <libkybios.h>
.sp
.BI "extern const char* kdk_bios_get_vendor();"
.sp
Link with \fI\-lkyhw\fP.
.SH "Detailed Description"
The main function of the interface is to obtain bios manufacturer
.SH "RETURN VALUE"
On success, returns  the bios manufacturer of type char*; The returned string needs to be released by 
.I free
.PP
On error, return
.BR NULL.
.SH EXAMPLES
.EX
#include <stdio.h>
#include "libkybios.h"
#include <stdlib.h>
.PP
int main()
{
    char *vendor = kdk_bios_get_vendor();
    char *version = kdk_bios_get_version();
    printf("vendor: %s", vendor);
    printf("version: %s",version);
    free(vendor);
    free(version);
    return 0;
}
.SH "CONFORMING TO"
These functions are as per the withdrawn POSIX.1e draft specification.
The following functions are Linux extensions:
.BR kdk_bios_get_version ().
and
.BR kdk_bios_free ().
.SH "SEE ALSO"
.BR kdk_bios_get_version (3).
and
.BR kdk_bios_free (3).