.TH "LIBKYBLUETOOTH" 3 "Fri Aug 25 2023" "Linux Programmer's Manual" \"
.SH NAME
kdk_bluetooth_get_device_id, kdk_bluetooth_get_manufacturer, kdk_bluetooth_get_dev_version,
kdk_bluetooth_get_name, kdk_bluetooth_get_address, kdk_bluetooth_get_link_mode, kdk_bluetooth_get_link_policy,
kdk_bluetooth_get_bus, kdk_bluetooth_get_scomtu, kdk_bluetooth_get_alcmtu, kdk_bluetooth_get_packettype,
kdk_bluetooth_get_features - 获取蓝牙信息
.SH SYNOPSIS
.nf
.B #include <libkybluetooth.h>
.sp
.BI "extern int** kdk_bluetooth_get_device_id();" 
.sp
.BI "extern char* kdk_bluetooth_get_manufacturer(int "num ");" 
.sp
.BI "extern char* kdk_bluetooth_get_dev_version(int "num ");" 
.sp
.BI "extern char* kdk_bluetooth_get_name(int "id ");" 
.sp
.BI "extern char* kdk_bluetooth_get_address(int "id ");"
.sp
.BI "extern char* kdk_bluetooth_get_link_mode(int "id ");"
.sp
.BI "extern char* kdk_bluetooth_get_link_policy(int "id ");"
.sp
.BI "extern char* kdk_bluetooth_get_bus(int "id ");"
.sp
.BI "extern char* kdk_bluetooth_get_scomtu(int "id ");"
.sp
.BI "extern char* kdk_bluetooth_get_alcmtu(int "id ");"
.sp
.BI "extern char* kdk_bluetooth_get_packettype(int "id ");"
.sp
.BI "extern char* kdk_bluetooth_get_features(int "id ");"
.sp
Link with \fI\-lkybluetooth\fP.
.SH "Detailed Description"
This library contains bluetooth information.
.SH "RETURN VALUE"
The return value is generally specific to the individual function called.
.SH "CONFORMING TO"
These functions are as per the withdrawn POSIX.1e draft specification.
The following functions are Linux extensions:
.BR kdk_bluetooth_get_device_id (),
.BR kdk_bluetooth_get_manufacturer (),
.BR kdk_bluetooth_get_dev_version (),
.BR kdk_bluetooth_get_name (),
.BR kdk_bluetooth_get_address (),
.BR kdk_bluetooth_get_link_mode (),
.BR kdk_bluetooth_get_link_policy (),
.BR kdk_bluetooth_get_bus (),
.BR kdk_bluetooth_get_scomtu (),
.BR kdk_bluetooth_get_alcmtu (),
.BR kdk_bluetooth_get_packettype ()
and
.BR kdk_bluetooth_get_features ().
.SH "SEE ALSO"
.BR kdk_bluetooth_get_device_id (3),
.BR kdk_bluetooth_get_manufacturer (3),
.BR kdk_bluetooth_get_dev_version (3),
.BR kdk_bluetooth_get_name (3),
.BR kdk_bluetooth_get_address (3),
.BR kdk_bluetooth_get_link_mode (3),
.BR kdk_bluetooth_get_link_policy (3),
.BR kdk_bluetooth_get_bus (3),
.BR kdk_bluetooth_get_scomtu (3),
.BR kdk_bluetooth_get_alcmtu (3),
.BR kdk_bluetooth_get_packettype (3)
and
.BR kdk_bluetooth_get_features (3).