.TH "LIBKYEDID" 3 "Fri Aug 25 2023" "Linux Programmer's Manual" \"
.SH NAME
kdk_edid_get_interface, kdk_edid_get_gamma, kdk_edid_get_size, kdk_edid_get_max_resolution,
kdk_edid_get_model, kdk_edid_get_visible_area, kdk_edid_get_manufacturer, kdk_edid_get_week,
kdk_edid_get_year, kdk_edid_get_primary, kdk_edid_get_resolution, kdk_edid_get_ratio, kdk_edid_get_character,
kdk_edid_freeall - 获取显示器信息
.SH SYNOPSIS
.nf
.B #include <libkyedid.h>
.sp
.BI "extern char** kdk_edid_get_interface();" 
.sp
.BI "extern float kdk_edid_get_gamma(char *"name ");" 
.sp
.BI "extern float kdk_edid_get_size(char *"name ");" 
.sp
.BI "extern char* kdk_edid_get_max_resolution(char *"name ");" 
.sp
.BI "extern char* kdk_edid_get_model(char *"name ");"
.sp
.BI "extern char* kdk_edid_get_visible_area(char *"name ");"
.sp
.BI "extern char* kdk_edid_get_manufacturer(char *"name ");"
.sp
.BI "extern int kdk_edid_get_week(char *"name ");"
.sp
.BI "extern int kdk_edid_get_year(char *"name ");"
.sp
.BI "extern int kdk_edid_get_primary(char *"name ");"
.sp
.BI "extern char* kdk_edid_get_resolution(char *"name ");"
.sp
.BI "extern char* kdk_edid_get_ratio(char *"name ");"
.sp
.BI "extern char* kdk_edid_get_character(char *"name ");"
.sp
.BI "extern inline void kdk_edid_freeall(char **"ptr ");"
.sp
Link with \fI\-lkyedid\fP.
.SH "Detailed Description"
This library contains bluetooth information.
.SH "RETURN VALUE"
The return value is generally specific to the individual function called.
.SH "CONFORMING TO"
These functions are as per the withdrawn POSIX.1e draft specification.
The following functions are Linux extensions:
.BR kdk_edid_get_interface (),
.BR kdk_edid_get_gamma (),
.BR kdk_edid_get_size (),
.BR kdk_edid_get_max_resolution (),
.BR kdk_edid_get_model (),
.BR kdk_edid_get_visible_area (),
.BR kdk_edid_get_manufacturer (),
.BR kdk_edid_get_week (),
.BR kdk_edid_get_year (),
.BR kdk_edid_get_primary (),
.BR kdk_edid_get_resolution (),
.BR kdk_edid_get_ratio (),
.BR kdk_edid_get_character ()
and
.BR kdk_edid_freeall ().
.SH "SEE ALSO"
.BR kdk_edid_get_interface (3),
.BR kdk_edid_get_gamma (3),
.BR kdk_edid_get_size (3),
.BR kdk_edid_get_max_resolution (3),
.BR kdk_edid_get_model (3),
.BR kdk_edid_get_visible_area (3),
.BR kdk_edid_get_manufacturer (3),
.BR kdk_edid_get_week (3),
.BR kdk_edid_get_year (3),
.BR kdk_edid_get_primary (3),
.BR kdk_edid_get_resolution (3),
.BR kdk_edid_get_ratio (3),
.BR kdk_edid_get_character (3)
and
.BR kdk_edid_freeall (3).