.TH "LIBKYFAN" 3 "Fri Aug 25 2023" "Linux Programmer's Manual" \"
.SH NAME
kdk_fan_get_information, kdk_fan_freeall - 获取风扇信息
.SH SYNOPSIS
.nf
.B #include <libkyfan.h>
.sp
.BI "extern char** kdk_fan_get_information();" 
.sp
.BI "extern inline void kdk_fan_freeall(char **"ptr ");" 
.sp
Link with \fI\-lkyfan\fP.
.SH "Detailed Description"
This library contains fan information.
.SH "RETURN VALUE"
The return value is generally specific to the individual function called.
.SH "CONFORMING TO"
These functions are as per the withdrawn POSIX.1e draft specification.
The following functions are Linux extensions:
.BR kdk_fan_get_information ()
and
.BR kdk_fan_freeall ().
.SH "SEE ALSO"
.BR kdk_fan_get_information (3)
and
.BR kdk_fan_freeall (3).