# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/kwallet/src/runtime/kwalletd/knewwalletdialogintro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KNewWalletDialogIntro(object):
    def setupUi(self, KNewWalletDialogIntro):
        KNewWalletDialogIntro.setObjectName("KNewWalletDialogIntro")
        KNewWalletDialogIntro.resize(341, 190)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(KNewWalletDialogIntro)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ktitlewidget = KTitleWidget(KNewWalletDialogIntro)
        self.ktitlewidget.setObjectName("ktitlewidget")
        self.verticalLayout_2.addWidget(self.ktitlewidget)
        self.labelIntro = QtWidgets.QLabel(KNewWalletDialogIntro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelIntro.sizePolicy().hasHeightForWidth())
        self.labelIntro.setSizePolicy(sizePolicy)
        self.labelIntro.setTextFormat(QtCore.Qt.RichText)
        self.labelIntro.setAlignment(QtCore.Qt.AlignVCenter)
        self.labelIntro.setWordWrap(True)
        self.labelIntro.setObjectName("labelIntro")
        self.verticalLayout_2.addWidget(self.labelIntro)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioBlowfish = QtWidgets.QRadioButton(KNewWalletDialogIntro)
        self.radioBlowfish.setObjectName("radioBlowfish")
        self.verticalLayout.addWidget(self.radioBlowfish)
        self.radioGpg = QtWidgets.QRadioButton(KNewWalletDialogIntro)
        self.radioGpg.setChecked(True)
        self.radioGpg.setObjectName("radioGpg")
        self.verticalLayout.addWidget(self.radioGpg)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(KNewWalletDialogIntro)
        self.radioBlowfish.toggled['bool'].connect(KNewWalletDialogIntro.onBlowfishToggled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(KNewWalletDialogIntro)

    def retranslateUi(self, KNewWalletDialogIntro):
        _translate = QtCore.QCoreApplication.translate
        self.ktitlewidget.setComment(_translate("KNewWalletDialogIntro", "The KDE Wallet System"))
        self.labelIntro.setText(_translate("KNewWalletDialogIntro", "<html><head/><body><p>The application \'<span style=\" font-weight:600;\">%1</span>\' has requested to open the KDE wallet. This is used to store sensitive data in a secure fashion. Please choose the new wallet\'s type below or click cancel to deny the application\'s request.</p></body></html>"))
        self.radioBlowfish.setText(_translate("KNewWalletDialogIntro", "Classic, blowfish encrypted file"))
        self.radioGpg.setText(_translate("KNewWalletDialogIntro", "Use GPG encryption, for better protection"))
from ktitlewidget import KTitleWidget
