# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/kwallet/src/runtime/kwalletd/kwalletwizardpageexplanation.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KWalletWizardPageExplanation(object):
    def setupUi(self, KWalletWizardPageExplanation):
        KWalletWizardPageExplanation.setObjectName("KWalletWizardPageExplanation")
        KWalletWizardPageExplanation.resize(478, 215)
        self.vboxlayout = QtWidgets.QVBoxLayout(KWalletWizardPageExplanation)
        self.vboxlayout.setObjectName("vboxlayout")
        self.textLabel2_3 = QtWidgets.QLabel(KWalletWizardPageExplanation)
        self.textLabel2_3.setTextFormat(QtCore.Qt.RichText)
        self.textLabel2_3.setWordWrap(True)
        self.textLabel2_3.setObjectName("textLabel2_3")
        self.vboxlayout.addWidget(self.textLabel2_3)

        self.retranslateUi(KWalletWizardPageExplanation)
        QtCore.QMetaObject.connectSlotsByName(KWalletWizardPageExplanation)

    def retranslateUi(self, KWalletWizardPageExplanation):
        _translate = QtCore.QCoreApplication.translate
        self.textLabel2_3.setText(_translate("KWalletWizardPageExplanation", "<html><head/><body><p>The KDE Wallet system stores your data in a <span style=\" font-style:italic;\">wallet</span> file on your local hard disk. The data is only written in the encrypted form of your choice - blowfish algorithm with your password as the key or using a GPG encryption key. When a wallet is opened, the wallet manager application will launch and display an icon in the system tray. You can use this application to manage all of your wallets. It even permits you to drag wallets and wallet contents, allowing you to easily copy a wallet to a remote system.</p></body></html>"))
