# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/print-manager/src/add-printer/ChooseSerial.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChooseSerial(object):
    def setupUi(self, ChooseSerial):
        ChooseSerial.setObjectName("ChooseSerial")
        ChooseSerial.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ChooseSerial.sizePolicy().hasHeightForWidth())
        ChooseSerial.setSizePolicy(sizePolicy)
        self.formLayout = QtWidgets.QFormLayout(ChooseSerial)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(ChooseSerial)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.baudRateCB = QtWidgets.QComboBox(ChooseSerial)
        self.baudRateCB.setObjectName("baudRateCB")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.baudRateCB)
        self.label_3 = QtWidgets.QLabel(ChooseSerial)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.parityCB = QtWidgets.QComboBox(ChooseSerial)
        self.parityCB.setObjectName("parityCB")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.parityCB)
        self.label_4 = QtWidgets.QLabel(ChooseSerial)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.bitsCB = QtWidgets.QComboBox(ChooseSerial)
        self.bitsCB.setObjectName("bitsCB")
        self.bitsCB.addItem("")
        self.bitsCB.setItemText(0, "8")
        self.bitsCB.addItem("")
        self.bitsCB.setItemText(1, "7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bitsCB)
        self.label_5 = QtWidgets.QLabel(ChooseSerial)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.flowCB = QtWidgets.QComboBox(ChooseSerial)
        self.flowCB.setObjectName("flowCB")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.flowCB)
        self.label_2.setBuddy(self.baudRateCB)
        self.label_3.setBuddy(self.parityCB)
        self.label_4.setBuddy(self.bitsCB)
        self.label_5.setBuddy(self.flowCB)

        self.retranslateUi(ChooseSerial)
        QtCore.QMetaObject.connectSlotsByName(ChooseSerial)

    def retranslateUi(self, ChooseSerial):
        _translate = QtCore.QCoreApplication.translate
        self.label_2.setText(_translate("ChooseSerial", "Baud Rate:", "@label:listbox"))
        self.label_3.setText(_translate("ChooseSerial", "Parity:", "@label:listbox"))
        self.label_4.setText(_translate("ChooseSerial", "Data Bits:", "@label:listbox"))
        self.label_5.setText(_translate("ChooseSerial", "Flow Control:", "@label:listbox"))
