# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/print-manager/src/add-printer/PageChoosePrinters.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageChoosePrinters(object):
    def setupUi(self, PageChoosePrinters):
        PageChoosePrinters.setObjectName("PageChoosePrinters")
        PageChoosePrinters.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PageChoosePrinters.sizePolicy().hasHeightForWidth())
        PageChoosePrinters.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(PageChoosePrinters)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.printerL = QtWidgets.QLabel(PageChoosePrinters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.printerL.sizePolicy().hasHeightForWidth())
        self.printerL.setSizePolicy(sizePolicy)
        self.printerL.setText("printer")
        self.printerL.setAlignment(QtCore.Qt.AlignCenter)
        self.printerL.setObjectName("printerL")
        self.verticalLayout.addWidget(self.printerL)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(PageChoosePrinters)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 2, 1, 1)
        self.vertLayout = QtWidgets.QVBoxLayout()
        self.vertLayout.setObjectName("vertLayout")
        self.label = QtWidgets.QLabel(PageChoosePrinters)
        self.label.setObjectName("label")
        self.vertLayout.addWidget(self.label)
        self.membersLV = ClassListWidget(PageChoosePrinters)
        self.membersLV.setObjectName("membersLV")
        self.vertLayout.addWidget(self.membersLV)
        self.gridLayout.addLayout(self.vertLayout, 0, 3, 1, 1)

        self.retranslateUi(PageChoosePrinters)
        QtCore.QMetaObject.connectSlotsByName(PageChoosePrinters)

    def retranslateUi(self, PageChoosePrinters):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("PageChoosePrinters", "Members:", "@label:listbox"))
from ClassListWidget import ClassListWidget
