# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/plasma-nm/vpn/openvpn/openvpn.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpenVPNProp(object):
    def setupUi(self, OpenVPNProp):
        OpenVPNProp.setObjectName("OpenVPNProp")
        OpenVPNProp.resize(495, 422)
        self.verticalLayout = QtWidgets.QVBoxLayout(OpenVPNProp)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.textLabel3 = QtWidgets.QLabel(OpenVPNProp)
        self.textLabel3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel3.setWordWrap(False)
        self.textLabel3.setObjectName("textLabel3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.textLabel3)
        self.gateway = QtWidgets.QLineEdit(OpenVPNProp)
        self.gateway.setClearButtonEnabled(True)
        self.gateway.setObjectName("gateway")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gateway)
        self.labelConnectionType = QtWidgets.QLabel(OpenVPNProp)
        self.labelConnectionType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelConnectionType.setWordWrap(False)
        self.labelConnectionType.setObjectName("labelConnectionType")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelConnectionType)
        self.cmbConnectionType = QtWidgets.QComboBox(OpenVPNProp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConnectionType.sizePolicy().hasHeightForWidth())
        self.cmbConnectionType.setSizePolicy(sizePolicy)
        self.cmbConnectionType.setObjectName("cmbConnectionType")
        self.cmbConnectionType.addItem("")
        self.cmbConnectionType.addItem("")
        self.cmbConnectionType.addItem("")
        self.cmbConnectionType.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbConnectionType)
        self.verticalLayout.addLayout(self.formLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(OpenVPNProp)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.formLayout_2 = QtWidgets.QFormLayout(self.page)
        self.formLayout_2.setContentsMargins(11, 11, 11, 11)
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.textLabel2 = QtWidgets.QLabel(self.page)
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName("textLabel2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.textLabel2)
        self.x509CaFile = KUrlRequester(self.page)
