#!/bin/sh

## live-build(7) - System Build Scripts
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

# Including common functions
[ -e "${LIVE_BUILD}/scripts/build.sh" ] && . "${LIVE_BUILD}/scripts/build.sh" || . /usr/lib/live/build.sh

# Setting static variables
DESCRIPTION="Copy live config into source"
USAGE="${PROGRAM} [--force]"

# Processing arguments and configuration files
Init_config_data "${@}"

if [ "${LB_SOURCE}" != "true" ]
then
	exit 0
fi

Echo_message "Begin copying live-build configuration..."

# Requiring stage file
Require_stagefiles config bootstrap

# Checking stage file
Check_stagefile

# Acquire lock file
Acquire_lockfile

# Remove old sources
if [ -d source/live ]
then
	rm -rf source/live
fi

# Copy system configuration
mkdir -p source/live
cp -a config source/live

if Find_files auto/*
then
	cp -a auto source/live
fi

# Creating readme file
cat > source/live/README.txt << EOF
The config files in this directory are a copy of those that were used by the
live-build tool to build this disc and the "live" disc for which this "source"
disc is a companion. (This disc contains the source code corresponding to the
packages used in the "live" disc).
EOF

# Creating stage file
Create_stagefile
