#!/bin/sh

## live-build(7) - System Build Scripts
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

# Including common functions
[ -e "${LIVE_BUILD}/scripts/build.sh" ] && . "${LIVE_BUILD}/scripts/build.sh" || . /usr/lib/live/build.sh

# Setting static variables
DESCRIPTION="Create source checksums"
USAGE="${PROGRAM} [--force]"

# Processing arguments and configuration files
Init_config_data "${@}"

if [ "${LB_CHECKSUMS}" = "none" ] || [ "${LB_SOURCE}" != "true" ]
then
	exit 0
fi

# Requiring stage file
Require_stagefiles config source_debian

# Checking stage file
Check_stagefile

# Acquire lock file
Acquire_lockfile

for DIRECTORY in source/debian source/live
do
	if [ ! -d ${DIRECTORY} ]
	then
		continue
	fi

	for CHECKSUM in ${LB_CHECKSUMS}
	do
		CHECKSUMS="${CHECKSUM}sum.txt"

		Echo_message "Begin creating source ${CHECKSUMS}..."

		# Remove old checksums
		if [ -f ${DIRECTORY}/${CHECKSUMS} ]
		then
			rm -f ${DIRECTORY}/${CHECKSUMS}
		fi

		# Calculating checksums
		cd ${DIRECTORY}
		find . -type f \
			\! -path './*SUMS' \
			\! -path './*sum.txt' \
			\! -path './*sum.README' \
		-print0 | sort -z | xargs -0 ${CHECKSUM}sum > ${CHECKSUMS}

cat > ${CHECKSUM}sum.README << EOF
The file ${CHECKSUMS} contains the ${CHECKSUM} checksums of all files on this medium.

You can verify them automatically with the 'verify-checksums' boot parameter,
or, manually with: '${CHECKSUM}sum -c ${CHECKSUMS}'.
EOF

		cd "${OLDPWD}"
	done

	# File list
	cd ${DIRECTORY}
	find . | sed -e 's|^.||g' | grep "^/" | sort > ../../${LB_IMAGE_NAME}-source.$(basename ${DIRECTORY}).contents
	cd "${OLDPWD}"
done

# Creating stage file
Create_stagefile
