#!/bin/sh

## live-build(7) - System Build Scripts
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

# Including common functions
[ -e "${LIVE_BUILD}/scripts/build.sh" ] && . "${LIVE_BUILD}/scripts/build.sh" || . /usr/lib/live/build.sh

# Setting static variables
DESCRIPTION="Install disk information into source"
USAGE="${PROGRAM} [--force]"

# Processing arguments and configuration files
Init_config_data "${@}"

case "${LB_SOURCE_IMAGES}" in
	iso*|hdd*)
		;;

	*)
		exit 0
		;;
esac

Echo_message "Begin installing disk information..."

# Requiring stage file
Require_stagefiles config bootstrap

# Checking stage file
Check_stagefile

# Acquire lock file
Acquire_lockfile

mkdir -p source/.disk

DISTRIBUTION="$(echo ${LB_DISTRIBUTION_BINARY} | cut -b 1 | tr '[a-z]' '[A-Z]')"
DISTRIBUTION="${DISTRIBUTION}$(echo ${LB_DISTRIBUTION_BINARY} | cut -b 2-)"

if [ -e chroot/etc/os-release ]
then
	VERSION="$(. chroot/etc/os-release && echo ${VERSION_ID})"
fi

VERSION="${VERSION:-none}"

case "${LB_MODE}" in
	debian)
		TITLE="Debian GNU/Linux"
		STRING="Official Snapshot ${ARCHITECTURE}"
		TRACE="project/trace/ftp-master.debian.org"
		;;

	*)
		TITLE="Debian GNU/Linux"
		STRING="Snapshot ${ARCHITECTURE}"
		TRACE=""
		;;
esac

if [ -n "${TRACE}" ]
then
	case "${LB_DERIVATIVE}" in
		true)
			echo "$(echo ${LB_PARENT_MIRROR_BOOTSTRAP} | awk -F:// '{ print $2 }'): $(wget -q ${LB_PARENT_MIRROR_BOOTSTRAP}/${TRACE} -O - | head -n 1)" \
			> source/.disk/archive_trace

			echo "$(echo ${LB_MIRROR_BOOTSTRAP} | awk -F:// '{ print $2 }'): $(wget -q ${LB_MIRROR_BOOTSTRAP}/${TRACE} -O - | head -n 1)" \
			>> source/.disk/archive_trace
			;;

		false)
			echo "$(wget -q ${LB_PARENT_MIRROR_BOOTSTRAP}/${TRACE} -O - | head -n 1)" \
			> source/.disk/archive_trace
			;;
	esac
fi

_DATE="$(date $DATE_UTC_OPTION -d@${SOURCE_DATE_EPOCH} +%Y%m%d-%H:%M)"

case "${LB_DEBIAN_INSTALLER}" in
	cdrom)
		echo "${TITLE} ${VERSION} \"${DISTRIBUTION}\" - ${STRING} LIVE/CD Source ${_DATE}" > source/.disk/info
		;;

	netinst)
		echo "${TITLE} ${VERSION} \"${DISTRIBUTION}\" - ${STRING} LIVE/NETINST Source ${_DATE}" > source/.disk/info
		;;

	netboot)
		echo "${TITLE} ${VERSION} \"${DISTRIBUTION}\" - ${STRING} LIVE/NETBOOT Source ${_DATE}" > source/.disk/info
		;;

	live)
		echo "${TITLE} ${VERSION} \"${DISTRIBUTION}\" - ${STRING} LIVE/INSTALL Source ${_DATE}" > source/.disk/info
		;;

	businesscard)
		echo "${TITLE} ${VERSION} \"${DISTRIBUTION}\" - ${STRING} LIVE/BC Source ${_DATE}" > source/.disk/info
		;;

	none)
		echo "${TITLE} ${VERSION} \"${DISTRIBUTION}\" - ${STRING} LIVE Source ${_DATE}" > source/.disk/info
		;;
esac

# Creating stage file
Create_stagefile
