#ifndef LINGMOSDKSOUNDEFFECTS_GLOBAL_H
#define LINGMOSDKSOUNDEFFECTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LINGMOSDKSOUNDEFFECTS_LIBRARY)
#  define LINGMOSDKSOUNDEFFECTS_EXPORT Q_DECL_EXPORT
#else
#  define LINGMOSDKSOUNDEFFECTS_EXPORT Q_DECL_IMPORT
#endif

#endif // LINGMOSDKSOUNDEFFECTS_GLOBAL_H
