[[flavour]]
name = 'powerpc64'
[flavour.build]
config = [
  'kernelarch-powerpc/config-arch-64',
  'kernelarch-powerpc/config-arch-64-be',
]
[flavour.defs]
is_default = true
[flavour.description]
hardware = '64-bit PowerPC with 4k pages'
[flavour.packages]
installer = true

[[flavour]]
name = 'powerpc64-64k'
[flavour.build]
config = [
  'kernelarch-powerpc/config-arch-64',
  'kernelarch-powerpc/config-arch-64-be',
  'kernelarch-powerpc/config-page-64k',
]
[flavour.description]
hardware = '64-bit PowerPC with 64k pages'

[[featureset]]
name = 'none'

[build]
kernel_file = 'vmlinux'
kernel_stem = 'vmlinux'

[relations.image]
suggests = [
  'mkvmlinuz',
  'grub-ieee1275',
]
