.TH "LIBKYRTINFO" 3 "Mon Sep 18 2023" "Linux Programmer's Manual" \"
.SH NAME
kdk_rti_get_mem_res_total_KiB, kdk_rti_get_mem_res_usage_percent, kdk_rti_get_mem_res_usage_KiB,
kdk_rti_get_mem_res_available_KiB, kdk_rti_get_mem_res_free_KiB, kdk_rti_get_mem_virt_alloc_KiB,
kdk_rti_get_mem_swap_total_KiB, kdk_rti_get_mem_swap_usage_percent, kdk_rti_get_mem_swap_usage_KiB,
kdk_rti_get_mem_swap_free_KiB, kdk_rti_get_cpu_current_usage, kdk_rti_get_uptime, kdk_get_process_name,
kdk_get_process_id, kdk_get_process_cpu_usage_percent, kdk_get_process_mem_usage_percent, kdk_get_process_status,
kdk_get_process_port, kdk_get_process_start_time, kdk_get_process_running_time, kdk_get_process_cpu_time,
kdk_get_process_command, kdk_get_process_user, kdk_procname_get_process_infomation, kdk_get_process_all_information,
kdk_proc_freeall  - 获取当前系统资源占用信息
.SH SYNOPSIS
.nf
.B #include <libkyrtinfo.h>
.sp
.BI "extern unsigned long kdk_rti_get_mem_res_total_KiB();" 
.sp
.BI "extern float kdk_rti_get_mem_res_usage_percent();" 
.sp
.BI "extern unsigned long kdk_rti_get_mem_res_usage_KiB();" 
.sp
.BI "extern unsigned long kdk_rti_get_mem_res_available_KiB();" 
.sp
.BI "extern unsigned long kdk_rti_get_mem_res_free_KiB();" 
.sp
.BI "extern unsigned long kdk_rti_get_mem_virt_alloc_KiB();" 
.sp
.BI "extern unsigned long kdk_rti_get_mem_swap_total_KiB();" 
.sp
.BI "extern float kdk_rti_get_mem_swap_usage_percent();" 
.sp
.BI "extern unsigned long kdk_rti_get_mem_swap_usage_KiB();" 
.sp
.BI "extern unsigned long kdk_rti_get_mem_swap_free_KiB();" 
.sp
.BI "extern float kdk_rti_get_cpu_current_usage();" 
.sp
.BI "extern int kdk_rti_get_uptime(unsigned int *"day ", unsigned int *"hour ", unsigned int *"min ", unsigned int *"sec ");" 
.sp
.nf
.B #include <libkyprocess.h>
.sp
.BI "extern char* kdk_get_process_name(int "proc_num ");" 
.sp
.BI "extern int kdk_get_process_id(char *"proc_name ");" 
.sp
.BI "extern float kdk_get_process_cpu_usage_percent(int "proc_num");" 
.sp
.BI "extern float kdk_get_process_mem_usage_percent(int "proc_num ");" 
.sp
.BI "extern char* kdk_get_process_status(int "proc_num ");" 
.sp
.BI "extern int kdk_get_process_port(int "proc_num ");" 
.sp
.BI "extern char* kdk_get_process_start_time(int "proc_num ");" 
.sp
.BI "extern char* kdk_get_process_running_time(int "proc_num ");" 
.sp
.BI "extern char* kdk_get_process_cpu_time(int "proc_num ");" 
.sp
.BI "extern char* kdk_get_process_command(int "proc_num ");" 
.sp
.BI "extern char* kdk_get_process_user(int "proc_num ");" 
.sp
.BI "extern char** kdk_procname_get_process_infomation(char *"proc_name ");" 
.sp
.BI "extern char** kdk_get_process_all_information();" 
.sp
.BI "extern inline void kdk_proc_freeall(char **"ptr ");"
.sp
Link with \fI\-lkyrtinfo\fP.
.SH "Detailed Description"
This library contains current system resource consumption information.
.SH "RETURN VALUE"
The return value is generally specific to the individual function called.
.SH "CONFORMING TO"
These functions are as per the withdrawn POSIX.1e draft specification.
The following functions are Linux extensions:
.BR kdk_rti_get_mem_res_total_KiB ()
and
.BR kdk_get_process_name ().
.SH "SEE ALSO"
.BR kdk_rti_get_mem_res_total_KiB (3)
and
.BR kdk_get_process_name (3).