# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/liblingmo/examples/testcontainmentactionsplugin/config.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName("Config")
        Config.resize(355, 100)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Config)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Config)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.text = QtWidgets.QLineEdit(Config)
        self.text.setObjectName("text")
        self.horizontalLayout.addWidget(self.text)

        self.retranslateUi(Config)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Config", "Text:"))
