#!/usr/bin/perl
# Connect a virtual CD after linux has booted from disk.
use Expect;

my $exp = new Expect;
$exp->debug(2);
$exp->exp_internal(1);
$exp->raw_pty(1);
$exp->spawn($ENV{CONSOLECOMMAND}) or die "failed to run CONSOLECOMMAND";

$exp->expect(360, '-re', 'Uncomp.*Linux') or die "failed to boot linux";
system("hp-ilo connect_cd");
