/usr/bin/downloader
/usr/bin/dlmextensionservice
translations/*.qm /usr/share/downloader/translations
assets/* /usr/share/deepin-manual/manual-assets/application/
desktop/downloader.desktop /usr/share/applications
data/downloader.db /usr/share/downloader/database
data/downloader.svg /usr/share/icons/hicolor/scalable/apps
data/downloader.svg /usr/share/downloader/icons/logo
docs/aria2.conf /usr/share/downloader/config
docs/config.conf /usr/share/downloader/config
docs/content-type.conf /usr/share/downloader/config
docs/httpAdvanced.json /usr/share/downloader/config
docs/content-type.conf /usr/share/downloader/config
docs/browser.downloader.autostart.json /etc/browser/native-messaging-hosts
/usr/libexec/openconnect/startdlmservice.sh
docs/ojlicckikdkkaclkpdddijgehekpmmbg.crx /usr/share/downloader/extension
docs/info.json /usr/share/downloader/extension
