if systemctl is-active --quiet lingmosdk-dbus.service; then
    echo "lingmosdk-dbus.service is active, restarting..."
    systemctl restart lingmosdk-dbus.service
else
    echo "lingmosdk-dbus.service is not active"
fi

if systemctl is-active --quiet lingmosdk-net.service; then
    echo "lingmosdk-net.service is active, restarting..."
    systemctl restart lingmosdk-net.service
else
    echo "lingmosdk-net.service is not active"
fi
