bin/systime usr/bin/
src/systemtime/com.lingmo.lingmosdk.TimeServer.conf etc/dbus-1/system.d/
src/systemtime/lingmosdk-systime.service lib/systemd/system/
src/systemtime/lingmosdk-systime-date.desktop etc/xdg/autostart/
bin/sdk-date usr/bin/
usr/lib/*/libkydate.so*
src/systemtime/dateform.conf /etc/kydate/
po/zh_CN.mo usr/share/locale/zh_CN/LC_MESSAGES/
po/bo_CN.mo usr/share/locale/bo_CN/LC_MESSAGES/
po/mn.mo usr/share/locale/mn/LC_MESSAGES/
po/zh_HK.mo usr/share/locale/zh_HK/LC_MESSAGES/
po/kk.mo usr/share/locale/kk/LC_MESSAGES/
po/ky.mo usr/share/locale/ky/LC_MESSAGES/
po/de.mo usr/share/locale/de/LC_MESSAGES/
po/es.mo usr/share/locale/es/LC_MESSAGES/
po/fr.mo usr/share/locale/fr/LC_MESSAGES/
po/ug.mo usr/share/locale/ug/LC_MESSAGES/