usr/include/lingmosdk/lingmosdk-system/libkync.h
usr/include/lingmosdk/lingmosdk-system/libkycpu.h
usr/include/lingmosdk/lingmosdk-system/libkyprinter.h
usr/include/lingmosdk/lingmosdk-system/libkybios.h
usr/include/lingmosdk/lingmosdk-system/libkyboard.h
usr/include/lingmosdk/lingmosdk-system/libkyusb.h
usr/include/lingmosdk/lingmosdk-system/libkybluetooth.h
usr/include/lingmosdk/lingmosdk-system/libkydisplay.h
usr/include/lingmosdk/lingmosdk-system/libkyedid.h
usr/include/lingmosdk/lingmosdk-system/libkyfan.h
usr/include/lingmosdk/lingmosdk-system/libkyhw.h
development-files/lingmosdk-hardware.pc usr/share/pkgconfig/
