usr/lib/*/libkyhw.so*
usr/lib/*/libkybluetooth.so*
usr/lib/*/libkyedid.so*
usr/lib/*/libkyfan.so*
usr/lib/*/libkyhwinfo.so*
po/lingmosdk-hardware_zh_CN.mo usr/share/locale/zh_CN/LC_MESSAGES/
po/lingmosdk-hardware_bo_CN.mo usr/share/locale/bo_CN/LC_MESSAGES/
po/lingmosdk-hardware_mn.mo usr/share/locale/mn/LC_MESSAGES/
po/lingmosdk-hardware_zh_HK.mo usr/share/locale/zh_HK/LC_MESSAGES/
po/lingmosdk-hardware_kk.mo usr/share/locale/kk/LC_MESSAGES/
po/lingmosdk-hardware_ky.mo usr/share/locale/ky/LC_MESSAGES/
po/lingmosdk-hardware_de.mo usr/share/locale/de/LC_MESSAGES/
po/lingmosdk-hardware_es.mo usr/share/locale/es/LC_MESSAGES/
po/lingmosdk-hardware_fr.mo usr/share/locale/fr/LC_MESSAGES/
po/lingmosdk-hardware_ug.mo usr/share/locale/ug/LC_MESSAGES/