check_env=`systemd-detect-virt`
echo $check_env
if [ $check_env = "docker" ];then
        echo "docker env do not start lingmosdk-systime.service"
else
	systemctl daemon-reload
	systemctl enable lingmosdk-systime.service
	systemctl restart lingmosdk-systime.service
fi

mv /usr/share/locale/zh_CN/LC_MESSAGES/zh_CN.mo /usr/share/locale/zh_CN/LC_MESSAGES/lingmosdk-date.mo || true
mv /usr/share/locale/bo_CN/LC_MESSAGES/bo_CN.mo /usr/share/locale/bo_CN/LC_MESSAGES/lingmosdk-date.mo || true
mv /usr/share/locale/mn/LC_MESSAGES/mn.mo /usr/share/locale/mn/LC_MESSAGES/lingmosdk-date.mo || true
mv /usr/share/locale/zh_HK/LC_MESSAGES/zh_HK.mo /usr/share/locale/zh_HK/LC_MESSAGES/lingmosdk-date.mo || true
mv /usr/share/locale/kk/LC_MESSAGES/kk.mo /usr/share/locale/kk/LC_MESSAGES/lingmosdk-date.mo || true
mv /usr/share/locale/ky/LC_MESSAGES/ky.mo /usr/share/locale/ky/LC_MESSAGES/lingmosdk-date.mo || true
mv /usr/share/locale/de/LC_MESSAGES/de.mo /usr/share/locale/de/LC_MESSAGES/lingmosdk-date.mo || true
mv /usr/share/locale/es/LC_MESSAGES/es.mo /usr/share/locale/es/LC_MESSAGES/lingmosdk-date.mo || true
mv /usr/share/locale/fr/LC_MESSAGES/fr.mo /usr/share/locale/fr/LC_MESSAGES/lingmosdk-date.mo || true
mv /usr/share/locale/ug/LC_MESSAGES/ug.mo /usr/share/locale/ug/LC_MESSAGES/lingmosdk-date.mo || true