mv /usr/share/locale/mn/LC_MESSAGES/lingmosdk-sysinfo_mn.mo /usr/share/locale/mn/LC_MESSAGES/lingmosdk-sysinfo.mo || true
mv /usr/share/locale/zh_CN/LC_MESSAGES/lingmosdk-sysinfo_zh_CN.mo /usr/share/locale/zh_CN/LC_MESSAGES/lingmosdk-sysinfo.mo || true
mv /usr/share/locale/bo_CN/LC_MESSAGES/lingmosdk-sysinfo_bo_CN.mo /usr/share/locale/bo_CN/LC_MESSAGES/lingmosdk-sysinfo.mo || true
mv /usr/share/locale/zh_HK/LC_MESSAGES/lingmosdk-sysinfo_zh_HK.mo /usr/share/locale/zh_HK/LC_MESSAGES/lingmosdk-sysinfo.mo || true
mv /usr/share/locale/kk/LC_MESSAGES/lingmosdk-sysinfo_kk.mo /usr/share/locale/kk/LC_MESSAGES/lingmosdk-sysinfo.mo || true
mv /usr/share/locale/ky/LC_MESSAGES/lingmosdk-sysinfo_ky.mo /usr/share/locale/ky/LC_MESSAGES/lingmosdk-sysinfo.mo || true
mv /usr/share/locale/de/LC_MESSAGES/lingmosdk-sysinfo_de.mo /usr/share/locale/de/LC_MESSAGES/lingmosdk-sysinfo.mo || true
mv /usr/share/locale/es/LC_MESSAGES/lingmosdk-sysinfo_es.mo /usr/share/locale/es/LC_MESSAGES/lingmosdk-sysinfo.mo || true
mv /usr/share/locale/fr/LC_MESSAGES/lingmosdk-sysinfo_fr.mo /usr/share/locale/fr/LC_MESSAGES/lingmosdk-sysinfo.mo || true
mv /usr/share/locale/ug/LC_MESSAGES/lingmosdk-sysinfo_ug.mo /usr/share/locale/ug/LC_MESSAGES/lingmosdk-sysinfo.mo || true

if systemctl is-active --quiet lingmosdk-dbus.service; then
    echo "lingmosdk-dbus.service is active, restarting..."
    systemctl restart lingmosdk-dbus.service
else
    echo "lingmosdk-dbus.service is not active"
fi
