if systemctl is-active --quiet lingmosdk-dbus.service; then
    echo "lingmosdk-dbus.service is active, restarting..."
    systemctl restart lingmosdk-dbus.service
else
    echo "lingmosdk-dbus.service is not active"
fi

mv /usr/share/locale/zh_CN/LC_MESSAGES/lingmosdk-hardware_zh_CN.mo /usr/share/locale/zh_CN/LC_MESSAGES/lingmosdk-hardware.mo || true
mv /usr/share/locale/bo_CN/LC_MESSAGES/lingmosdk-hardware_bo_CN.mo /usr/share/locale/bo_CN/LC_MESSAGES/lingmosdk-hardware.mo || true
mv /usr/share/locale/mn/LC_MESSAGES/lingmosdk-hardware_mn.mo /usr/share/locale/mn/LC_MESSAGES/lingmosdk-hardware.mo || true
mv /usr/share/locale/zh_HK/LC_MESSAGES/lingmosdk-hardware_zh_HK.mo /usr/share/locale/zh_HK/LC_MESSAGES/lingmosdk-hardware.mo || true
mv /usr/share/locale/kk/LC_MESSAGES/lingmosdk-hardware_kk.mo /usr/share/locale/kk/LC_MESSAGES/lingmosdk-hardware.mo || true
mv /usr/share/locale/ky/LC_MESSAGES/lingmosdk-hardware_ky.mo /usr/share/locale/ky/LC_MESSAGES/lingmosdk-hardware.mo || true
mv /usr/share/locale/de/LC_MESSAGES/lingmosdk-hardware_de.mo /usr/share/locale/de/LC_MESSAGES/lingmosdk-hardware.mo || true
mv /usr/share/locale/es/LC_MESSAGES/lingmosdk-hardware_es.mo /usr/share/locale/es/LC_MESSAGES/lingmosdk-hardware.mo || true
mv /usr/share/locale/fr/LC_MESSAGES/lingmosdk-hardware_fr.mo /usr/share/locale/fr/LC_MESSAGES/lingmosdk-hardware.mo || true
mv /usr/share/locale/ug/LC_MESSAGES/lingmosdk-hardware_ug.mo /usr/share/locale/ug/LC_MESSAGES/lingmosdk-hardware.mo || true