usr/lib/*/libkysysinfo.so*
po/lingmosdk-sysinfo_mn.mo usr/share/locale/mn/LC_MESSAGES/
po/lingmosdk-sysinfo_zh_CN.mo usr/share/locale/zh_CN/LC_MESSAGES/
po/lingmosdk-sysinfo_bo_CN.mo usr/share/locale/bo_CN/LC_MESSAGES/
po/lingmosdk-sysinfo_zh_HK.mo usr/share/locale/zh_HK/LC_MESSAGES/
po/lingmosdk-sysinfo_kk.mo usr/share/locale/kk/LC_MESSAGES/
po/lingmosdk-sysinfo_ky.mo usr/share/locale/ky/LC_MESSAGES/
po/lingmosdk-sysinfo_de.mo usr/share/locale/de/LC_MESSAGES/
po/lingmosdk-sysinfo_es.mo usr/share/locale/es/LC_MESSAGES/
po/lingmosdk-sysinfo_fr.mo usr/share/locale/fr/LC_MESSAGES/
po/lingmosdk-sysinfo_ug.mo usr/share/locale/ug/LC_MESSAGES/