[Icon Theme]
Name=Oxygen
Comment=Oxygen icon theme
Hidden=false
Directories=22x22/actions,22x22/animations,22x22/apps,22x22/mimetypes,32x32/apps

[22x22/actions]
Size=22
Context=Actions
Type=Threshold

[22x22/animations]
Size=22
Context=Animations
Type=Threshold

[22x22/apps]
Size=22
Context=Applications
Type=Threshold

[22x22/mimetypes]
Size=22
Context=MimeTypes
Type=Threshold

[32x32/apps]
Size=32
Context=Applications
Type=Threshold
