#!/bin/bash
display_daemon="/usr/lib/lingmo-daemon/greeter-display-daemon"
if [ -x $display_daemon ]; then
    $display_daemon &
fi
xsettingsd_conf="/etc/lightdm/lingmo/xsettingsd.conf"
if [ -e $xsettingsd_conf ]; then
    xsettingsd -c $xsettingsd_conf &
fi
/usr/bin/lightdm-lingmo-greeter
