[Desktop Entry]
Name=Lingmo Windowed
Name[ar]=بلازما المؤطرة
Name[az]=Pəncərədə Lingmo
Name[be]=Плазмоіды як праграмы
Name[bg]=Lingmo уиджети в самостоятелен прозорец
Name[bs]=Plazma uprozorena
Name[ca]=Lingmo amb finestres
Name[ca@valencia]=Lingmo amb finestres
Name[cs]=Lingmo v okně
Name[da]=Lingmo i vinduestilstand
Name[de]=Lingmo-Fenster
Name[el]=Lingmo σε παράθυρα
Name[en_GB]=Lingmo Windowed
Name[eo]=Lingmo Enfenestra
Name[es]=Lingmo en ventanas
Name[et]=Akendesse paigutatud Lingmo
Name[eu]=Lingmo leihoetan
Name[fi]=Ikkunoitu Lingmo
Name[fr]=Lingmo fenêtré
Name[gl]=Lingmo en xanelas
Name[he]=פלזמה בחלונות
Name[hi]=प्लाज़्मा विंडोड
Name[hu]=Ablakban futtatott plazma
Name[ia]=Lingmo Windowed (in fenestras)
Name[id]=Perjendelaan Lingmo
Name[is]=Lingmo í gluggum
Name[it]=Lingmo a finestre
Name[ja]=ウインドウ化された Lingmo
Name[ka]=Lingmo ფანჯარაში
Name[ko]=창 모드 Lingmo
Name[lt]=Languota Lingmo
Name[lv]=Lingmo Windowed
Name[ml]=പ്ലാസ്മ ജാലകീകരിച്ചത്
Name[nb]=Lingmo i vindu
Name[nds]=Lingmo-Finstern
Name[nl]=Lingmo weergegeven in vensters
Name[nn]=Lingmo i vindauge
Name[pa]=ਪਲਾਜ਼ਮਾ ਵਿੰਡੋ
Name[pl]=Okienkowa Plazma
Name[pt]=Lingmo em Janelas
Name[pt_BR]=Lingmo em janelas
Name[ro]=Lingmo în fereastră
Name[ru]=Lingmo в окне
Name[sa]=प्लाज्मा गवाक्षयुक्त
Name[sk]=Lingmo v okne
Name[sl]=Okenski način Lingmo
Name[sr]=Плазма у прозору
Name[sr@ijekavian]=Плазма у прозору
Name[sr@ijekavianlatin]=Lingmo u prozoru
Name[sr@latin]=Lingmo u prozoru
Name[sv]=Lingmo i fönster
Name[ta]=சாளர பிளாஸ்மாய்டுகள்
Name[tr]=Lingmo Penceresi
Name[uk]=Плазма у вікні
Name[vi]=Lingmo cửa sổ hoá
Name[x-test]=xxLingmo Windowedxx
Name[zh_CN]=窗口化 Lingmo
Name[zh_TW]=Lingmo 視窗
Comment=Run Plasmoids as simple applications
Comment[ar]=شغل بلازمويد كتطبيق بسيط
Comment[az]=Lingmo əlavəsini adi tətbiq kimi başlatmaq
Comment[be]=Запуск плазмоідаў як простых праграм
Comment[bg]=Стартиране на уиджетите на Lingmo като прости приложения
Comment[bs]=Pokreni plazmoide kao običnu aplikaciju
Comment[ca]=Executa els plasmoides com a simples aplicacions
Comment[ca@valencia]=Executa els plasmoides com a simples aplicacions
Comment[cs]=Spouštějte Plasmoidy jako prosté aplikace
Comment[da]=Kør plasmoids som simple programmer
Comment[de]=Ausführung von Plasmoiden als einfache Anwendungen
Comment[el]=Εκτέλεση πλασμοειδών ως απλές εφαρμογές
Comment[en_GB]=Run Plasmoids as simple applications
Comment[eo]=Ruligi Plasmoidojn kiel simplaj aplikaĵoj
Comment[es]=Ejecutar plasmoides como aplicaciones simples
Comment[et]=Plasmoidide käivitamine tavaliste rakendustena
Comment[eu]=Exekutatu Plasmoideak aplikazio arrunt gisa
Comment[fi]=Suorita plasmoideja sovelluksina
Comment[fr]=Lancer les plasmoïdes comme de simples applications
Comment[gl]=Executar trebellos como aplicacións sinxelas.
Comment[he]=הצגת Plasmoids כיישומים פשוטים
Comment[hi]=प्लाज़्मोइड को सरल अनुप्रयोगों के रूप में चलाएँ
Comment[hu]=Plasmoidok futtatása egyszerű alkalmazásként
Comment[ia]=Executa Plasmoids como applicationes simple
Comment[id]=Menjalankan Plasmoids sebagai aplikasi sederhana
Comment[is]=Keyra Lingmo-græjur sem einföld forrit
Comment[it]=Esegui i plasmoidi come semplici applicazioni
Comment[ja]=Plasmoid を単純なアプリケーションとして実行
Comment[ka]=პლაზმოიდების ცალკე აპლიკაციებად გაშვება
Comment[ko]=Plasmoid를 간단한 앱으로 실행
Comment[lt]=Paleisti Lingmo įskiepius kaip paprastas programas
Comment[lv]=Palaist plazmoīdus kā vienkāršas programmas
Comment[ml]=ലളിതമായ ആപ്ലിക്കേഷനുകളായി പ്ലാസ്മോയിഡുകൾ പ്രവർത്തിപ്പിക്കുക
Comment[nb]=Kjør plasmoider som enkle programmer
Comment[nds]=Lingmo-Lüttprogrammen as eenfach Programmen utföhren
Comment[nl]=Plasmoids uitvoeren als eenvoudige toepassingen
Comment[nn]=Køyr skjermelement som enkle program
Comment[pa]=ਪਲਾਜ਼ਮੋਡ ਨੂੰ ਸਰਲ ਐਪਲੀਕੇਸ਼ਨਾਂ ਵਜੋਂ ਚਲਾਓ
Comment[pl]=Uruchamia Plazmoidy jako proste aplikacje
Comment[pt]=Executar os plasmóides como aplicações simples
Comment[pt_BR]=Executa os plasmoides como aplicativos simples
Comment[ro]=Rulează plasmoizi ca simple aplicații
Comment[ru]=Запуск виджетов Lingmo в качестве оконных приложений
Comment[sa]=प्लाज्मोइड्स् सरल-अनुप्रयोगरूपेण चालयन्तु
Comment[sk]=Spúšťať Plazmoidy ako jednoduché aplikácie
Comment[sl]=Zaganjajte Plasmoide kot preproste programe
Comment[sr]=Извршавање плазмоида као простих програма
Comment[sr@ijekavian]=Извршавање плазмоида као простих програма
Comment[sr@ijekavianlatin]=Izvršavanje plazmoida kao prostih programa
Comment[sr@latin]=Izvršavanje plazmoida kao prostih programa
Comment[sv]=Kör Plasmoider som enkla program
Comment[ta]=பிளாஸ்மாய்டுகளை தனிப்பட்ட செயலிகளாக இயக்கும்
Comment[tr]=Plasmoid’leri basit uygulamalar olarak çalıştır
Comment[uk]=Запуск плазмоїдів як простих програм
Comment[vi]=Chạy các Plasmoid như các ứng dụng đơn giản
Comment[x-test]=xxRun Plasmoids as simple applicationsxx
Comment[zh_CN]=将小部件当作简单应用程序运行
Comment[zh_TW]=以簡單應用程式執行 Lingmo 小元件

Exec=@CMAKE_INSTALL_PREFIX@/bin/lingmowindowed
Terminal=false
NoDisplay=true
Icon=lingmo
Type=Application
X-DBUS-StartupType=Unique
InitialPreference=1
X-KDE-Wayland-Interfaces=org_kde_lingmo_window_management,org_kde_kwin_keystate,zkde_screencast_unstable_v1,org_kde_lingmo_activation_feedback
