Document: liblingmo-chkname
Title: Debian liblingmo-chkname Manual
Author: <insert document author here>
Abstract: This manual describes what liblingmo-chkname is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/liblingmo-chkname/liblingmo-chkname.sgml.gz

Format: postscript
Files: /usr/share/doc/liblingmo-chkname/liblingmo-chkname.ps.gz

Format: text
Files: /usr/share/doc/liblingmo-chkname/liblingmo-chkname.text.gz

Format: HTML
Index: /usr/share/doc/liblingmo-chkname/html/index.html
Files: /usr/share/doc/liblingmo-chkname/html/*.html
