mv  usbdevice.svg            usbdevice_20px.svg       
mv  cpu.svg                  cpu_20px.svg        
mv  storage.svg              storage_20px.svg         
mv  printer.svg              printer_20px.svg         
mv  battery.svg              battery_20px.svg         
mv  overview.svg             overview_20px.svg        
mv  keyboard.svg             keyboardv.svg        
mv  bluetooth.svg            bluetoothv.svg       
mv  memory.svg               memory_20px.svg          
mv  otherinputdevice.svg     otherinputdevice_20px.svg
mv  otherpcidevice.svg       otherpcidevice_20px.svg  
mv  mouse.svg                mouse_20px.svg           
mv  camera.svg               camera_20px.svg          
mv  networkadapter.svg       networkadapter_20px.svg  
mv  monitor.svg              monitor_20px.svg         
mv  displayadapter.svg       displayadapter_20px.svg  
mv  audiodevice.svg          audiodevice_20px.svg     
mv  motherboard.svg          motherboard_20px.svg     
mv  cdrom.svg                cdrom_20px.svg 
