# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/kuserfeedback/src/console/schemaeditor/aggregationeditwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KUserFeedback::Console::AggregationEditWidget(object):
    def setupUi(self, KUserFeedback::Console::AggregationEditWidget):
        KUserFeedback::Console::AggregationEditWidget.setObjectName("KUserFeedback::Console::AggregationEditWidget")
        KUserFeedback::Console::AggregationEditWidget.resize(542, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(KUserFeedback::Console::AggregationEditWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(KUserFeedback::Console::AggregationEditWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.aggregationView = QtWidgets.QTreeView(self.splitter)
        self.aggregationView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.aggregationView.setRootIsDecorated(False)
        self.aggregationView.setUniformRowHeights(True)
        self.aggregationView.setObjectName("aggregationView")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.elementView = QtWidgets.QTreeView(self.widget)
        self.elementView.setRootIsDecorated(False)
        self.elementView.setUniformRowHeights(True)
        self.elementView.setObjectName("elementView")
        self.verticalLayout.addWidget(self.elementView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.addButton = QtWidgets.QPushButton(self.widget)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.deleteButton = QtWidgets.QPushButton(self.widget)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.splitter)
        self.actionAddAggregation = QtWidgets.QAction(KUserFeedback::Console::AggregationEditWidget)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.actionAddAggregation.setIcon(icon)
        self.actionAddAggregation.setObjectName("actionAddAggregation")
        self.actionDeleteAggregation = QtWidgets.QAction(KUserFeedback::Console::AggregationEditWidget)
        icon = QtGui.QIcon.fromTheme("edit-delete")
        self.actionDeleteAggregation.setIcon(icon)
        self.actionDeleteAggregation.setObjectName("actionDeleteAggregation")

        self.retranslateUi(KUserFeedback::Console::AggregationEditWidget)
        QtCore.QMetaObject.connectSlotsByName(KUserFeedback::Console::AggregationEditWidget)

    def retranslateUi(self, KUserFeedback::Console::AggregationEditWidget):
        _translate = QtCore.QCoreApplication.translate
        self.addButton.setText(_translate("KUserFeedback::Console::AggregationEditWidget", "&Add"))
        self.deleteButton.setText(_translate("KUserFeedback::Console::AggregationEditWidget", "&Delete"))
        self.actionAddAggregation.setText(_translate("KUserFeedback::Console::AggregationEditWidget", "Add &Aggregation"))
        self.actionAddAggregation.setToolTip(_translate("KUserFeedback::Console::AggregationEditWidget", "Add a new aggregation."))
        self.actionDeleteAggregation.setText(_translate("KUserFeedback::Console::AggregationEditWidget", "&Delete Aggregation"))
        self.actionDeleteAggregation.setToolTip(_translate("KUserFeedback::Console::AggregationEditWidget", "Delete the currently selected aggregation."))
