#!/bin/sh

set -e

if [ "$1" = "configure" ];then
    update-alternatives --install /var/lib/AccountsService/icons/default \
        default-account-icon /var/lib/AccountsService/icons/animal/raccoon.png 0
fi

#DEBHELPER#
exit 0
