.TH LIVE\-BUILD 1 2020\-03\-30 1:20191222 "Debian Live Project"

.SH NAME
\fBlingmo-sys-build_installer\fR \- Complete the installer stage

.SH SYNOPSIS
\fBlingmo-sys-build installer\fR [\fIOPTIONS\fR]

.SH DESCRIPTION
\fBlingmo-sys-build installer\fR is a high\-level command (porcelain) of \fIlive\-build\fR(7), the Debian Live tool suite.
.PP
\fBlingmo-sys-build installer\fR calls all necessary live\-build programs in the correct order to complete the installer stage.

.SH OPTIONS
\fBlingmo-sys-build installer\fR has no specific options but understands all generic live\-build options. See \fIlive\-build\fR(7) for a complete list of all generic live\-build options.

.SH FILES
.IP "\fBnone\fR" 4

.SH SEE ALSO
\fIlive\-build\fR(7)
.PP
This program is a part of live\-build.

.SH HOMEPAGE
More information about live\-build and the Debian Live project can be found on the homepage at <\fIhttps://wiki.debian.org/DebianLive\fR>.

.SH BUGS
Bugs can be reported by submitting a bug report for the live\-build package in the Bug Tracking System at <\fIhttp://bugs.debian.org/\fR> or by writing a mail to the Debian Live mailing list at <\fIdebian-live@lists.debian.org\fR>.

.SH AUTHOR
live\-build was originally written by Daniel Baumann <\fImail@daniel-baumann.ch\fR>. Since 2016 development has been continued by the Debian Live team.
