#!/bin/bash
#1030专业版已发布版本上，default-settings版本2020.11.23，在用户视频目录内的软链接 添加了专业版，服务器版，社区版视频区分，实现动态指向生成. 
#而原有借口视频为demo.mp4, 不区分镜像。导致在欢迎升级中产生了不少问题。
#default-settings从2020.12.17版本开始， 在用户视频目录内的软链接 还原成统一demo.mp4接口，不区分镜像。
#为解决1030专业版上用户视频目录内的软链接指向为professional.mp4特殊增加一级软链接，以实现兼容）。在其他版本下面这个软链接毫无用处。
#欢迎5.6.0.30版本(1030专业版)为区分镜像视频名称。从5.6.0.33版本后视频名称统一为demo.mp4
ln -s -f /usr/share/dde-introduction/demo.mp4  /usr/share/dde-introduction/professional.mp4