# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/lingmo-workspace/freespacenotifier/freespacenotifier_prefs_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_freespacenotifier_prefs_base(object):
    def setupUi(self, freespacenotifier_prefs_base):
        freespacenotifier_prefs_base.setObjectName("freespacenotifier_prefs_base")
        freespacenotifier_prefs_base.resize(320, 217)
        self.gridLayout = QtWidgets.QGridLayout(freespacenotifier_prefs_base)
        self.gridLayout.setObjectName("gridLayout")
        self.kcfg_enableNotification = QtWidgets.QCheckBox(freespacenotifier_prefs_base)
        self.kcfg_enableNotification.setChecked(True)
        self.kcfg_enableNotification.setObjectName("kcfg_enableNotification")
        self.gridLayout.addWidget(self.kcfg_enableNotification, 0, 0, 1, 1)
        self.label_minimumSpace = QtWidgets.QLabel(freespacenotifier_prefs_base)
        self.label_minimumSpace.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_minimumSpace.setObjectName("label_minimumSpace")
        self.gridLayout.addWidget(self.label_minimumSpace, 1, 0, 1, 1)
        self.kcfg_minimumSpace = QtWidgets.QSpinBox(freespacenotifier_prefs_base)
        self.kcfg_minimumSpace.setObjectName("kcfg_minimumSpace")
        self.gridLayout.addWidget(self.kcfg_minimumSpace, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)

        self.retranslateUi(freespacenotifier_prefs_base)
        self.kcfg_enableNotification.toggled['bool'].connect(self.kcfg_minimumSpace.setEnabled) # type: ignore
        self.kcfg_enableNotification.toggled['bool'].connect(self.label_minimumSpace.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(freespacenotifier_prefs_base)

    def retranslateUi(self, freespacenotifier_prefs_base):
        _translate = QtCore.QCoreApplication.translate
        self.kcfg_enableNotification.setText(_translate("freespacenotifier_prefs_base", "Enable low disk space warning"))
        self.label_minimumSpace.setText(_translate("freespacenotifier_prefs_base", "Warn when free space is below:"))
        self.kcfg_minimumSpace.setSuffix(_translate("freespacenotifier_prefs_base", " MiB"))
