# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/LingmoOS/shell/bc/Terminal/qmltermwidget/lib/SearchBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchBar(object):
    def setupUi(self, SearchBar):
        SearchBar.setObjectName("SearchBar")
        SearchBar.resize(399, 40)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SearchBar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.closeButton = QtWidgets.QToolButton(SearchBar)
        icon = QtGui.QIcon.fromTheme("dialog-close")
        self.closeButton.setIcon(icon)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.findLabel = QtWidgets.QLabel(SearchBar)
        self.findLabel.setObjectName("findLabel")
        self.horizontalLayout.addWidget(self.findLabel)
        self.searchTextEdit = QtWidgets.QLineEdit(SearchBar)
        self.searchTextEdit.setObjectName("searchTextEdit")
        self.horizontalLayout.addWidget(self.searchTextEdit)
        self.findPreviousButton = QtWidgets.QToolButton(SearchBar)
        icon = QtGui.QIcon.fromTheme("go-previous")
        self.findPreviousButton.setIcon(icon)
        self.findPreviousButton.setObjectName("findPreviousButton")
        self.horizontalLayout.addWidget(self.findPreviousButton)
        self.findNextButton = QtWidgets.QToolButton(SearchBar)
        icon = QtGui.QIcon.fromTheme("go-next")
        self.findNextButton.setIcon(icon)
        self.findNextButton.setObjectName("findNextButton")
        self.horizontalLayout.addWidget(self.findNextButton)
        self.optionsButton = QtWidgets.QToolButton(SearchBar)
        icon = QtGui.QIcon.fromTheme("preferences-system")
        self.optionsButton.setIcon(icon)
        self.optionsButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.optionsButton.setObjectName("optionsButton")
        self.horizontalLayout.addWidget(self.optionsButton)

        self.retranslateUi(SearchBar)
        QtCore.QMetaObject.connectSlotsByName(SearchBar)

    def retranslateUi(self, SearchBar):
        _translate = QtCore.QCoreApplication.translate
        SearchBar.setWindowTitle(_translate("SearchBar", "SearchBar"))
        self.closeButton.setText(_translate("SearchBar", "X"))
        self.findLabel.setText(_translate("SearchBar", "Find:"))
        self.findPreviousButton.setText(_translate("SearchBar", "<"))
        self.findNextButton.setText(_translate("SearchBar", ">"))
        self.optionsButton.setText(_translate("SearchBar", "..."))
