# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lingmo/project/nx_pkg/LingmoOS/shell/frameworks/print-manager/src/libkcups/SelectMakeModel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectMakeModel(object):
    def setupUi(self, SelectMakeModel):
        SelectMakeModel.setObjectName("SelectMakeModel")
        SelectMakeModel.resize(467, 358)
        self.gridLayout = QtWidgets.QGridLayout(SelectMakeModel)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.ppdFilePathUrl = KUrlRequester(SelectMakeModel)
        self.ppdFilePathUrl.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ppdFilePathUrl.sizePolicy().hasHeightForWidth())
        self.ppdFilePathUrl.setSizePolicy(sizePolicy)
        self.ppdFilePathUrl.setObjectName("ppdFilePathUrl")
        self.gridLayout.addWidget(self.ppdFilePathUrl, 3, 1, 1, 1)
        self.splitter = QtWidgets.QSplitter(SelectMakeModel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.makeView = QtWidgets.QListView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makeView.sizePolicy().hasHeightForWidth())
        self.makeView.setSizePolicy(sizePolicy)
        self.makeView.setObjectName("makeView")
        self.ppdsLV = QtWidgets.QListView(self.splitter)
        self.ppdsLV.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ppdsLV.setObjectName("ppdsLV")
        self.gridLayout.addWidget(self.splitter, 2, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButtonSelectDriver = QtWidgets.QRadioButton(SelectMakeModel)
        self.radioButtonSelectDriver.setChecked(True)
        self.radioButtonSelectDriver.setObjectName("radioButtonSelectDriver")
        self.horizontalLayout.addWidget(self.radioButtonSelectDriver)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.ppdFileRB = QtWidgets.QRadioButton(SelectMakeModel)
        self.ppdFileRB.setObjectName("ppdFileRB")
        self.gridLayout.addWidget(self.ppdFileRB, 3, 0, 1, 1)
        self.messageWidget = KMessageWidget(SelectMakeModel)
        self.messageWidget.setObjectName("messageWidget")
        self.gridLayout.addWidget(self.messageWidget, 0, 0, 1, 2)

        self.retranslateUi(SelectMakeModel)
        self.ppdFileRB.toggled['bool'].connect(self.ppdFilePathUrl.setEnabled) # type: ignore
        self.ppdFileRB.clicked.connect(self.ppdFilePathUrl.setFocus) # type: ignore
        self.radioButtonSelectDriver.toggled['bool'].connect(self.makeView.setEnabled) # type: ignore
        self.radioButtonSelectDriver.toggled['bool'].connect(self.ppdsLV.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SelectMakeModel)

    def retranslateUi(self, SelectMakeModel):
        _translate = QtCore.QCoreApplication.translate
        SelectMakeModel.setWindowTitle(_translate("SelectMakeModel", "Select a Driver"))
        self.radioButtonSelectDriver.setText(_translate("SelectMakeModel", "Choose &the driver"))
        self.ppdFileRB.setText(_translate("SelectMakeModel", "Ma&nually Provide a PPD File:"))
from kmessagewidget import KMessageWidget
from kurlrequester import KUrlRequester
