name: Test

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    name: Building System
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Update source
        run: sudo apt update

      - name: Install base packages
        run: sudo apt install -y sudo tree dctrl-tools devscripts wget isolinux syslinux binutils build-essential diffutils gcc g++ bash patch gzip bzip2 perl tar cpio unzip rsync file bc findutils make sed python3 cvs git mercurial subversion libncurses5 asciidoc w3m python3-argparse-addons dblatex python3-aiohttp python3-matplotlib graphviz

      - name: Init build
        run: cp -v system/GEN_CONFIG .config
      
      - name: Build System
        run: make -j18
      
      - name: Check output
        run: |
            ls output/
            tree output/
