#cmakedefine01 HAVE_STRUCT_UCRED
#cmakedefine01 HAVE_SETPRIORITY
#cmakedefine01 HAVE_GETPEEREID
#cmakedefine01 HAVE_X11
#cmakedefine01 HAVE_INITGROUPS
#cmakedefine01 HAVE_SYS_SELECT_H
#define CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"
#define KDE_INSTALL_FULL_LIBEXECDIR_KF "${KDE_INSTALL_FULL_LIBEXECDIR_KF}"
