{
    "KPlugin": {
        "Authors": [
            {
                "Email": "kde-artists@kde.org",
                "Name": "KDE Visual Design Group",
                "Name[ar]": "مجموعة التصميم المرئي لكِيدِي",
                "Name[az]": "KDE Vizual Dizayn Qrupu",
                "Name[be]": "Суполка візуальнага дызайну KDE",
                "Name[ca@valencia]": "Grup de disseny visual de KDE",
                "Name[ca]": "Grup de disseny visual de KDE",
                "Name[cs]": "Skupina vizuálního návrhu KDE",
                "Name[eo]": "KDE Vida Dezajna Grupo",
                "Name[es]": "El grupo de diseño visual de KDE",
                "Name[eu]": "KDE Diseinu bisualeko taldea",
                "Name[fi]": "KDE:n visuaalinen suunnitteluryhmä",
                "Name[fr]": "Groupe de conception graphique de KDE « VDG » (Visual Design Group)",
                "Name[gl]": "Grupo de deseño visual de KDE",
                "Name[he]": "קבוצת העיצוב החזותי של KDE",
                "Name[ia]": "KDE Visual Design Group (Gruppo de Designo Visual de KDE)",
                "Name[id]": "Grup Desain Visual KDE",
                "Name[is]": "Myndrænn hönnunarhópur KDE",
                "Name[ko]": "KDE 시각 디자인 그룹",
                "Name[lt]": "KDE vaizdinio dizaino grupė",
                "Name[lv]": "KDE Vizuālā dizaina grupa",
                "Name[nl]": "KDE Visuele ontwerpgroep",
                "Name[pl]": "Grupa oprawy graficznej KDE",
                "Name[pt]": "Grupo de Desenho Visual do KDE",
                "Name[pt_BR]": "Grupo de design visual do KDE (KDE VDG)",
                "Name[ru]": "Группа KDE Visual Design",
                "Name[sl]": "Skupina vizualnega designa KDE",
                "Name[sv]": "KDE:s visuella designgrupp",
                "Name[ta]": "கே.டீ.யீ. வரைகலை வடிவமைப்புக் குழு",
                "Name[tr]": "KDE Görsel Tasarım Grubu",
                "Name[uk]": "Група з візуального дизайну KDE",
                "Name[vi]": "Đội Thiết kế Trực quan KDE",
                "Name[x-test]": "xxKDE Visual Design Groupxx",
                "Name[zh_CN]": "KDE 视觉设计团队",
                "Name[zh_TW]": "KDE VDG 視覺設計組"
            }
        ],
        "Category": "",
        "Description": "Ocean by the KDE VDG",
        "Description[ar]": "نسيم من مجموعة تصميم كِيدِي",
        "Description[az]": "KDE VDG tərəfindən Ocean İş mühiti görünüşü",
        "Description[be]": "Ocean ад KDE VDG",
        "Description[bg]": "Ocean от KDE VDG",
        "Description[ca@valencia]": "Brisa, creat pel VDG de KDE",
        "Description[ca]": "Brisa, creat pel VDG del KDE",
        "Description[cs]": "Ocean od KDE VDG",
        "Description[de]": "Ocean von der KDE VDG",
        "Description[eo]": "Brizo de la KDE VDG",
        "Description[es]": "Brisa, por KDE VDG",
        "Description[eu]": "Brisa KDEren VDGk egina",
        "Description[fi]": "Ocean KDE VDG:ltä",
        "Description[fr]": "Ocean par l'équipe « KDE VDG »",
        "Description[gl]": "Brisa do KDE VDG.",
        "Description[he]": "בריזה מאת קבוצת העיצוב החזותי של KDE",
        "Description[hu]": "Ocean a KDE VDG-től",
        "Description[ia]": "Ocean (Brisa) per le KDE VDG",
        "Description[id]": "Ocean oleh KDE VDG",
        "Description[is]": "Ocean frá KDE VDG",
        "Description[it]": "Brezza a cura del KDE VDG",
        "Description[ka]": "Ocean KDE VDG-სგან",
        "Description[ko]": "KDE 시각 디자인 그룹에서 제작한 Ocean",
        "Description[lt]": "Ocean pagal KDE VDG",
        "Description[lv]": "KDE VDG veidotā „Ocean“",
        "Description[nl]": "Ocean door de KDE VDG",
        "Description[nn]": "Ocean frå KDE VDG",
        "Description[pl]": "Bryza autorstwa KDE VDG",
        "Description[pt]": "Brisa da VDG do KDE",
        "Description[pt_BR]": "Ocean pelo KDE VDG",
        "Description[ro]": "Briză, de KDE VDG",
        "Description[ru]": "Оформление рабочей среды Ocean от KDE VDG",
        "Description[sa]": "KDE VDG द्वारा Ocean",
        "Description[sk]": "Vánok od KDE VDG",
        "Description[sl]": "Sapica od KDE VDG",
        "Description[sv]": "Ocean av KDE:s visuella designgrupp",
        "Description[ta]": "கே.டீ.யீ. VDG வழங்கும் பிரீஸ்",
        "Description[tr]": "KDE VDG tarafından Esinti",
        "Description[uk]": "Ocean, автори — KDE VDG",
        "Description[vi]": "Ocean, do KDE VDG",
        "Description[x-test]": "xxOcean by the KDE VDGxx",
        "Description[zh_CN]": "Ocean 微风主题，由 KDE VDG (视觉设计团队) 设计制作",
        "Description[zh_TW]": "由 KDE VDG 設計的 Ocean",
        "EnabledByDefault": true,
        "Id": "default",
        "License": "LGPL",
        "Name": "Ocean",
        "Name[ar]": "نسيم",
        "Name[ca@valencia]": "Brisa",
        "Name[ca]": "Brisa",
        "Name[eo]": "Vento",
        "Name[es]": "Brisa",
        "Name[eu]": "Brisa",
        "Name[gl]": "Brisa",
        "Name[he]": "בריזה",
        "Name[ia]": "Brisa",
        "Name[it]": "Brezza",
        "Name[ka]": "ნიავი",
        "Name[pl]": "Bryza",
        "Name[pt]": "Brisa",
        "Name[ro]": "Briză",
        "Name[sk]": "Vánok",
        "Name[sl]": "Sapica",
        "Name[ta]": "பிரீஸ்",
        "Name[tr]": "Esinti",
        "Name[x-test]": "xxOceanxx",
        "Name[zh_CN]": "Ocean 微风",
        "Version": "@KF6_MIN_VERSION@",
        "Website": "https://www.kde.org/"
    },
    "X-Lingmo-API": "5.0"
}
