#ifndef KUSERREGISTER_GLOBAL_H
#define KUSERREGISTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KUSERREGISTER_LIBRARY)
#  define KUSERREGISTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define KUSERREGISTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // KUSERREGISTER_GLOBAL_H
